<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiver'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiver'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Indt'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Omkostninger'));
InsertRecord('accountgroups',array('groupname'),array('AKTIEKAPITAL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('AKTIEKAPITAL','20','0','6000',''));
InsertRecord('accountgroups',array('groupname'),array('AKTIVER'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('AKTIVER','10','0','3000',''));
InsertRecord('accountgroups',array('groupname'),array('ANDEN INDT'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ANDEN INDT','30','1','10000',''));
InsertRecord('accountgroups',array('groupname'),array('EGENKAPITAL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('EGENKAPITAL','20','0','7000',''));
InsertRecord('accountgroups',array('groupname'),array('GENERELLE & ADMINISTRATIVE UDG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GENERELLE & ADMINISTRATIVE UDG','40','1','13000',''));
InsertRecord('accountgroups',array('groupname'),array('KONSULENTINDT'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('KONSULENTINDT','30','1','9000',''));
InsertRecord('accountgroups',array('groupname'),array('KORTFRISTEDE AKTIVER'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('KORTFRISTEDE AKTIVER','10','0','1000',''));
InsertRecord('accountgroups',array('groupname'),array('KORTFRISTET G'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('KORTFRISTET G','20','0','4000',''));
InsertRecord('accountgroups',array('groupname'),array('L'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('L','40','1','12000',''));
InsertRecord('accountgroups',array('groupname'),array('LAGER-AKTIVER'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('LAGER-AKTIVER','10','0','2000',''));
InsertRecord('accountgroups',array('groupname'),array('LANGFRISTET G'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('LANGFRISTET G','20','0','5000',''));
InsertRecord('accountgroups',array('groupname'),array('SALGSINDT'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('SALGSINDT','30','1','8000',''));
InsertRecord('accountgroups',array('groupname'),array('SALGSOMKOSTNINGER'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('SALGSOMKOSTNINGER','40','1','11000',''));
InsertRecord('chartmaster',array('accountcaode'),array('1061'),array('accountcode','accountname','group_'),array('1061','Bank','KORTFRISTEDE AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1065'),array('accountcode','accountname','group_'),array('1065','Kasse','KORTFRISTEDE AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1200'),array('accountcode','accountname','group_'),array('1200','Indbetalinger','KORTFRISTEDE AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1205'),array('accountcode','accountname','group_'),array('1205','Hens','KORTFRISTEDE AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1210'),array('accountcode','accountname','group_'),array('1210','Moms indg','KORTFRISTEDE AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1520'),array('accountcode','accountname','group_'),array('1520','Lager / udstyr','LAGER-AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1530'),array('accountcode','accountname','group_'),array('1530','Lager / programmel','LAGER-AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1540'),array('accountcode','accountname','group_'),array('1540','Lager / till','LAGER-AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1550'),array('accountcode','accountname','group_'),array('1550','Lager / arrangementer','LAGER-AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1820'),array('accountcode','accountname','group_'),array('1820','Kontorinventar og -udstyr','AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1825'),array('accountcode','accountname','group_'),array('1825','Samlede afskrivninger, inventar, udstyr','AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1840'),array('accountcode','accountname','group_'),array('1840','K','AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('1845'),array('accountcode','accountname','group_'),array('1845','Samlede afskrivninger, k','AKTIVER'));
InsertRecord('chartmaster',array('accountcaode'),array('2100'),array('accountcode','accountname','group_'),array('2100','Udbetalinger','KORTFRISTET G'));
InsertRecord('chartmaster',array('accountcaode'),array('2160'),array('accountcode','accountname','group_'),array('2160','Selskabsskat','KORTFRISTET G'));
InsertRecord('chartmaster',array('accountcaode'),array('2190'),array('accountcode','accountname','group_'),array('2190','Afgifter','KORTFRISTET G'));
InsertRecord('chartmaster',array('accountcaode'),array('2311'),array('accountcode','accountname','group_'),array('2311','Moms udg','KORTFRISTET G'));
InsertRecord('chartmaster',array('accountcaode'),array('2620'),array('accountcode','accountname','group_'),array('2620','Bankl','LANGFRISTET G'));
InsertRecord('chartmaster',array('accountcaode'),array('3350'),array('accountcode','accountname','group_'),array('3350','Almindelige aktier','AKTIEKAPITAL'));
InsertRecord('chartmaster',array('accountcaode'),array('3510'),array('accountcode','accountname','group_'),array('3510','Egenkapital primo','EGENKAPITAL'));
InsertRecord('chartmaster',array('accountcaode'),array('3600'),array('accountcode','accountname','group_'),array('3600','','EGENKAPITAL'));
InsertRecord('chartmaster',array('accountcaode'),array('4020'),array('accountcode','accountname','group_'),array('4020','Salg / udstyr','SALGSINDT'));
InsertRecord('chartmaster',array('accountcaode'),array('4030'),array('accountcode','accountname','group_'),array('4030','Salg / programmel','SALGSINDT'));
InsertRecord('chartmaster',array('accountcaode'),array('4040'),array('accountcode','accountname','group_'),array('4040','Salg / till','SALGSINDT'));
InsertRecord('chartmaster',array('accountcaode'),array('4050'),array('accountcode','accountname','group_'),array('4050','Salg / arrangementer','SALGSINDT'));
InsertRecord('chartmaster',array('accountcaode'),array('4320'),array('accountcode','accountname','group_'),array('4320','Konsulentbistand','KONSULENTINDT'));
InsertRecord('chartmaster',array('accountcaode'),array('4330'),array('accountcode','accountname','group_'),array('4330','Programmering','KONSULENTINDT'));
InsertRecord('chartmaster',array('accountcaode'),array('4440'),array('accountcode','accountname','group_'),array('4440','Renter','ANDEN INDT'));
InsertRecord('chartmaster',array('accountcaode'),array('4450'),array('accountcode','accountname','group_'),array('4450','Foreign Exchange Gain','ANDEN INDT'));
InsertRecord('chartmaster',array('accountcaode'),array('5010'),array('accountcode','accountname','group_'),array('5010','Anskaffelser under 8.000','SALGSOMKOSTNINGER'));
InsertRecord('chartmaster',array('accountcaode'),array('5011'),array('accountcode','accountname','group_'),array('5011','Anskaffelser over 8.000','SALGSOMKOSTNINGER'));
InsertRecord('chartmaster',array('accountcaode'),array('5020'),array('accountcode','accountname','group_'),array('5020','Omkostninger / udstyr','SALGSOMKOSTNINGER'));
InsertRecord('chartmaster',array('accountcaode'),array('5030'),array('accountcode','accountname','group_'),array('5030','Omkostninger / programmel','SALGSOMKOSTNINGER'));
InsertRecord('chartmaster',array('accountcaode'),array('5040'),array('accountcode','accountname','group_'),array('5040','Omkostninger / till','SALGSOMKOSTNINGER'));
InsertRecord('chartmaster',array('accountcaode'),array('5050'),array('accountcode','accountname','group_'),array('5050','Omkostninger / arrangementer','SALGSOMKOSTNINGER'));
InsertRecord('chartmaster',array('accountcaode'),array('5100'),array('accountcode','accountname','group_'),array('5100','Fragt, post','SALGSOMKOSTNINGER'));
InsertRecord('chartmaster',array('accountcaode'),array('5410'),array('accountcode','accountname','group_'),array('5410','L','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5420'),array('accountcode','accountname','group_'),array('5420','ATP','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5470'),array('accountcode','accountname','group_'),array('5470','Personalegoder','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5610'),array('accountcode','accountname','group_'),array('5610','Bogf','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5615'),array('accountcode','accountname','group_'),array('5615','Marketing','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5620'),array('accountcode','accountname','group_'),array('5620','D','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5660'),array('accountcode','accountname','group_'),array('5660','Afdrag p','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5680'),array('accountcode','accountname','group_'),array('5680','A-skat','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5685'),array('accountcode','accountname','group_'),array('5685','Forsikringer','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5690'),array('accountcode','accountname','group_'),array('5690','Renter og bankgebyrer','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5700'),array('accountcode','accountname','group_'),array('5700','Kontorudgifter','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5760'),array('accountcode','accountname','group_'),array('5760','Husleje','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5765'),array('accountcode','accountname','group_'),array('5765','Vedligeholdelse og reparation','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5780'),array('accountcode','accountname','group_'),array('5780','Telefon','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5785'),array('accountcode','accountname','group_'),array('5785','Rejser & repr','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5790'),array('accountcode','accountname','group_'),array('5790','El, vand, varme','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5800'),array('accountcode','accountname','group_'),array('5800','Licenser','GENERELLE & ADMINISTRATIVE UDG'));
InsertRecord('chartmaster',array('accountcaode'),array('5810'),array('accountcode','accountname','group_'),array('5810','Foreign Exchange Loss','GENERELLE & ADMINISTRATIVE UDG'));
?>