<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiver'), $db);
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiver'), $db);
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Indt'), $db);
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Omkostninger'), $db);
InsertRecord('accountgroups',array('groupname'),array('Aktiver'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Aktiver','10','0','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Andre omk'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Andre omk','40','1','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Finansielle omk'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Finansielle omk','40','1','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Fri'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Fri','40','1','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Kontoromk'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kontoromk','40','1','30000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('L'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('L','40','1','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Passiver'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Passiver','20','0','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Salg'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Salg','30','1','10000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Varek'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Varek','40','1','20000',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1100'),array('accountcode','accountname','group_'),array('1100','Varesalg','Salg'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1110'),array('accountcode','accountname','group_'),array('1110','Varesalg 2','Salg'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1120'),array('accountcode','accountname','group_'),array('1120','Salg EU','Salg'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1200'),array('accountcode','accountname','group_'),array('1200','Udf','Salg'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1210'),array('accountcode','accountname','group_'),array('1210','Andre indt','Salg'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1790'),array('accountcode','accountname','group_'),array('1790','Reg. igangv','Salg'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1810'),array('accountcode','accountname','group_'),array('1810','Debitorrabatter','Salg'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2100'),array('accountcode','accountname','group_'),array('2100','Varek','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2110'),array('accountcode','accountname','group_'),array('2110','Varek','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2150'),array('accountcode','accountname','group_'),array('2150','Varek','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2200'),array('accountcode','accountname','group_'),array('2200','Fremmed assistance','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2400'),array('accountcode','accountname','group_'),array('2400','K','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2790'),array('accountcode','accountname','group_'),array('2790','Regulering af varelager','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2810'),array('accountcode','accountname','group_'),array('2810','Kreditorrabatter','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2820'),array('accountcode','accountname','group_'),array('2820','Kursreguleringer','Varek'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3100'),array('accountcode','accountname','group_'),array('3100','Annoncer og reklame','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3110'),array('accountcode','accountname','group_'),array('3110','Rejseudgifter','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3120'),array('accountcode','accountname','group_'),array('3120','Blomster og gaver m.v.','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3130'),array('accountcode','accountname','group_'),array('3130','Repr','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3140'),array('accountcode','accountname','group_'),array('3140','Repr','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3210'),array('accountcode','accountname','group_'),array('3210','Husleje og varme m/moms','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3220'),array('accountcode','accountname','group_'),array('3220','Elforbrug','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3240'),array('accountcode','accountname','group_'),array('3240','Reng','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3250'),array('accountcode','accountname','group_'),array('3250','Vedligeholdelse lokaler','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3310'),array('accountcode','accountname','group_'),array('3310','Telefon og mobiltelefon','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3315'),array('accountcode','accountname','group_'),array('3315','Fragt','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3320'),array('accountcode','accountname','group_'),array('3320','Portoudgifter','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3330'),array('accountcode','accountname','group_'),array('3330','Kontorartikler','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3340'),array('accountcode','accountname','group_'),array('3340','Fagliteratur','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3345'),array('accountcode','accountname','group_'),array('3345','Aviser og tidsskrifter','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3350'),array('accountcode','accountname','group_'),array('3350','Sm','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3360'),array('accountcode','accountname','group_'),array('3360','Vedligeholdelse inventar','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3370'),array('accountcode','accountname','group_'),array('3370','EDB-udgifter m.v.','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3380'),array('accountcode','accountname','group_'),array('3380','Regnskabsm','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3385'),array('accountcode','accountname','group_'),array('3385','Anden ekstern assistance','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3390'),array('accountcode','accountname','group_'),array('3390','Advokatudgifter','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3410'),array('accountcode','accountname','group_'),array('3410','Kontigenter m/moms','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3420'),array('accountcode','accountname','group_'),array('3420','Forsikringer','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3430'),array('accountcode','accountname','group_'),array('3430','Gebyr m/moms','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3435'),array('accountcode','accountname','group_'),array('3435','Gebyr u/moms','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3440'),array('accountcode','accountname','group_'),array('3440','P-afgifter','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3450'),array('accountcode','accountname','group_'),array('3450','Taxa','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3610'),array('accountcode','accountname','group_'),array('3610','Autodrift m/moms','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3620'),array('accountcode','accountname','group_'),array('3620','V','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3630'),array('accountcode','accountname','group_'),array('3630','Service og reparationer','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3640'),array('accountcode','accountname','group_'),array('3640','K','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3710'),array('accountcode','accountname','group_'),array('3710','Tab p','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3740'),array('accountcode','accountname','group_'),array('3740','Tab/Vind','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3800'),array('accountcode','accountname','group_'),array('3800','Ikke fradragsberet. udgifter','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3900'),array('accountcode','accountname','group_'),array('3900','Diverse','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3905'),array('accountcode','accountname','group_'),array('3905','Fejlkonto','Kontoromk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4110'),array('accountcode','accountname','group_'),array('4110','Udbetalte l','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4140'),array('accountcode','accountname','group_'),array('4140','K','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4150'),array('accountcode','accountname','group_'),array('4150','AM-bidrag m.v.','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4160'),array('accountcode','accountname','group_'),array('4160','Arb. giverbidrag','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4180'),array('accountcode','accountname','group_'),array('4180','Pensioner m.v.','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4210'),array('accountcode','accountname','group_'),array('4210','Feriepenge','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4250'),array('accountcode','accountname','group_'),array('4250','Reg. af feriepengetilsvar','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4310'),array('accountcode','accountname','group_'),array('4310','ATP-bidrag','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4320'),array('accountcode','accountname','group_'),array('4320','Andre sociale bidrag','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4330'),array('accountcode','accountname','group_'),array('4330','L','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4410'),array('accountcode','accountname','group_'),array('4410','Personaleforsikringer','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4420'),array('accountcode','accountname','group_'),array('4420','Skole og kurser','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4510'),array('accountcode','accountname','group_'),array('4510','Modtaget l','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4600'),array('accountcode','accountname','group_'),array('4600','Personaleudgifter','L'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5110'),array('accountcode','accountname','group_'),array('5110','Afskr. good-will','Andre omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5120'),array('accountcode','accountname','group_'),array('5120','Afskr. lokaleindretning','Andre omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5210'),array('accountcode','accountname','group_'),array('5210','Afskr. inventar','Andre omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5220'),array('accountcode','accountname','group_'),array('5220','Afskr. driftsmidler','Andre omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5230'),array('accountcode','accountname','group_'),array('5230','Afskr. grunde og bygninger','Andre omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5250'),array('accountcode','accountname','group_'),array('5250','Afskr. tekniske anl','Andre omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5500'),array('accountcode','accountname','group_'),array('5500','Nedskr. oms','Andre omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6020'),array('accountcode','accountname','group_'),array('6020','Indt. kapitaland. tilknyt. vir','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6030'),array('accountcode','accountname','group_'),array('6030','Indt. kapitaland. associerede','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6050'),array('accountcode','accountname','group_'),array('6050','Indt. andre kapitaland. v','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6110'),array('accountcode','accountname','group_'),array('6110','Renteindt','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6130'),array('accountcode','accountname','group_'),array('6130','Renteindt','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6140'),array('accountcode','accountname','group_'),array('6140','Renteindt','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6211'),array('accountcode','accountname','group_'),array('6211','Renteudgift, banker','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6230'),array('accountcode','accountname','group_'),array('6230','Renteudgift, kreditorer','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6240'),array('accountcode','accountname','group_'),array('6240','Renteudgift, l','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6250'),array('accountcode','accountname','group_'),array('6250','Renteudgift, i','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6280'),array('accountcode','accountname','group_'),array('6280','Renteudgift, offentlige','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6410'),array('accountcode','accountname','group_'),array('6410','Ekstraordin','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6420'),array('accountcode','accountname','group_'),array('6420','Indt','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6550'),array('accountcode','accountname','group_'),array('6550','Ekstraordin','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6560'),array('accountcode','accountname','group_'),array('6560','Udgifter vedr. tidl.','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6610'),array('accountcode','accountname','group_'),array('6610','Skat af','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6620'),array('accountcode','accountname','group_'),array('6620','Regulering af udskudt skat','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6630'),array('accountcode','accountname','group_'),array('6630','Skatter vedr. tidl.','Finansielle omk'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7120'),array('accountcode','accountname','group_'),array('7120','Goodwill Saldo primo','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7130'),array('accountcode','accountname','group_'),array('7130','Goodwill Tilgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7135'),array('accountcode','accountname','group_'),array('7135','Goodwill Afgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7150'),array('accountcode','accountname','group_'),array('7150','Afskrivninger','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7151'),array('accountcode','accountname','group_'),array('7151','Akkumulerede afskrivninger, pr','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7185'),array('accountcode','accountname','group_'),array('7185','Deposita, forudbetalt husleje','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7220'),array('accountcode','accountname','group_'),array('7220','Forudb. Saldo primo','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7230'),array('accountcode','accountname','group_'),array('7230','Forudb. Tilgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7235'),array('accountcode','accountname','group_'),array('7235','Forudb. Afgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7250'),array('accountcode','accountname','group_'),array('7250','','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7251'),array('accountcode','accountname','group_'),array('7251','Akkumulerede afskrivninger, pr','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7310'),array('accountcode','accountname','group_'),array('7310','Bygn. Saldo primo','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7320'),array('accountcode','accountname','group_'),array('7320','Bygn. Tilgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7330'),array('accountcode','accountname','group_'),array('7330','Bygn. Afgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7340'),array('accountcode','accountname','group_'),array('7340','Opskrivninger','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7350'),array('accountcode','accountname','group_'),array('7350','','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7351'),array('accountcode','accountname','group_'),array('7351','Akkumulerede afskrivninger, pr','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7410'),array('accountcode','accountname','group_'),array('7410','Maskiner Saldo primo','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7420'),array('accountcode','accountname','group_'),array('7420','Maskiner Tilgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7430'),array('accountcode','accountname','group_'),array('7430','Maskiner Afgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7440'),array('accountcode','accountname','group_'),array('7440','Opskrivninger','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7450'),array('accountcode','accountname','group_'),array('7450','','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7451'),array('accountcode','accountname','group_'),array('7451','Akkumulerede afskrivninger, pr','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7510'),array('accountcode','accountname','group_'),array('7510','Inventar Saldo primo','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7520'),array('accountcode','accountname','group_'),array('7520','Inventar Tilgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7530'),array('accountcode','accountname','group_'),array('7530','Inventar Afgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7540'),array('accountcode','accountname','group_'),array('7540','Inventar Opskrivninger','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7550'),array('accountcode','accountname','group_'),array('7550','','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7551'),array('accountcode','accountname','group_'),array('7551','Akkumulerede afskrivninger, pr','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7572'),array('accountcode','accountname','group_'),array('7572','Driftsm. Saldo primo','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7577'),array('accountcode','accountname','group_'),array('7577','Driftsm. Tilgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7578'),array('accountcode','accountname','group_'),array('7578','Driftsm. Afgang','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7580'),array('accountcode','accountname','group_'),array('7580','Driftsm. Opskrivninger','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7586'),array('accountcode','accountname','group_'),array('7586','','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7590'),array('accountcode','accountname','group_'),array('7590','Akkumulerede afskrivninger, pr','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7597'),array('accountcode','accountname','group_'),array('7597','Forudbet. for mat. anl','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7610'),array('accountcode','accountname','group_'),array('7610','Kapitalandele i tilknyt. virks','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7620'),array('accountcode','accountname','group_'),array('7620','Tilgodehav. hos tilknyt. virks','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7630'),array('accountcode','accountname','group_'),array('7630','Kapitalandele i associerede vi','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7640'),array('accountcode','accountname','group_'),array('7640','Tilgodehav. hos associerede vi','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7650'),array('accountcode','accountname','group_'),array('7650','Andre v','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7660'),array('accountcode','accountname','group_'),array('7660','Andre tilgodehaverner','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7680'),array('accountcode','accountname','group_'),array('7680','Egne aktier eller anparter','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7690'),array('accountcode','accountname','group_'),array('7690','Tilgodeh. hos virsomhedsdelta','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7710'),array('accountcode','accountname','group_'),array('7710','Varelager','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7750'),array('accountcode','accountname','group_'),array('7750','Igangv','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7810'),array('accountcode','accountname','group_'),array('7810','Debitorsamlekonto','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7820'),array('accountcode','accountname','group_'),array('7820','Andre tilgodehavender','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7840'),array('accountcode','accountname','group_'),array('7840','Periodeafgr','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7860'),array('accountcode','accountname','group_'),array('7860','Kapitalandele i tilknyt. virks','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7870'),array('accountcode','accountname','group_'),array('7870','Egne aktier eller anparter','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7880'),array('accountcode','accountname','group_'),array('7880','Andre v','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7910'),array('accountcode','accountname','group_'),array('7910','Kassebeholdning','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7920'),array('accountcode','accountname','group_'),array('7920','Pengeinstitut','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7930'),array('accountcode','accountname','group_'),array('7930','Girokonto','Aktiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8110'),array('accountcode','accountname','group_'),array('8110','Selskabskapital','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8120'),array('accountcode','accountname','group_'),array('8120','Overkurs ved emission','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8130'),array('accountcode','accountname','group_'),array('8130','Opskrivningshenl','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8140'),array('accountcode','accountname','group_'),array('8140','Reserver for nettoopskrivning','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8141'),array('accountcode','accountname','group_'),array('8141','Reserve for egne aktier eller','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8142'),array('accountcode','accountname','group_'),array('8142','','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8144'),array('accountcode','accountname','group_'),array('8144','Vedt','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8190'),array('accountcode','accountname','group_'),array('8190','Overf','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8195'),array('accountcode','accountname','group_'),array('8195','Overf','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8200'),array('accountcode','accountname','group_'),array('8200','Privat indskud','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8210'),array('accountcode','accountname','group_'),array('8210','Private h','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8610'),array('accountcode','accountname','group_'),array('8610','Udskudt skat','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8650'),array('accountcode','accountname','group_'),array('8650','Debitorreservationer','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8670'),array('accountcode','accountname','group_'),array('8670','Andre hens','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9005'),array('accountcode','accountname','group_'),array('9005','Langfr. Obligationsl','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9120'),array('accountcode','accountname','group_'),array('9120','Konvertibel g','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9130'),array('accountcode','accountname','group_'),array('9130','Udbyttegivende g','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9140'),array('accountcode','accountname','group_'),array('9140','Kreditinstitutter','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9160'),array('accountcode','accountname','group_'),array('9160','Leverand','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9170'),array('accountcode','accountname','group_'),array('9170','Vekselg','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9180'),array('accountcode','accountname','group_'),array('9180','G','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9190'),array('accountcode','accountname','group_'),array('9190','G','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9200'),array('accountcode','accountname','group_'),array('9200','Selskabsskat','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9301'),array('accountcode','accountname','group_'),array('9301','Kortfr. Obligationsl','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9320'),array('accountcode','accountname','group_'),array('9320','Konvertible g','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9330'),array('accountcode','accountname','group_'),array('9330','Udbyttegivende g','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9340'),array('accountcode','accountname','group_'),array('9340','Kreditinstitutter','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9350'),array('accountcode','accountname','group_'),array('9350','Modtagne forudbetalinger fra kr','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9360'),array('accountcode','accountname','group_'),array('9360','Kreditorsamlekonto','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9370'),array('accountcode','accountname','group_'),array('9370','Vekselg','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9380'),array('accountcode','accountname','group_'),array('9380','G','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9390'),array('accountcode','accountname','group_'),array('9390','G','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9395'),array('accountcode','accountname','group_'),array('9395','Skyldig selskabsskat','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9401'),array('accountcode','accountname','group_'),array('9401','Toldv','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9410'),array('accountcode','accountname','group_'),array('9410','Udg','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9415'),array('accountcode','accountname','group_'),array('9415','Importmoms','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9420'),array('accountcode','accountname','group_'),array('9420','Indg','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9430'),array('accountcode','accountname','group_'),array('9430','Elafgift','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9440'),array('accountcode','accountname','group_'),array('9440','CO2-aftift','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9470'),array('accountcode','accountname','group_'),array('9470','Anden aftift','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9480'),array('accountcode','accountname','group_'),array('9480','Skyldig moms','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9520'),array('accountcode','accountname','group_'),array('9520','Tilbagehold A-skat','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9525'),array('accountcode','accountname','group_'),array('9525','Betalt A-skat','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9530'),array('accountcode','accountname','group_'),array('9530','Tilbageholdt AM-bidrag','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9535'),array('accountcode','accountname','group_'),array('9535','Betalt AM-bidrag','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9540'),array('accountcode','accountname','group_'),array('9540','Skyldig ATP-bidrag','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9545'),array('accountcode','accountname','group_'),array('9545','Skyldig arb.giverbidrag','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9560'),array('accountcode','accountname','group_'),array('9560','Skyldige feriepenge','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9570'),array('accountcode','accountname','group_'),array('9570','Feriepengetilsvar','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9590'),array('accountcode','accountname','group_'),array('9590','Mellemregn. selskabsdeltagere','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9800'),array('accountcode','accountname','group_'),array('9800','Skyldige omkostninger','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9900'),array('accountcode','accountname','group_'),array('9900','Udbytte for regnskabs','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9920'),array('accountcode','accountname','group_'),array('9920','Ikke h','Passiver'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9930'),array('accountcode','accountname','group_'),array('9930','Skyldig udbytteskat','Passiver'), $db);
?>