<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiven'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiven'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Erfolg'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Aufwand'));
InsertRecord('accountgroups',array('groupname'),array('ABSCHREIBUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ABSCHREIBUNGEN','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('AUFWENDUNGEN F'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('AUFWENDUNGEN F','10','0','1000',''));
InsertRecord('accountgroups',array('groupname'),array('BETEILIGUNGSERTR'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('BETEILIGUNGSERTR','30','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('BETRIEBS- UND GESCH'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('BETRIEBS- UND GESCH','10','0','6000',''));
InsertRecord('accountgroups',array('groupname'),array('BEZOGENE TEILE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('BEZOGENE TEILE','10','0','10000',''));
InsertRecord('accountgroups',array('groupname'),array('EB,SB,G+V KONTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('EB,SB,G+V KONTEN','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('EINLAGEN STILLER GESELLSCHAFTE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('EINLAGEN STILLER GESELLSCHAFTE','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('FAHRZEUGE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FAHRZEUGE','10','0','5000',''));
InsertRecord('accountgroups',array('groupname'),array('FERTIGE ERZEUGNISSE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FERTIGE ERZEUGNISSE','10','0','13000',''));
InsertRecord('accountgroups',array('groupname'),array('FINANZANLAGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FINANZANLAGEN','10','0','8000',''));
InsertRecord('accountgroups',array('groupname'),array('FINANZERTR'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FINANZERTR','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('FORDERUNGEN AUS ABGABENVERRECH'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FORDERUNGEN AUS ABGABENVERRECH','10','0','20000',''));
InsertRecord('accountgroups',array('groupname'),array('FORDEUNGEN AUS LIEFERUNGEN UND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FORDEUNGEN AUS LIEFERUNGEN UND','10','0','18000',''));
InsertRecord('accountgroups',array('groupname'),array('FREIWILLIGER SOZIALAUFWAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FREIWILLIGER SOZIALAUFWAND','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('GEAHLTSAUFWAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GEAHLTSAUFWAND','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('GELEISTETE ANZAHLUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GELEISTETE ANZAHLUNGEN','10','0','7000',''));
InsertRecord('accountgroups',array('groupname'),array('GELEISTETE ANZAHLUNGEN 2'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GELEISTETE ANZAHLUNGEN 2','10','0','16000',''));
InsertRecord('accountgroups',array('groupname'),array('GESETZLICHER SOZIALAUFWAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GESETZLICHER SOZIALAUFWAND','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('GEWINN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GEWINN','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('GRUNDST'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GRUNDST','10','0','3000',''));
InsertRecord('accountgroups',array('groupname'),array('HILFS- UND BETRIEBSSTOFFE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('HILFS- UND BETRIEBSSTOFFE','10','0','11000',''));
InsertRecord('accountgroups',array('groupname'),array('IMMATERIELLE VERM'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('IMMATERIELLE VERM','10','0','2000',''));
InsertRecord('accountgroups',array('groupname'),array('INSTANDHALTUNGSAUFWAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('INSTANDHALTUNGSAUFWAND','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('KAPITAL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('KAPITAL','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('KAPITALR'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('KAPITALR','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('KASSABESTAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('KASSABESTAND','10','0','22000',''));
InsertRecord('accountgroups',array('groupname'),array('LANGFRISTIGE VERBINDLICHKEITEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('LANGFRISTIGE VERBINDLICHKEITEN','20','0','24000',''));
InsertRecord('accountgroups',array('groupname'),array('LOHNAUFWAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('LOHNAUFWAND','40','1','32000',''));
InsertRecord('accountgroups',array('groupname'),array('MASCHINEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('MASCHINEN','10','0','4000',''));
InsertRecord('accountgroups',array('groupname'),array('MIET-,PACHT-,LEASING-, LIZENZA'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('MIET-,PACHT-,LEASING-, LIZENZA','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('NOCH NICHT ABGERECHNETE LEISTU'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('NOCH NICHT ABGERECHNETE LEISTU','10','0','15000',''));
InsertRecord('accountgroups',array('groupname'),array('R'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('R','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('ROHSTOFFE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ROHSTOFFE','10','0','9000',''));
InsertRecord('accountgroups',array('groupname'),array('SCHECKS, GUTHABEN BEI KREDITIN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('SCHECKS, GUTHABEN BEI KREDITIN','10','0','23000',''));
InsertRecord('accountgroups',array('groupname'),array('SONSTIGE ERL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('SONSTIGE ERL','30','1','29000',''));
InsertRecord('accountgroups',array('groupname'),array('SONSTIGE FORDERUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('SONSTIGE FORDERUNGEN','10','0','19000',''));
InsertRecord('accountgroups',array('groupname'),array('SONSTIGE STEUERN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('SONSTIGE STEUERN','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('TRANSPORTKOSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('TRANSPORTKOSTEN','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('UMSATZ'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('UMSATZ','30','1','27000',''));
InsertRecord('accountgroups',array('groupname'),array('UMSATZ BERATUNG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('UMSATZ BERATUNG','30','1','28000',''));
InsertRecord('accountgroups',array('groupname'),array('UNFERTIGE ERZEUGNISSE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('UNFERTIGE ERZEUGNISSE','10','0','12000',''));
InsertRecord('accountgroups',array('groupname'),array('VERBINDLICHKEITEN AUS LIEFERUN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('VERBINDLICHKEITEN AUS LIEFERUN','20','0','25000',''));
InsertRecord('accountgroups',array('groupname'),array('VERBINDLICHKEITEN FINANZAMT'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('VERBINDLICHKEITEN FINANZAMT','20','0','26000',''));
InsertRecord('accountgroups',array('groupname'),array('VERBRAUCH BRENN- UND TREIBSTOF'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('VERBRAUCH BRENN- UND TREIBSTOF','30','1','31000',''));
InsertRecord('accountgroups',array('groupname'),array('VERSICHERUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('VERSICHERUNGEN','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('VERWALTUNGSKOSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('VERWALTUNGSKOSTEN','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('WAREN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('WAREN','10','0','14000',''));
InsertRecord('accountgroups',array('groupname'),array('WARENEINSATZ'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('WARENEINSATZ','40','1','30000',''));
InsertRecord('accountgroups',array('groupname'),array('WERTBERICHTIGUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('WERTBERICHTIGUNGEN','10','0','17000',''));
InsertRecord('accountgroups',array('groupname'),array('WERTPAPIERE UND ANTEILE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('WERTPAPIERE UND ANTEILE','10','0','21000',''));
InsertRecord('chartmaster',array('accountcaode'),array('0010'),array('accountcode','accountname','group_'),array('0010','Firmenwert','AUFWENDUNGEN F'));
InsertRecord('chartmaster',array('accountcaode'),array('0110'),array('accountcode','accountname','group_'),array('0110','Rechte','IMMATERIELLE VERM'));
InsertRecord('chartmaster',array('accountcaode'),array('0210'),array('accountcode','accountname','group_'),array('0210','unbebaute Grundst','GRUNDST'));
InsertRecord('chartmaster',array('accountcaode'),array('0220'),array('accountcode','accountname','group_'),array('0220','bebaute Grundst','GRUNDST'));
InsertRecord('chartmaster',array('accountcaode'),array('0229'),array('accountcode','accountname','group_'),array('0229','kum. Abschreibung bebaute Grundst','GRUNDST'));
InsertRecord('chartmaster',array('accountcaode'),array('0410'),array('accountcode','accountname','group_'),array('0410','Maschinen','MASCHINEN'));
InsertRecord('chartmaster',array('accountcaode'),array('0419'),array('accountcode','accountname','group_'),array('0419','kum. Abschreibung Maschinen','MASCHINEN'));
InsertRecord('chartmaster',array('accountcaode'),array('0510'),array('accountcode','accountname','group_'),array('0510','Fahrzeuge','FAHRZEUGE'));
InsertRecord('chartmaster',array('accountcaode'),array('0519'),array('accountcode','accountname','group_'),array('0519','kum. Abschreibung Fahrzeuge','FAHRZEUGE'));
InsertRecord('chartmaster',array('accountcaode'),array('0620'),array('accountcode','accountname','group_'),array('0620','B','BETRIEBS- UND GESCH'));
InsertRecord('chartmaster',array('accountcaode'),array('0625'),array('accountcode','accountname','group_'),array('0625','kum. Abschreibung Betriebs- und Gesch','BETRIEBS- UND GESCH'));
InsertRecord('chartmaster',array('accountcaode'),array('0810'),array('accountcode','accountname','group_'),array('0810','Beteiligungen','FINANZANLAGEN'));
InsertRecord('chartmaster',array('accountcaode'),array('0820'),array('accountcode','accountname','group_'),array('0820','Wertpapiere','FINANZANLAGEN'));
InsertRecord('chartmaster',array('accountcaode'),array('1120'),array('accountcode','accountname','group_'),array('1120','Vorr','ROHSTOFFE'));
InsertRecord('chartmaster',array('accountcaode'),array('1220'),array('accountcode','accountname','group_'),array('1220','Vorr','BEZOGENE TEILE'));
InsertRecord('chartmaster',array('accountcaode'),array('1320'),array('accountcode','accountname','group_'),array('1320','Hilfsstoffe','HILFS- UND BETRIEBSSTOFFE'));
InsertRecord('chartmaster',array('accountcaode'),array('1350'),array('accountcode','accountname','group_'),array('1350','Betriebssstoffe','HILFS- UND BETRIEBSSTOFFE'));
InsertRecord('chartmaster',array('accountcaode'),array('1420'),array('accountcode','accountname','group_'),array('1420','Vorr','UNFERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcaode'),array('1520'),array('accountcode','accountname','group_'),array('1520','Vorr','FERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcaode'),array('1530'),array('accountcode','accountname','group_'),array('1530','Vorr','FERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcaode'),array('1540'),array('accountcode','accountname','group_'),array('1540','Vorr','FERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcaode'),array('2010'),array('accountcode','accountname','group_'),array('2010','Forderungen Lieferung & Leistung','FORDEUNGEN AUS LIEFERUNGEN UND'));
InsertRecord('chartmaster',array('accountcaode'),array('2019'),array('accountcode','accountname','group_'),array('2019','Wertberichtigung uneinbringliche Forderungen','FORDEUNGEN AUS LIEFERUNGEN UND'));
InsertRecord('chartmaster',array('accountcaode'),array('2320'),array('accountcode','accountname','group_'),array('2320','sonstige Forderungen','SONSTIGE FORDERUNGEN'));
InsertRecord('chartmaster',array('accountcaode'),array('2520'),array('accountcode','accountname','group_'),array('2520','sonstige Forderungen aus Abgebenverrechnung','FORDERUNGEN AUS ABGABENVERRECH'));
InsertRecord('chartmaster',array('accountcaode'),array('2620'),array('accountcode','accountname','group_'),array('2620','Wertpapiere Umlaufverm','WERTPAPIERE UND ANTEILE'));
InsertRecord('chartmaster',array('accountcaode'),array('2701'),array('accountcode','accountname','group_'),array('2701','Kassa','KASSABESTAND'));
InsertRecord('chartmaster',array('accountcaode'),array('2810'),array('accountcode','accountname','group_'),array('2810','Schecks','SCHECKS, GUTHABEN BEI KREDITIN'));
InsertRecord('chartmaster',array('accountcaode'),array('2820'),array('accountcode','accountname','group_'),array('2820','Bankguthaben','SCHECKS, GUTHABEN BEI KREDITIN'));
InsertRecord('chartmaster',array('accountcaode'),array('3110'),array('accountcode','accountname','group_'),array('3110','Bank Verbindlichkeiten','LANGFRISTIGE VERBINDLICHKEITEN'));
InsertRecord('chartmaster',array('accountcaode'),array('3120'),array('accountcode','accountname','group_'),array('3120','Kredite von Eigent','LANGFRISTIGE VERBINDLICHKEITEN'));
InsertRecord('chartmaster',array('accountcaode'),array('3310'),array('accountcode','accountname','group_'),array('3310','Verbindlichkeiten aus Lieferungen und Leistungen','VERBINDLICHKEITEN AUS LIEFERUN'));
InsertRecord('chartmaster',array('accountcaode'),array('3510'),array('accountcode','accountname','group_'),array('3510','Finanzamt Verrechnung K','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('3520'),array('accountcode','accountname','group_'),array('3520','Finanzamt Verrechnung Umsatzsteuer','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('3530'),array('accountcode','accountname','group_'),array('3530','Umsatzsteuer 0%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('3531'),array('accountcode','accountname','group_'),array('3531','Umsatzsteuer 10%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('3532'),array('accountcode','accountname','group_'),array('3532','Umsatzsteuer 20%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('3540'),array('accountcode','accountname','group_'),array('3540','Vorsteuer 0%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('3541'),array('accountcode','accountname','group_'),array('3541','Vorsteuer 10%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('3542'),array('accountcode','accountname','group_'),array('3542','Vorsteuer 20%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcaode'),array('4020'),array('accountcode','accountname','group_'),array('4020','Verkauf - Hardware','UMSATZ'));
InsertRecord('chartmaster',array('accountcaode'),array('4030'),array('accountcode','accountname','group_'),array('4030','Verkauf - Software','UMSATZ'));
InsertRecord('chartmaster',array('accountcaode'),array('4040'),array('accountcode','accountname','group_'),array('4040','Verkauf - Ersatzteile','UMSATZ'));
InsertRecord('chartmaster',array('accountcaode'),array('4320'),array('accountcode','accountname','group_'),array('4320','Erl','UMSATZ BERATUNG'));
InsertRecord('chartmaster',array('accountcaode'),array('4330'),array('accountcode','accountname','group_'),array('4330','Erl','UMSATZ BERATUNG'));
InsertRecord('chartmaster',array('accountcaode'),array('4630'),array('accountcode','accountname','group_'),array('4630','Frachterl','SONSTIGE ERL'));
InsertRecord('chartmaster',array('accountcaode'),array('4640'),array('accountcode','accountname','group_'),array('4640','Devisengewinne','SONSTIGE ERL'));
InsertRecord('chartmaster',array('accountcaode'),array('5020'),array('accountcode','accountname','group_'),array('5020','Wareneinsatz / Hardware','WARENEINSATZ'));
InsertRecord('chartmaster',array('accountcaode'),array('5030'),array('accountcode','accountname','group_'),array('5030','Wareneinsatz / Software','WARENEINSATZ'));
InsertRecord('chartmaster',array('accountcaode'),array('5040'),array('accountcode','accountname','group_'),array('5040','Wareneinsatz / Ersatzteile','WARENEINSATZ'));
InsertRecord('chartmaster',array('accountcaode'),array('5610'),array('accountcode','accountname','group_'),array('5610','Energie, Wasser','VERBRAUCH BRENN- UND TREIBSTOF'));
InsertRecord('chartmaster',array('accountcaode'),array('6010'),array('accountcode','accountname','group_'),array('6010','Lohn','LOHNAUFWAND'));
InsertRecord('chartmaster',array('accountcaode'),array('6210'),array('accountcode','accountname','group_'),array('6210','Gehalt','GEAHLTSAUFWAND'));
InsertRecord('chartmaster',array('accountcaode'),array('6510'),array('accountcode','accountname','group_'),array('6510','Dienstgeberanteile','GESETZLICHER SOZIALAUFWAND'));
InsertRecord('chartmaster',array('accountcaode'),array('6710'),array('accountcode','accountname','group_'),array('6710','freiwilliger Sozialaufwand','FREIWILLIGER SOZIALAUFWAND'));
InsertRecord('chartmaster',array('accountcaode'),array('7010'),array('accountcode','accountname','group_'),array('7010','Abschreibungen','ABSCHREIBUNGEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7020'),array('accountcode','accountname','group_'),array('7020','geringwertige Wirtschaftsg','ABSCHREIBUNGEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7110'),array('accountcode','accountname','group_'),array('7110','Ertragssteuern','SONSTIGE STEUERN'));
InsertRecord('chartmaster',array('accountcaode'),array('7120'),array('accountcode','accountname','group_'),array('7120','Grundsteuern','SONSTIGE STEUERN'));
InsertRecord('chartmaster',array('accountcaode'),array('7210'),array('accountcode','accountname','group_'),array('7210','Reparatur und Instandhaltung','INSTANDHALTUNGSAUFWAND'));
InsertRecord('chartmaster',array('accountcaode'),array('7310'),array('accountcode','accountname','group_'),array('7310','Frachtaufwand','TRANSPORTKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7410'),array('accountcode','accountname','group_'),array('7410','Miete','MIET-,PACHT-,LEASING-, LIZENZA'));
InsertRecord('chartmaster',array('accountcaode'),array('7411'),array('accountcode','accountname','group_'),array('7411','Lizenzen','MIET-,PACHT-,LEASING-, LIZENZA'));
InsertRecord('chartmaster',array('accountcaode'),array('7610'),array('accountcode','accountname','group_'),array('7610','Beratungsaufwand','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7611'),array('accountcode','accountname','group_'),array('7611','B','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7615'),array('accountcode','accountname','group_'),array('7615','Werbung und Marketing','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7620'),array('accountcode','accountname','group_'),array('7620','uneinbringliche Forderungen','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7630'),array('accountcode','accountname','group_'),array('7630','Telephonkosten','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7631'),array('accountcode','accountname','group_'),array('7631','Internetkosten','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7632'),array('accountcode','accountname','group_'),array('7632','Reise- und Repr','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7634'),array('accountcode','accountname','group_'),array('7634','Registrierungsgeb','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('7710'),array('accountcode','accountname','group_'),array('7710','Versicherung','VERSICHERUNGEN'));
InsertRecord('chartmaster',array('accountcaode'),array('8020'),array('accountcode','accountname','group_'),array('8020','Bankzinsen und Geb','FINANZERTR'));
InsertRecord('chartmaster',array('accountcaode'),array('8050'),array('accountcode','accountname','group_'),array('8050','Devisenverluste','FINANZERTR'));
InsertRecord('chartmaster',array('accountcaode'),array('8110'),array('accountcode','accountname','group_'),array('8110','Ertr','BETEILIGUNGSERTR'));
InsertRecord('chartmaster',array('accountcaode'),array('9010'),array('accountcode','accountname','group_'),array('9010','Aktien, Gesch','KAPITAL'));
InsertRecord('chartmaster',array('accountcaode'),array('9020'),array('accountcode','accountname','group_'),array('9020','nicht einbezahltes Kapital','KAPITAL'));
InsertRecord('chartmaster',array('accountcaode'),array('9210'),array('accountcode','accountname','group_'),array('9210','freie R','KAPITALR'));
InsertRecord('chartmaster',array('accountcaode'),array('9310'),array('accountcode','accountname','group_'),array('9310','Gewinnvortrag Vorjahr','GEWINN'));
InsertRecord('chartmaster',array('accountcaode'),array('9320'),array('accountcode','accountname','group_'),array('9320','Jahresgewinn','GEWINN'));
InsertRecord('chartmaster',array('accountcaode'),array('9420'),array('accountcode','accountname','group_'),array('9420','Abfertigungsr','R'));
InsertRecord('chartmaster',array('accountcaode'),array('9430'),array('accountcode','accountname','group_'),array('9430','Urlaubsr','R'));
?>