<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiven'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiven'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Erfolg'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Aufwand'));
InsertRecord('accountgroups',array('groupname'),array('ABSCHREIBUNGEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('10','ABSCHREIBUNGEN','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('AUFWENDUNGEN F'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('20','AUFWENDUNGEN F','10','0','1000','',''));
InsertRecord('accountgroups',array('groupname'),array('BETEILIGUNGSERTR'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('30','BETEILIGUNGSERTR','30','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('BETRIEBS- UND GESCH'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('40','BETRIEBS- UND GESCH','10','0','6000','',''));
InsertRecord('accountgroups',array('groupname'),array('BEZOGENE TEILE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('50','BEZOGENE TEILE','10','0','10000','',''));
InsertRecord('accountgroups',array('groupname'),array('EB,SB,G+V KONTEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('60','EB,SB,G+V KONTEN','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('EINLAGEN STILLER GESELLSCHAFTE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('70','EINLAGEN STILLER GESELLSCHAFTE','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('FAHRZEUGE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('80','FAHRZEUGE','10','0','5000','',''));
InsertRecord('accountgroups',array('groupname'),array('FERTIGE ERZEUGNISSE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('90','FERTIGE ERZEUGNISSE','10','0','13000','',''));
InsertRecord('accountgroups',array('groupname'),array('FINANZANLAGEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('100','FINANZANLAGEN','10','0','8000','',''));
InsertRecord('accountgroups',array('groupname'),array('FINANZERTR'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('110','FINANZERTR','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('FORDERUNGEN AUS ABGABENVERRECH'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('120','FORDERUNGEN AUS ABGABENVERRECH','10','0','20000','',''));
InsertRecord('accountgroups',array('groupname'),array('FORDEUNGEN AUS LIEFERUNGEN UND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('130','FORDEUNGEN AUS LIEFERUNGEN UND','10','0','18000','',''));
InsertRecord('accountgroups',array('groupname'),array('FREIWILLIGER SOZIALAUFWAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('140','FREIWILLIGER SOZIALAUFWAND','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('GEAHLTSAUFWAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('150','GEAHLTSAUFWAND','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('GELEISTETE ANZAHLUNGEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('160','GELEISTETE ANZAHLUNGEN','10','0','7000','',''));
InsertRecord('accountgroups',array('groupname'),array('GELEISTETE ANZAHLUNGEN 2'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('170','GELEISTETE ANZAHLUNGEN 2','10','0','16000','',''));
InsertRecord('accountgroups',array('groupname'),array('GESETZLICHER SOZIALAUFWAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('180','GESETZLICHER SOZIALAUFWAND','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('GEWINN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('190','GEWINN','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('GRUNDST'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('200','GRUNDST','10','0','3000','',''));
InsertRecord('accountgroups',array('groupname'),array('HILFS- UND BETRIEBSSTOFFE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('210','HILFS- UND BETRIEBSSTOFFE','10','0','11000','',''));
InsertRecord('accountgroups',array('groupname'),array('IMMATERIELLE VERM'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('220','IMMATERIELLE VERM','10','0','2000','',''));
InsertRecord('accountgroups',array('groupname'),array('INSTANDHALTUNGSAUFWAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('230','INSTANDHALTUNGSAUFWAND','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('KAPITAL'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('240','KAPITAL','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('KAPITALR'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('250','KAPITALR','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('KASSABESTAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('260','KASSABESTAND','10','0','22000','',''));
InsertRecord('accountgroups',array('groupname'),array('LANGFRISTIGE VERBINDLICHKEITEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('270','LANGFRISTIGE VERBINDLICHKEITEN','20','0','24000','',''));
InsertRecord('accountgroups',array('groupname'),array('LOHNAUFWAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('280','LOHNAUFWAND','40','1','32000','',''));
InsertRecord('accountgroups',array('groupname'),array('MASCHINEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('290','MASCHINEN','10','0','4000','',''));
InsertRecord('accountgroups',array('groupname'),array('MIET-,PACHT-,LEASING-, LIZENZA'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('300','MIET-,PACHT-,LEASING-, LIZENZA','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('NOCH NICHT ABGERECHNETE LEISTU'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('310','NOCH NICHT ABGERECHNETE LEISTU','10','0','15000','',''));
InsertRecord('accountgroups',array('groupname'),array('R'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('320','R','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('ROHSTOFFE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('330','ROHSTOFFE','10','0','9000','',''));
InsertRecord('accountgroups',array('groupname'),array('SCHECKS, GUTHABEN BEI KREDITIN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('340','SCHECKS, GUTHABEN BEI KREDITIN','10','0','23000','',''));
InsertRecord('accountgroups',array('groupname'),array('SONSTIGE ERL'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('350','SONSTIGE ERL','30','1','29000','',''));
InsertRecord('accountgroups',array('groupname'),array('SONSTIGE FORDERUNGEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('360','SONSTIGE FORDERUNGEN','10','0','19000','',''));
InsertRecord('accountgroups',array('groupname'),array('SONSTIGE STEUERN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('370','SONSTIGE STEUERN','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('TRANSPORTKOSTEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('380','TRANSPORTKOSTEN','20','0','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('UMSATZ'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('390','UMSATZ','30','1','27000','',''));
InsertRecord('accountgroups',array('groupname'),array('UMSATZ BERATUNG'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('400','UMSATZ BERATUNG','30','1','28000','',''));
InsertRecord('accountgroups',array('groupname'),array('UNFERTIGE ERZEUGNISSE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('410','UNFERTIGE ERZEUGNISSE','10','0','12000','',''));
InsertRecord('accountgroups',array('groupname'),array('VERBINDLICHKEITEN AUS LIEFERUN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('420','VERBINDLICHKEITEN AUS LIEFERUN','20','0','25000','',''));
InsertRecord('accountgroups',array('groupname'),array('VERBINDLICHKEITEN FINANZAMT'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('430','VERBINDLICHKEITEN FINANZAMT','20','0','26000','',''));
InsertRecord('accountgroups',array('groupname'),array('VERBRAUCH BRENN- UND TREIBSTOF'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('440','VERBRAUCH BRENN- UND TREIBSTOF','30','1','31000','',''));
InsertRecord('accountgroups',array('groupname'),array('VERSICHERUNGEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('450','VERSICHERUNGEN','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('VERWALTUNGSKOSTEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('460','VERWALTUNGSKOSTEN','40','1','32767','',''));
InsertRecord('accountgroups',array('groupname'),array('WAREN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('470','WAREN','10','0','14000','',''));
InsertRecord('accountgroups',array('groupname'),array('WARENEINSATZ'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('480','WARENEINSATZ','40','1','30000','',''));
InsertRecord('accountgroups',array('groupname'),array('WERTBERICHTIGUNGEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('490','WERTBERICHTIGUNGEN','10','0','17000','',''));
InsertRecord('accountgroups',array('groupname'),array('WERTPAPIERE UND ANTEILE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('500','WERTPAPIERE UND ANTEILE','10','0','21000','',''));
InsertRecord('chartmaster',array('accountcode'),array('0010'),array('accountcode','accountname','group_'),array('0010','Firmenwert','AUFWENDUNGEN F'));
InsertRecord('chartmaster',array('accountcode'),array('0110'),array('accountcode','accountname','group_'),array('0110','Rechte','IMMATERIELLE VERM'));
InsertRecord('chartmaster',array('accountcode'),array('0210'),array('accountcode','accountname','group_'),array('0210','unbebaute Grundst','GRUNDST'));
InsertRecord('chartmaster',array('accountcode'),array('0220'),array('accountcode','accountname','group_'),array('0220','bebaute Grundst','GRUNDST'));
InsertRecord('chartmaster',array('accountcode'),array('0229'),array('accountcode','accountname','group_'),array('0229','kum. Abschreibung bebaute Grundst','GRUNDST'));
InsertRecord('chartmaster',array('accountcode'),array('0410'),array('accountcode','accountname','group_'),array('0410','Maschinen','MASCHINEN'));
InsertRecord('chartmaster',array('accountcode'),array('0419'),array('accountcode','accountname','group_'),array('0419','kum. Abschreibung Maschinen','MASCHINEN'));
InsertRecord('chartmaster',array('accountcode'),array('0510'),array('accountcode','accountname','group_'),array('0510','Fahrzeuge','FAHRZEUGE'));
InsertRecord('chartmaster',array('accountcode'),array('0519'),array('accountcode','accountname','group_'),array('0519','kum. Abschreibung Fahrzeuge','FAHRZEUGE'));
InsertRecord('chartmaster',array('accountcode'),array('0620'),array('accountcode','accountname','group_'),array('0620','B','BETRIEBS- UND GESCH'));
InsertRecord('chartmaster',array('accountcode'),array('0625'),array('accountcode','accountname','group_'),array('0625','kum. Abschreibung Betriebs- und Gesch','BETRIEBS- UND GESCH'));
InsertRecord('chartmaster',array('accountcode'),array('0810'),array('accountcode','accountname','group_'),array('0810','Beteiligungen','FINANZANLAGEN'));
InsertRecord('chartmaster',array('accountcode'),array('0820'),array('accountcode','accountname','group_'),array('0820','Wertpapiere','FINANZANLAGEN'));
InsertRecord('chartmaster',array('accountcode'),array('1120'),array('accountcode','accountname','group_'),array('1120','Vorr','ROHSTOFFE'));
InsertRecord('chartmaster',array('accountcode'),array('1220'),array('accountcode','accountname','group_'),array('1220','Vorr','BEZOGENE TEILE'));
InsertRecord('chartmaster',array('accountcode'),array('1320'),array('accountcode','accountname','group_'),array('1320','Hilfsstoffe','HILFS- UND BETRIEBSSTOFFE'));
InsertRecord('chartmaster',array('accountcode'),array('1350'),array('accountcode','accountname','group_'),array('1350','Betriebssstoffe','HILFS- UND BETRIEBSSTOFFE'));
InsertRecord('chartmaster',array('accountcode'),array('1420'),array('accountcode','accountname','group_'),array('1420','Vorr','UNFERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcode'),array('1520'),array('accountcode','accountname','group_'),array('1520','Vorr','FERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcode'),array('1530'),array('accountcode','accountname','group_'),array('1530','Vorr','FERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcode'),array('1540'),array('accountcode','accountname','group_'),array('1540','Vorr','FERTIGE ERZEUGNISSE'));
InsertRecord('chartmaster',array('accountcode'),array('2010'),array('accountcode','accountname','group_'),array('2010','Forderungen Lieferung & Leistung','FORDEUNGEN AUS LIEFERUNGEN UND'));
InsertRecord('chartmaster',array('accountcode'),array('2019'),array('accountcode','accountname','group_'),array('2019','Wertberichtigung uneinbringliche Forderungen','FORDEUNGEN AUS LIEFERUNGEN UND'));
InsertRecord('chartmaster',array('accountcode'),array('2320'),array('accountcode','accountname','group_'),array('2320','sonstige Forderungen','SONSTIGE FORDERUNGEN'));
InsertRecord('chartmaster',array('accountcode'),array('2520'),array('accountcode','accountname','group_'),array('2520','sonstige Forderungen aus Abgebenverrechnung','FORDERUNGEN AUS ABGABENVERRECH'));
InsertRecord('chartmaster',array('accountcode'),array('2620'),array('accountcode','accountname','group_'),array('2620','Wertpapiere Umlaufverm','WERTPAPIERE UND ANTEILE'));
InsertRecord('chartmaster',array('accountcode'),array('2701'),array('accountcode','accountname','group_'),array('2701','Kassa','KASSABESTAND'));
InsertRecord('chartmaster',array('accountcode'),array('2810'),array('accountcode','accountname','group_'),array('2810','Schecks','SCHECKS, GUTHABEN BEI KREDITIN'));
InsertRecord('chartmaster',array('accountcode'),array('2820'),array('accountcode','accountname','group_'),array('2820','Bankguthaben','SCHECKS, GUTHABEN BEI KREDITIN'));
InsertRecord('chartmaster',array('accountcode'),array('3110'),array('accountcode','accountname','group_'),array('3110','Bank Verbindlichkeiten','LANGFRISTIGE VERBINDLICHKEITEN'));
InsertRecord('chartmaster',array('accountcode'),array('3120'),array('accountcode','accountname','group_'),array('3120','Kredite von Eigent','LANGFRISTIGE VERBINDLICHKEITEN'));
InsertRecord('chartmaster',array('accountcode'),array('3310'),array('accountcode','accountname','group_'),array('3310','Verbindlichkeiten aus Lieferungen und Leistungen','VERBINDLICHKEITEN AUS LIEFERUN'));
InsertRecord('chartmaster',array('accountcode'),array('3510'),array('accountcode','accountname','group_'),array('3510','Finanzamt Verrechnung K','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('3520'),array('accountcode','accountname','group_'),array('3520','Finanzamt Verrechnung Umsatzsteuer','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('3530'),array('accountcode','accountname','group_'),array('3530','Umsatzsteuer 0%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('3531'),array('accountcode','accountname','group_'),array('3531','Umsatzsteuer 10%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('3532'),array('accountcode','accountname','group_'),array('3532','Umsatzsteuer 20%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('3540'),array('accountcode','accountname','group_'),array('3540','Vorsteuer 0%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('3541'),array('accountcode','accountname','group_'),array('3541','Vorsteuer 10%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('3542'),array('accountcode','accountname','group_'),array('3542','Vorsteuer 20%','VERBINDLICHKEITEN FINANZAMT'));
InsertRecord('chartmaster',array('accountcode'),array('4020'),array('accountcode','accountname','group_'),array('4020','Verkauf - Hardware','UMSATZ'));
InsertRecord('chartmaster',array('accountcode'),array('4030'),array('accountcode','accountname','group_'),array('4030','Verkauf - Software','UMSATZ'));
InsertRecord('chartmaster',array('accountcode'),array('4040'),array('accountcode','accountname','group_'),array('4040','Verkauf - Ersatzteile','UMSATZ'));
InsertRecord('chartmaster',array('accountcode'),array('4320'),array('accountcode','accountname','group_'),array('4320','Erl','UMSATZ BERATUNG'));
InsertRecord('chartmaster',array('accountcode'),array('4330'),array('accountcode','accountname','group_'),array('4330','Erl','UMSATZ BERATUNG'));
InsertRecord('chartmaster',array('accountcode'),array('4630'),array('accountcode','accountname','group_'),array('4630','Frachterl','SONSTIGE ERL'));
InsertRecord('chartmaster',array('accountcode'),array('4640'),array('accountcode','accountname','group_'),array('4640','Devisengewinne','SONSTIGE ERL'));
InsertRecord('chartmaster',array('accountcode'),array('5020'),array('accountcode','accountname','group_'),array('5020','Wareneinsatz / Hardware','WARENEINSATZ'));
InsertRecord('chartmaster',array('accountcode'),array('5030'),array('accountcode','accountname','group_'),array('5030','Wareneinsatz / Software','WARENEINSATZ'));
InsertRecord('chartmaster',array('accountcode'),array('5040'),array('accountcode','accountname','group_'),array('5040','Wareneinsatz / Ersatzteile','WARENEINSATZ'));
InsertRecord('chartmaster',array('accountcode'),array('5610'),array('accountcode','accountname','group_'),array('5610','Energie, Wasser','VERBRAUCH BRENN- UND TREIBSTOF'));
InsertRecord('chartmaster',array('accountcode'),array('6010'),array('accountcode','accountname','group_'),array('6010','Lohn','LOHNAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('6210'),array('accountcode','accountname','group_'),array('6210','Gehalt','GEAHLTSAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('6510'),array('accountcode','accountname','group_'),array('6510','Dienstgeberanteile','GESETZLICHER SOZIALAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('6710'),array('accountcode','accountname','group_'),array('6710','freiwilliger Sozialaufwand','FREIWILLIGER SOZIALAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('7010'),array('accountcode','accountname','group_'),array('7010','Abschreibungen','ABSCHREIBUNGEN'));
InsertRecord('chartmaster',array('accountcode'),array('7020'),array('accountcode','accountname','group_'),array('7020','geringwertige Wirtschaftsg','ABSCHREIBUNGEN'));
InsertRecord('chartmaster',array('accountcode'),array('7110'),array('accountcode','accountname','group_'),array('7110','Ertragssteuern','SONSTIGE STEUERN'));
InsertRecord('chartmaster',array('accountcode'),array('7120'),array('accountcode','accountname','group_'),array('7120','Grundsteuern','SONSTIGE STEUERN'));
InsertRecord('chartmaster',array('accountcode'),array('7210'),array('accountcode','accountname','group_'),array('7210','Reparatur und Instandhaltung','INSTANDHALTUNGSAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('7310'),array('accountcode','accountname','group_'),array('7310','Frachtaufwand','TRANSPORTKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7410'),array('accountcode','accountname','group_'),array('7410','Miete','MIET-,PACHT-,LEASING-, LIZENZA'));
InsertRecord('chartmaster',array('accountcode'),array('7411'),array('accountcode','accountname','group_'),array('7411','Lizenzen','MIET-,PACHT-,LEASING-, LIZENZA'));
InsertRecord('chartmaster',array('accountcode'),array('7610'),array('accountcode','accountname','group_'),array('7610','Beratungsaufwand','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7611'),array('accountcode','accountname','group_'),array('7611','B','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7615'),array('accountcode','accountname','group_'),array('7615','Werbung und Marketing','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7620'),array('accountcode','accountname','group_'),array('7620','uneinbringliche Forderungen','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7630'),array('accountcode','accountname','group_'),array('7630','Telephonkosten','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7631'),array('accountcode','accountname','group_'),array('7631','Internetkosten','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7632'),array('accountcode','accountname','group_'),array('7632','Reise- und Repr','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7634'),array('accountcode','accountname','group_'),array('7634','Registrierungsgeb','VERWALTUNGSKOSTEN'));
InsertRecord('chartmaster',array('accountcode'),array('7710'),array('accountcode','accountname','group_'),array('7710','Versicherung','VERSICHERUNGEN'));
InsertRecord('chartmaster',array('accountcode'),array('8020'),array('accountcode','accountname','group_'),array('8020','Bankzinsen und Geb','FINANZERTR'));
InsertRecord('chartmaster',array('accountcode'),array('8050'),array('accountcode','accountname','group_'),array('8050','Devisenverluste','FINANZERTR'));
InsertRecord('chartmaster',array('accountcode'),array('8110'),array('accountcode','accountname','group_'),array('8110','Ertr','BETEILIGUNGSERTR'));
InsertRecord('chartmaster',array('accountcode'),array('9010'),array('accountcode','accountname','group_'),array('9010','Aktien, Gesch','KAPITAL'));
InsertRecord('chartmaster',array('accountcode'),array('9020'),array('accountcode','accountname','group_'),array('9020','nicht einbezahltes Kapital','KAPITAL'));
InsertRecord('chartmaster',array('accountcode'),array('9210'),array('accountcode','accountname','group_'),array('9210','freie R','KAPITALR'));
InsertRecord('chartmaster',array('accountcode'),array('9310'),array('accountcode','accountname','group_'),array('9310','Gewinnvortrag Vorjahr','GEWINN'));
InsertRecord('chartmaster',array('accountcode'),array('9320'),array('accountcode','accountname','group_'),array('9320','Jahresgewinn','GEWINN'));
InsertRecord('chartmaster',array('accountcode'),array('9420'),array('accountcode','accountname','group_'),array('9420','Abfertigungsr','R'));
InsertRecord('chartmaster',array('accountcode'),array('9430'),array('accountcode','accountname','group_'),array('9430','Urlaubsr','R'));
?>