<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiven'), $db);
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiven'), $db);
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Erfolg'), $db);
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Aufwand'), $db);
InsertRecord('accountgroups',array('groupname'),array(''),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('','30','1','21000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('AKTIVEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('AKTIVEN','10','0','1000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('AKTIVIERTER AUFWAND UND AKTIVE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('AKTIVIERTER AUFWAND UND AKTIVE','10','0','7000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Andere kurzfristige Verbindlic'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Andere kurzfristige Verbindlic','20','0','12000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('ANLAGEVERM'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ANLAGEVERM','10','0','6000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('AUFWAND F'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('AUFWAND F','40','1','25000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('BESTANDES'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('BESTANDES','30','1','23000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('BETRIEBSERTRAG AUS LIEFERUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('BETRIEBSERTRAG AUS LIEFERUNGEN','30','1','17000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('DIENSTLEISTUNGSERTRAG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('DIENSTLEISTUNGSERTRAG','30','1','20000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('EIGENKAPITAL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('EIGENKAPITAL','20','0','15000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('EIGENLEISTUNGEN UND EIGENVERBR'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('EIGENLEISTUNGEN UND EIGENVERBR','30','1','22000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('ERTRAGSMINDERUNGEN AUS PRODUKT'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ERTRAGSMINDERUNGEN AUS PRODUKT','30','1','24000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Fl'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Fl','10','0','3000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Forderungen'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Forderungen','10','0','4000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('FREMDKAPITAL KURZFRISTIG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FREMDKAPITAL KURZFRISTIG','20','0','9000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('FREMDKAPITAL LANGFRISTIG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FREMDKAPITAL LANGFRISTIG','20','0','14000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('HANDELSERTRAG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('HANDELSERTRAG','30','1','19000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('HANDELSWARENAUFWAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('HANDELSWARENAUFWAND','40','1','27000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Kurzfristige Finanzverbindlich'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kurzfristige Finanzverbindlich','20','0','11000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Kurzfristige Verbindlichkeiten'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kurzfristige Verbindlichkeiten','20','0','10000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('MATERIALAUFWAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('MATERIALAUFWAND','40','1','26000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Passive Rechnungsabgrenzung, k'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Passive Rechnungsabgrenzung, k','20','0','13000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('PASSIVEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('PASSIVEN','20','0','8000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('PRODUKTIONSERTRAG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('PRODUKTIONSERTRAG','30','1','18000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Reserven, Bilanzgewinn'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Reserven, Bilanzgewinn','20','0','16000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('UMLAUFSVERM'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('UMLAUFSVERM','10','0','2000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Vorr'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Vorr','10','0','5000',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11101'),array('accountcode','accountname','group_'),array('11101','Kasse','Fl'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11102'),array('accountcode','accountname','group_'),array('11102','Bank CS','Fl'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11111'),array('accountcode','accountname','group_'),array('11111','Debitoren','Forderungen'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11117'),array('accountcode','accountname','group_'),array('11117','MWST Vorsteuer auf Aufwand','Forderungen'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11118'),array('accountcode','accountname','group_'),array('11118','MWST Vorsteuer auf Investitionen','Forderungen'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11119'),array('accountcode','accountname','group_'),array('11119','Verrechnungssteuer','Forderungen'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11121'),array('accountcode','accountname','group_'),array('11121','Warenvorr','Vorr'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11128'),array('accountcode','accountname','group_'),array('11128','Angefangene Arbeiten','Vorr'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('11130'),array('accountcode','accountname','group_'),array('11130','Aktive Rechnungsabgrenzung','Vorr'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('14151'),array('accountcode','accountname','group_'),array('14151','Mobiliar und Einrichtungen','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('14152'),array('accountcode','accountname','group_'),array('14152','B','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('18181'),array('accountcode','accountname','group_'),array('18181','Gr','AKTIVIERTER AUFWAND UND AKTIVE'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('18182'),array('accountcode','accountname','group_'),array('18182','Entwicklungsaufwand','AKTIVIERTER AUFWAND UND AKTIVE'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21201'),array('accountcode','accountname','group_'),array('21201','Lieferanten','Kurzfristige Verbindlichkeiten'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21202'),array('accountcode','accountname','group_'),array('21202','Personalaufwand','Kurzfristige Verbindlichkeiten'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21203'),array('accountcode','accountname','group_'),array('21203','Sozialversicherungen','Kurzfristige Verbindlichkeiten'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21205'),array('accountcode','accountname','group_'),array('21205','Leasing','Kurzfristige Verbindlichkeiten'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21216'),array('accountcode','accountname','group_'),array('21216','Gesellschafter','Kurzfristige Finanzverbindlich'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21217'),array('accountcode','accountname','group_'),array('21217','Privat','Kurzfristige Finanzverbindlich'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21221'),array('accountcode','accountname','group_'),array('21221','MWST (2,4)','Andere kurzfristige Verbindlic'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21222'),array('accountcode','accountname','group_'),array('21222','MWST (3,6)','Andere kurzfristige Verbindlic'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21223'),array('accountcode','accountname','group_'),array('21223','MWST (7,6)','Andere kurzfristige Verbindlic'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21224'),array('accountcode','accountname','group_'),array('21224','MWST (7.6) 1/2','Andere kurzfristige Verbindlic'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21228'),array('accountcode','accountname','group_'),array('21228','Geschuldete Steuern','Andere kurzfristige Verbindlic'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21229'),array('accountcode','accountname','group_'),array('21229','Gewinnaussch','Andere kurzfristige Verbindlic'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21231'),array('accountcode','accountname','group_'),array('21231','Passive Rechnungsabgrenzung','Passive Rechnungsabgrenzung, k'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('21235'),array('accountcode','accountname','group_'),array('21235','R','Passive Rechnungsabgrenzung, k'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('24256'),array('accountcode','accountname','group_'),array('24256','Gesellschafter','FREMDKAPITAL LANGFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('28280'),array('accountcode','accountname','group_'),array('28280','Stammkapital','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('28291'),array('accountcode','accountname','group_'),array('28291','Reserven','Reserven, Bilanzgewinn'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('28295'),array('accountcode','accountname','group_'),array('28295','Gewinnvortrag','Reserven, Bilanzgewinn'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('28296'),array('accountcode','accountname','group_'),array('28296','Jahresgewinn','Reserven, Bilanzgewinn'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('31001'),array('accountcode','accountname','group_'),array('31001','Computer','PRODUKTIONSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('31005'),array('accountcode','accountname','group_'),array('31005','','PRODUKTIONSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('32001'),array('accountcode','accountname','group_'),array('32001','Hardware','HANDELSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('32002'),array('accountcode','accountname','group_'),array('32002','Software OSS','HANDELSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('32003'),array('accountcode','accountname','group_'),array('32003','Software kommerz.','HANDELSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('32005'),array('accountcode','accountname','group_'),array('32005','','HANDELSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('34001'),array('accountcode','accountname','group_'),array('34001','Beratung','DIENSTLEISTUNGSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('34002'),array('accountcode','accountname','group_'),array('34002','Installation','DIENSTLEISTUNGSERTRAG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('36001'),array('accountcode','accountname','group_'),array('36001','Reisezeit',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('36002'),array('accountcode','accountname','group_'),array('36002','Reise (Fahrt)',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('36003'),array('accountcode','accountname','group_'),array('36003','Essen',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('36004'),array('accountcode','accountname','group_'),array('36004','Versand',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('36005'),array('accountcode','accountname','group_'),array('36005','Kursgewinn',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('37001'),array('accountcode','accountname','group_'),array('37001','Eigenleistungen','EIGENLEISTUNGEN UND EIGENVERBR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('37002'),array('accountcode','accountname','group_'),array('37002','Eigenverbrauch','EIGENLEISTUNGEN UND EIGENVERBR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('38001'),array('accountcode','accountname','group_'),array('38001','Bestandes','BESTANDES'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('39001'),array('accountcode','accountname','group_'),array('39001','Skonti','ERTRAGSMINDERUNGEN AUS PRODUKT'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('39002'),array('accountcode','accountname','group_'),array('39002','Rabatte, Preisnachl','ERTRAGSMINDERUNGEN AUS PRODUKT'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('39004'),array('accountcode','accountname','group_'),array('39004','Rundungsdifferenzen','ERTRAGSMINDERUNGEN AUS PRODUKT'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('39005'),array('accountcode','accountname','group_'),array('39005','Verluste aus Forderungen','ERTRAGSMINDERUNGEN AUS PRODUKT'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('39006'),array('accountcode','accountname','group_'),array('39006','Kursverlust','ERTRAGSMINDERUNGEN AUS PRODUKT'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('41001'),array('accountcode','accountname','group_'),array('41001','Computer','MATERIALAUFWAND'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('41005'),array('accountcode','accountname','group_'),array('41005','','MATERIALAUFWAND'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('42001'),array('accountcode','accountname','group_'),array('42001','Hardware','HANDELSWARENAUFWAND'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('42002'),array('accountcode','accountname','group_'),array('42002','Software OSS','HANDELSWARENAUFWAND'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('42003'),array('accountcode','accountname','group_'),array('42003','Software kommerz.','HANDELSWARENAUFWAND'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('42005'),array('accountcode','accountname','group_'),array('42005','','HANDELSWARENAUFWAND'), $db);
?>