<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiven'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiven'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Erfolg'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Aufwand'));
InsertRecord('accountgroups',array('groupname'),array('Abschreibungen'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Abschreibungen','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('Ausgaben'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Ausgaben','40','1','5000',''));
InsertRecord('accountgroups',array('groupname'),array('Debitoren'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Debitoren','10','0','20000',''));
InsertRecord('accountgroups',array('groupname'),array('Finanzausk'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Finanzausk','40','1','32767',''));
InsertRecord('accountgroups',array('groupname'),array('Fixkosten'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Fixkosten','10','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('Kapital'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kapital','20','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('Kasse/Bank'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kasse/Bank','10','0','10000',''));
InsertRecord('accountgroups',array('groupname'),array('Kreditoren'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kreditoren','20','0','30000',''));
InsertRecord('accountgroups',array('groupname'),array('Lager'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Lager','10','0','32767',''));
InsertRecord('accountgroups',array('groupname'),array('Verkauf'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Verkauf','30','1','1000',''));
InsertRecord('accountgroups',array('groupname'),array('Verkaufskosten'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Verkaufskosten','40','1','2000',''));
InsertRecord('chartmaster',array('accountcaode'),array('1400'),array('accountcode','accountname','group_'),array('1400','Lager Rohwaren','Lager'));
InsertRecord('chartmaster',array('accountcaode'),array('1410'),array('accountcode','accountname','group_'),array('1410','Lager in Arbeit stehende G','Lager'));
InsertRecord('chartmaster',array('accountcaode'),array('1420'),array('accountcode','accountname','group_'),array('1420','Lager vertiggestellte G','Lager'));
InsertRecord('chartmaster',array('accountcaode'),array('1430'),array('accountcode','accountname','group_'),array('1430','Erhaltene G','Kreditoren'));
InsertRecord('chartmaster',array('accountcaode'),array('1500'),array('accountcode','accountname','group_'),array('1500','Debitoren','Debitoren'));
InsertRecord('chartmaster',array('accountcaode'),array('1700'),array('accountcode','accountname','group_'),array('1700','Bankkonto','Kasse/Bank'));
InsertRecord('chartmaster',array('accountcaode'),array('1705'),array('accountcode','accountname','group_'),array('1705','Kasse','Kasse/Bank'));
InsertRecord('chartmaster',array('accountcaode'),array('1710'),array('accountcode','accountname','group_'),array('1710','Fremdw','Kasse/Bank'));
InsertRecord('chartmaster',array('accountcaode'),array('2000'),array('accountcode','accountname','group_'),array('2000','Eigenkaptial','Kapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2050'),array('accountcode','accountname','group_'),array('2050','Gewinnvortrag','Kapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2630'),array('accountcode','accountname','group_'),array('2630','Kreditoren','Kreditoren'));
InsertRecord('chartmaster',array('accountcaode'),array('2660'),array('accountcode','accountname','group_'),array('2660','MwSt CH','Kreditoren'));
InsertRecord('chartmaster',array('accountcaode'),array('2662'),array('accountcode','accountname','group_'),array('2662','MwSt CH (Hardware)','Kreditoren'));
InsertRecord('chartmaster',array('accountcaode'),array('2664'),array('accountcode','accountname','group_'),array('2664','MwSt DE','Kreditoren'));
InsertRecord('chartmaster',array('accountcaode'),array('2680'),array('accountcode','accountname','group_'),array('2680','MwSt CH (Vorsteuer)','Kreditoren'));
InsertRecord('chartmaster',array('accountcaode'),array('2682'),array('accountcode','accountname','group_'),array('2682','MwSt DE (Vorsteuer)','Kreditoren'));
InsertRecord('chartmaster',array('accountcaode'),array('3000'),array('accountcode','accountname','group_'),array('3000','Verkauf','Verkauf'));
InsertRecord('chartmaster',array('accountcaode'),array('3010'),array('accountcode','accountname','group_'),array('3010','Verkauf - Wiederverkauf','Verkauf'));
InsertRecord('chartmaster',array('accountcaode'),array('3020'),array('accountcode','accountname','group_'),array('3020','Verkauf -','Verkauf'));
InsertRecord('chartmaster',array('accountcaode'),array('3200'),array('accountcode','accountname','group_'),array('3200','Rabatte, p','Verkauf'));
InsertRecord('chartmaster',array('accountcaode'),array('3400'),array('accountcode','accountname','group_'),array('3400','W','Verkauf'));
InsertRecord('chartmaster',array('accountcaode'),array('3800'),array('accountcode','accountname','group_'),array('3800','Frachtkosten, Dritte','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('4000'),array('accountcode','accountname','group_'),array('4000','Materialeinkauf','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4010'),array('accountcode','accountname','group_'),array('4010','Verkaufskosten, Endkunden','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4200'),array('accountcode','accountname','group_'),array('4200','Materialverbrauch, Differenzen','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4210'),array('accountcode','accountname','group_'),array('4210','Materialverbrauch','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4220'),array('accountcode','accountname','group_'),array('4220','Materialeinkauf, Differnzen','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4250'),array('accountcode','accountname','group_'),array('4250','Rabatte, Erhaltene','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4260'),array('accountcode','accountname','group_'),array('4260','W','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4300'),array('accountcode','accountname','group_'),array('4300','Frachtkosten, eigene','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('4500'),array('accountcode','accountname','group_'),array('4500','Verpackungsmaterial','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('5000'),array('accountcode','accountname','group_'),array('5000','Lohnkosten','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('5050'),array('accountcode','accountname','group_'),array('5050','Lohnkosten, zur','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('5200'),array('accountcode','accountname','group_'),array('5200','Lohnkosten, indirekte','Verkaufskosten'));
InsertRecord('chartmaster',array('accountcaode'),array('5210'),array('accountcode','accountname','group_'),array('5210','Gemeinkosten','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6400'),array('accountcode','accountname','group_'),array('6400','Kommissionen','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6600'),array('accountcode','accountname','group_'),array('6600','Reparaturen B','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6700'),array('accountcode','accountname','group_'),array('6700','Ausgaben, allgemeine','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6730'),array('accountcode','accountname','group_'),array('6730','Telefon','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6790'),array('accountcode','accountname','group_'),array('6790','Bankspesen','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6800'),array('accountcode','accountname','group_'),array('6800','Unterhaltskosten','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6810'),array('accountcode','accountname','group_'),array('6810','Prozesskosten/Recht','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('6840'),array('accountcode','accountname','group_'),array('6840','Kreditorenkontrolle','Ausgaben'));
InsertRecord('chartmaster',array('accountcaode'),array('7040'),array('accountcode','accountname','group_'),array('7040','Abschreibungen B','Abschreibungen'));
InsertRecord('chartmaster',array('accountcaode'),array('8200'),array('accountcode','accountname','group_'),array('8200','Bankzinsen','Finanzausk'));
?>