<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiven'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiven'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Erfolg'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Aufwand'));
InsertRecord('accountgroups',array('groupname'),array('AKTIVEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('10','AKTIVEN','10','0','1000','',''));
InsertRecord('accountgroups',array('groupname'),array('AKTIVIERTER AUFWAND UND AKTIVE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('20','AKTIVIERTER AUFWAND UND AKTIVE','10','0','7000','',''));
InsertRecord('accountgroups',array('groupname'),array('Andere kurzfristige Verbindlic'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('30','Andere kurzfristige Verbindlic','20','0','12000','',''));
InsertRecord('accountgroups',array('groupname'),array('ANLAGEVERM'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('40','ANLAGEVERM','10','0','6000','',''));
InsertRecord('accountgroups',array('groupname'),array('AUFWAND F'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('50','AUFWAND F','40','1','25000','',''));
InsertRecord('accountgroups',array('groupname'),array('BESTANDES'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('60','BESTANDES','30','1','23000','',''));
InsertRecord('accountgroups',array('groupname'),array('BETRIEBSERTRAG AUS LIEFERUNGEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('70','BETRIEBSERTRAG AUS LIEFERUNGEN','30','1','17000','',''));
InsertRecord('accountgroups',array('groupname'),array('DIENSTLEISTUNGSERTRAG'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('80','DIENSTLEISTUNGSERTRAG','30','1','20000','',''));
InsertRecord('accountgroups',array('groupname'),array('EIGENKAPITAL'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('90','EIGENKAPITAL','20','0','15000','',''));
InsertRecord('accountgroups',array('groupname'),array('EIGENLEISTUNGEN UND EIGENVERBR'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('100','EIGENLEISTUNGEN UND EIGENVERBR','30','1','22000','',''));
InsertRecord('accountgroups',array('groupname'),array('ERTRAGSMINDERUNGEN AUS PRODUKT'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('110','ERTRAGSMINDERUNGEN AUS PRODUKT','30','1','24000','',''));
InsertRecord('accountgroups',array('groupname'),array('Fl'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('120','Fl','10','0','3000','',''));
InsertRecord('accountgroups',array('groupname'),array('Forderungen'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('130','Forderungen','10','0','4000','',''));
InsertRecord('accountgroups',array('groupname'),array('FREMDKAPITAL KURZFRISTIG'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('140','FREMDKAPITAL KURZFRISTIG','20','0','9000','',''));
InsertRecord('accountgroups',array('groupname'),array('FREMDKAPITAL LANGFRISTIG'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('150','FREMDKAPITAL LANGFRISTIG','20','0','14000','',''));
InsertRecord('accountgroups',array('groupname'),array('HANDELSERTRAG'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('160','HANDELSERTRAG','30','1','19000','',''));
InsertRecord('accountgroups',array('groupname'),array('HANDELSWARENAUFWAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('170','HANDELSWARENAUFWAND','40','1','27000','',''));
InsertRecord('accountgroups',array('groupname'),array('Kurzfristige Finanzverbindlich'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('180','Kurzfristige Finanzverbindlich','20','0','11000','',''));
InsertRecord('accountgroups',array('groupname'),array('Kurzfristige Verbindlichkeiten'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('190','Kurzfristige Verbindlichkeiten','20','0','10000','',''));
InsertRecord('accountgroups',array('groupname'),array('MATERIALAUFWAND'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('200','MATERIALAUFWAND','40','1','26000','',''));
InsertRecord('accountgroups',array('groupname'),array('Passive Rechnungsabgrenzung, k'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('210','Passive Rechnungsabgrenzung, k','20','0','13000','',''));
InsertRecord('accountgroups',array('groupname'),array('PASSIVEN'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('220','PASSIVEN','20','0','8000','',''));
InsertRecord('accountgroups',array('groupname'),array('PRODUKTIONSERTRAG'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('230','PRODUKTIONSERTRAG','30','1','18000','',''));
InsertRecord('accountgroups',array('groupname'),array('Reserven, Bilanzgewinn'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('240','Reserven, Bilanzgewinn','20','0','16000','',''));
InsertRecord('accountgroups',array('groupname'),array('UMLAUFSVERM'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('250','UMLAUFSVERM','10','0','2000','',''));
InsertRecord('accountgroups',array('groupname'),array('Vorr'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('260','Vorr','10','0','5000','',''));
InsertRecord('chartmaster',array('accountcode'),array('11101'),array('accountcode','accountname','group_'),array('11101','Kasse','Fl'));
InsertRecord('chartmaster',array('accountcode'),array('11102'),array('accountcode','accountname','group_'),array('11102','Bank CS','Fl'));
InsertRecord('chartmaster',array('accountcode'),array('11111'),array('accountcode','accountname','group_'),array('11111','Debitoren','Forderungen'));
InsertRecord('chartmaster',array('accountcode'),array('11117'),array('accountcode','accountname','group_'),array('11117','MWST Vorsteuer auf Aufwand','Forderungen'));
InsertRecord('chartmaster',array('accountcode'),array('11118'),array('accountcode','accountname','group_'),array('11118','MWST Vorsteuer auf Investitionen','Forderungen'));
InsertRecord('chartmaster',array('accountcode'),array('11119'),array('accountcode','accountname','group_'),array('11119','Verrechnungssteuer','Forderungen'));
InsertRecord('chartmaster',array('accountcode'),array('11121'),array('accountcode','accountname','group_'),array('11121','Warenvorr','Vorr'));
InsertRecord('chartmaster',array('accountcode'),array('11128'),array('accountcode','accountname','group_'),array('11128','Angefangene Arbeiten','Vorr'));
InsertRecord('chartmaster',array('accountcode'),array('11130'),array('accountcode','accountname','group_'),array('11130','Aktive Rechnungsabgrenzung','Vorr'));
InsertRecord('chartmaster',array('accountcode'),array('14151'),array('accountcode','accountname','group_'),array('14151','Mobiliar und Einrichtungen','ANLAGEVERM'));
InsertRecord('chartmaster',array('accountcode'),array('14152'),array('accountcode','accountname','group_'),array('14152','B','ANLAGEVERM'));
InsertRecord('chartmaster',array('accountcode'),array('18181'),array('accountcode','accountname','group_'),array('18181','Gr','AKTIVIERTER AUFWAND UND AKTIVE'));
InsertRecord('chartmaster',array('accountcode'),array('18182'),array('accountcode','accountname','group_'),array('18182','Entwicklungsaufwand','AKTIVIERTER AUFWAND UND AKTIVE'));
InsertRecord('chartmaster',array('accountcode'),array('21201'),array('accountcode','accountname','group_'),array('21201','Lieferanten','Kurzfristige Verbindlichkeiten'));
InsertRecord('chartmaster',array('accountcode'),array('21202'),array('accountcode','accountname','group_'),array('21202','Personalaufwand','Kurzfristige Verbindlichkeiten'));
InsertRecord('chartmaster',array('accountcode'),array('21203'),array('accountcode','accountname','group_'),array('21203','Sozialversicherungen','Kurzfristige Verbindlichkeiten'));
InsertRecord('chartmaster',array('accountcode'),array('21205'),array('accountcode','accountname','group_'),array('21205','Leasing','Kurzfristige Verbindlichkeiten'));
InsertRecord('chartmaster',array('accountcode'),array('21216'),array('accountcode','accountname','group_'),array('21216','Gesellschafter','Kurzfristige Finanzverbindlich'));
InsertRecord('chartmaster',array('accountcode'),array('21217'),array('accountcode','accountname','group_'),array('21217','Privat','Kurzfristige Finanzverbindlich'));
InsertRecord('chartmaster',array('accountcode'),array('21221'),array('accountcode','accountname','group_'),array('21221','MWST (2,4)','Andere kurzfristige Verbindlic'));
InsertRecord('chartmaster',array('accountcode'),array('21222'),array('accountcode','accountname','group_'),array('21222','MWST (3,6)','Andere kurzfristige Verbindlic'));
InsertRecord('chartmaster',array('accountcode'),array('21223'),array('accountcode','accountname','group_'),array('21223','MWST (7,6)','Andere kurzfristige Verbindlic'));
InsertRecord('chartmaster',array('accountcode'),array('21224'),array('accountcode','accountname','group_'),array('21224','MWST (7.6) 1/2','Andere kurzfristige Verbindlic'));
InsertRecord('chartmaster',array('accountcode'),array('21228'),array('accountcode','accountname','group_'),array('21228','Geschuldete Steuern','Andere kurzfristige Verbindlic'));
InsertRecord('chartmaster',array('accountcode'),array('21229'),array('accountcode','accountname','group_'),array('21229','Gewinnaussch','Andere kurzfristige Verbindlic'));
InsertRecord('chartmaster',array('accountcode'),array('21231'),array('accountcode','accountname','group_'),array('21231','Passive Rechnungsabgrenzung','Passive Rechnungsabgrenzung, k'));
InsertRecord('chartmaster',array('accountcode'),array('21235'),array('accountcode','accountname','group_'),array('21235','R','Passive Rechnungsabgrenzung, k'));
InsertRecord('chartmaster',array('accountcode'),array('24256'),array('accountcode','accountname','group_'),array('24256','Gesellschafter','FREMDKAPITAL LANGFRISTIG'));
InsertRecord('chartmaster',array('accountcode'),array('28280'),array('accountcode','accountname','group_'),array('28280','Stammkapital','EIGENKAPITAL'));
InsertRecord('chartmaster',array('accountcode'),array('28291'),array('accountcode','accountname','group_'),array('28291','Reserven','Reserven, Bilanzgewinn'));
InsertRecord('chartmaster',array('accountcode'),array('28295'),array('accountcode','accountname','group_'),array('28295','Gewinnvortrag','Reserven, Bilanzgewinn'));
InsertRecord('chartmaster',array('accountcode'),array('28296'),array('accountcode','accountname','group_'),array('28296','Jahresgewinn','Reserven, Bilanzgewinn'));
InsertRecord('chartmaster',array('accountcode'),array('31001'),array('accountcode','accountname','group_'),array('31001','Computer','PRODUKTIONSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('31005'),array('accountcode','accountname','group_'),array('31005','','PRODUKTIONSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('32001'),array('accountcode','accountname','group_'),array('32001','Hardware','HANDELSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('32002'),array('accountcode','accountname','group_'),array('32002','Software OSS','HANDELSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('32003'),array('accountcode','accountname','group_'),array('32003','Software kommerz.','HANDELSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('32005'),array('accountcode','accountname','group_'),array('32005','','HANDELSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('34001'),array('accountcode','accountname','group_'),array('34001','Beratung','DIENSTLEISTUNGSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('34002'),array('accountcode','accountname','group_'),array('34002','Installation','DIENSTLEISTUNGSERTRAG'));
InsertRecord('chartmaster',array('accountcode'),array('36001'),array('accountcode','accountname','group_'),array('36001','Reisezeit','',''));
InsertRecord('chartmaster',array('accountcode'),array('36002'),array('accountcode','accountname','group_'),array('36002','Reise (Fahrt)','',''));
InsertRecord('chartmaster',array('accountcode'),array('36003'),array('accountcode','accountname','group_'),array('36003','Essen','',''));
InsertRecord('chartmaster',array('accountcode'),array('36004'),array('accountcode','accountname','group_'),array('36004','Versand','',''));
InsertRecord('chartmaster',array('accountcode'),array('36005'),array('accountcode','accountname','group_'),array('36005','Kursgewinn','',''));
InsertRecord('chartmaster',array('accountcode'),array('37001'),array('accountcode','accountname','group_'),array('37001','Eigenleistungen','EIGENLEISTUNGEN UND EIGENVERBR'));
InsertRecord('chartmaster',array('accountcode'),array('37002'),array('accountcode','accountname','group_'),array('37002','Eigenverbrauch','EIGENLEISTUNGEN UND EIGENVERBR'));
InsertRecord('chartmaster',array('accountcode'),array('38001'),array('accountcode','accountname','group_'),array('38001','Bestandes','BESTANDES'));
InsertRecord('chartmaster',array('accountcode'),array('39001'),array('accountcode','accountname','group_'),array('39001','Skonti','ERTRAGSMINDERUNGEN AUS PRODUKT'));
InsertRecord('chartmaster',array('accountcode'),array('39002'),array('accountcode','accountname','group_'),array('39002','Rabatte, Preisnachl','ERTRAGSMINDERUNGEN AUS PRODUKT'));
InsertRecord('chartmaster',array('accountcode'),array('39004'),array('accountcode','accountname','group_'),array('39004','Rundungsdifferenzen','ERTRAGSMINDERUNGEN AUS PRODUKT'));
InsertRecord('chartmaster',array('accountcode'),array('39005'),array('accountcode','accountname','group_'),array('39005','Verluste aus Forderungen','ERTRAGSMINDERUNGEN AUS PRODUKT'));
InsertRecord('chartmaster',array('accountcode'),array('39006'),array('accountcode','accountname','group_'),array('39006','Kursverlust','ERTRAGSMINDERUNGEN AUS PRODUKT'));
InsertRecord('chartmaster',array('accountcode'),array('41001'),array('accountcode','accountname','group_'),array('41001','Computer','MATERIALAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('41005'),array('accountcode','accountname','group_'),array('41005','','MATERIALAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('42001'),array('accountcode','accountname','group_'),array('42001','Hardware','HANDELSWARENAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('42002'),array('accountcode','accountname','group_'),array('42002','Software OSS','HANDELSWARENAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('42003'),array('accountcode','accountname','group_'),array('42003','Software kommerz.','HANDELSWARENAUFWAND'));
InsertRecord('chartmaster',array('accountcode'),array('42005'),array('accountcode','accountname','group_'),array('42005','','HANDELSWARENAUFWAND'));
?>