INSERT INTO `accountsection` (`sectionid`, `language`, `sectionname`) VALUES (10,'de_CH.utf8','Aktiven');
INSERT INTO `accountsection` (`sectionid`, `language`, `sectionname`) VALUES (20,'de_CH.utf8','Passiven');
INSERT INTO `accountsection` (`sectionid`, `language`, `sectionname`) VALUES (30,'de_CH.utf8','Erfolg');
INSERT INTO `accountsection` (`sectionid`, `language`, `sectionname`) VALUES (40,'de_CH.utf8','Aufwand');

INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('AKTIVEN','10','de_CH.utf8',10,0,1000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('EIGENLEISTUNGEN UND EIGENVERBR','100','de_CH.utf8',30,1,22000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('ERTRAGSMINDERUNGEN AUS PRODUKT','110','de_CH.utf8',30,1,24000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Fl','120','de_CH.utf8',10,0,3000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Forderungen','130','de_CH.utf8',10,0,4000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('FREMDKAPITAL KURZFRISTIG','140','de_CH.utf8',20,0,9000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('FREMDKAPITAL LANGFRISTIG','150','de_CH.utf8',20,0,14000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('HANDELSERTRAG','160','de_CH.utf8',30,1,19000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('HANDELSWARENAUFWAND','170','de_CH.utf8',40,1,27000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Kurzfristige Finanzverbindlich','180','de_CH.utf8',20,0,11000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Kurzfristige Verbindlichkeiten','190','de_CH.utf8',20,0,10000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('AKTIVIERTER AUFWAND UND AKTIVE','20','de_CH.utf8',10,0,7000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('MATERIALAUFWAND','200','de_CH.utf8',40,1,26000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Passive Rechnungsabgrenzung, k','210','de_CH.utf8',20,0,13000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('PASSIVEN','220','de_CH.utf8',20,0,8000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('PRODUKTIONSERTRAG','230','de_CH.utf8',30,1,18000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Reserven, Bilanzgewinn','240','de_CH.utf8',20,0,16000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('UMLAUFSVERM','250','de_CH.utf8',10,0,2000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Vorr','260','de_CH.utf8',10,0,5000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('Andere kurzfristige Verbindlic','30','de_CH.utf8',20,0,12000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('ANLAGEVERM','40','de_CH.utf8',10,0,6000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('AUFWAND F','50','de_CH.utf8',40,1,25000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('BESTANDES','60','de_CH.utf8',30,1,23000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('BETRIEBSERTRAG AUS LIEFERUNGEN','70','de_CH.utf8',30,1,17000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('DIENSTLEISTUNGSERTRAG','80','de_CH.utf8',30,1,20000,'','');
INSERT INTO `accountgroups` (`groupname`, `groupcode`, `language`, `sectioninaccounts`, `pandl`, `sequenceintb`, `parentgroupname`, `parentgroupcode`) VALUES ('EIGENKAPITAL','90','de_CH.utf8',20,0,15000,'','');

INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11101','de_CH.utf8','Kasse','Fl','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11102','de_CH.utf8','Bank CS','Fl','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11111','de_CH.utf8','Debitoren','Forderungen','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11117','de_CH.utf8','MWST Vorsteuer auf Aufwand','Forderungen','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11118','de_CH.utf8','MWST Vorsteuer auf Investitionen','Forderungen','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11119','de_CH.utf8','Verrechnungssteuer','Forderungen','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11121','de_CH.utf8','Warenvorr','Vorr','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11128','de_CH.utf8','Angefangene Arbeiten','Vorr','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('11130','de_CH.utf8','Aktive Rechnungsabgrenzung','Vorr','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('14151','de_CH.utf8','Mobiliar und Einrichtungen','ANLAGEVERM','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('14152','de_CH.utf8','B','ANLAGEVERM','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('18181','de_CH.utf8','Gr','AKTIVIERTER AUFWAND UND AKTIVE','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('18182','de_CH.utf8','Entwicklungsaufwand','AKTIVIERTER AUFWAND UND AKTIVE','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21201','de_CH.utf8','Lieferanten','Kurzfristige Verbindlichkeiten','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21202','de_CH.utf8','Personalaufwand','Kurzfristige Verbindlichkeiten','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21203','de_CH.utf8','Sozialversicherungen','Kurzfristige Verbindlichkeiten','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21205','de_CH.utf8','Leasing','Kurzfristige Verbindlichkeiten','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21216','de_CH.utf8','Gesellschafter','Kurzfristige Finanzverbindlich','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21217','de_CH.utf8','Privat','Kurzfristige Finanzverbindlich','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21221','de_CH.utf8','MWST (2,4)','Andere kurzfristige Verbindlic','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21222','de_CH.utf8','MWST (3,6)','Andere kurzfristige Verbindlic','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21223','de_CH.utf8','MWST (7,6)','Andere kurzfristige Verbindlic','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21224','de_CH.utf8','MWST (7.6) 1/2','Andere kurzfristige Verbindlic','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21228','de_CH.utf8','Geschuldete Steuern','Andere kurzfristige Verbindlic','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21229','de_CH.utf8','Gewinnaussch','Andere kurzfristige Verbindlic','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21231','de_CH.utf8','Passive Rechnungsabgrenzung','Passive Rechnungsabgrenzung, k','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('21235','de_CH.utf8','R','Passive Rechnungsabgrenzung, k','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('24256','de_CH.utf8','Gesellschafter','FREMDKAPITAL LANGFRISTIG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('28280','de_CH.utf8','Stammkapital','EIGENKAPITAL','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('28291','de_CH.utf8','Reserven','Reserven, Bilanzgewinn','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('28295','de_CH.utf8','Gewinnvortrag','Reserven, Bilanzgewinn','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('28296','de_CH.utf8','Jahresgewinn','Reserven, Bilanzgewinn','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('31001','de_CH.utf8','Computer','PRODUKTIONSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('31005','de_CH.utf8','','PRODUKTIONSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('32001','de_CH.utf8','Hardware','HANDELSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('32002','de_CH.utf8','Software OSS','HANDELSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('32003','de_CH.utf8','Software kommerz.','HANDELSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('32005','de_CH.utf8','','HANDELSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('34001','de_CH.utf8','Beratung','DIENSTLEISTUNGSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('34002','de_CH.utf8','Installation','DIENSTLEISTUNGSERTRAG','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('37001','de_CH.utf8','Eigenleistungen','EIGENLEISTUNGEN UND EIGENVERBR','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('37002','de_CH.utf8','Eigenverbrauch','EIGENLEISTUNGEN UND EIGENVERBR','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('38001','de_CH.utf8','Bestandes','BESTANDES','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('39001','de_CH.utf8','Skonti','ERTRAGSMINDERUNGEN AUS PRODUKT','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('39002','de_CH.utf8','Rabatte, Preisnachl','ERTRAGSMINDERUNGEN AUS PRODUKT','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('39004','de_CH.utf8','Rundungsdifferenzen','ERTRAGSMINDERUNGEN AUS PRODUKT','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('39005','de_CH.utf8','Verluste aus Forderungen','ERTRAGSMINDERUNGEN AUS PRODUKT','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('39006','de_CH.utf8','Kursverlust','ERTRAGSMINDERUNGEN AUS PRODUKT','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('41001','de_CH.utf8','Computer','MATERIALAUFWAND','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('41005','de_CH.utf8','','MATERIALAUFWAND','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('42001','de_CH.utf8','Hardware','HANDELSWARENAUFWAND','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('42002','de_CH.utf8','Software OSS','HANDELSWARENAUFWAND','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('42003','de_CH.utf8','Software kommerz.','HANDELSWARENAUFWAND','');
INSERT INTO `chartmaster` (`accountcode`, `language`, `accountname`, `group_`, `groupcode`) VALUES ('42005','de_CH.utf8','','HANDELSWARENAUFWAND','');
