<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Aktiven'), $db);
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Passiven'), $db);
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Erfolg'), $db);
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Aufwand'), $db);
InsertRecord('accountgroups',array('groupname'),array('ANLAGEVERM'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ANLAGEVERM','10','0','1000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Ausserordentl.Ertr'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Ausserordentl.Ertr','30','1','18000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('EIGENKAPITAL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('EIGENKAPITAL','20','0','5000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('ERTR'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ERTR','30','1','14000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('FORDERUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FORDERUNGEN','10','0','3000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('FREMDKAPITAL KURZFRISTIG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FREMDKAPITAL KURZFRISTIG','20','0','8000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('FREMDKAPITAL LANGFRISTIG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('FREMDKAPITAL LANGFRISTIG','20','0','7000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Guthabenzinsen'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Guthabenzinsen','30','1','17000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('LIQUIDE MITTEL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('LIQUIDE MITTEL','10','0','4000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('NEUTRALE AUFWENDUNGEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('NEUTRALE AUFWENDUNGEN','40','1','15000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('NEUTRALE ERTR'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('NEUTRALE ERTR','30','1','16000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('PERSONALKOSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('PERSONALKOSTEN','40','1','11000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('R'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('R','20','0','6000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('RAUMKOSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('RAUMKOSTEN','40','1','12000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('SONSTIGE KOSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('SONSTIGE KOSTEN','40','1','13000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('WARENBESTAND'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('WARENBESTAND','10','0','2000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('WARENEINGANG'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('WARENEINGANG','40','1','9000',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('0100'),array('accountcode','accountname','group_'),array('0100','Konzessionen & Lizenzen','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('0135'),array('accountcode','accountname','group_'),array('0135','EDV-Programme','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('0440'),array('accountcode','accountname','group_'),array('0440','Maschinen','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('0500'),array('accountcode','accountname','group_'),array('0500','Betriebsausstattung','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('0520'),array('accountcode','accountname','group_'),array('0520','PKW','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('0650'),array('accountcode','accountname','group_'),array('0650','B','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('0670'),array('accountcode','accountname','group_'),array('0670','GWG','ANLAGEVERM'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1140'),array('accountcode','accountname','group_'),array('1140','Warenbestand','WARENBESTAND'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1201'),array('accountcode','accountname','group_'),array('1201','Geleistete Anzahlungen','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1210'),array('accountcode','accountname','group_'),array('1210','Forderungen ohne Kontokorrent','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1300'),array('accountcode','accountname','group_'),array('1300','Sonstige Forderungen','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1370'),array('accountcode','accountname','group_'),array('1370','Ungekl','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1400'),array('accountcode','accountname','group_'),array('1400','Anrechenbare Vorsteuer','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1401'),array('accountcode','accountname','group_'),array('1401','Anrechenbare Vorsteuer 7%','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1402'),array('accountcode','accountname','group_'),array('1402','Vorsteuer ig Erwerb','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1403'),array('accountcode','accountname','group_'),array('1403','Vorsteuer ig Erwerb 16%','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1405'),array('accountcode','accountname','group_'),array('1405','Anrechenbare Vorsteuer 16%','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1406'),array('accountcode','accountname','group_'),array('1406','Anrechenbare Vorsteuer 15%','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1433'),array('accountcode','accountname','group_'),array('1433','bezahlte Einfuhrumsatzsteuer','FORDERUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1601'),array('accountcode','accountname','group_'),array('1601','Kasse','LIQUIDE MITTEL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1700'),array('accountcode','accountname','group_'),array('1700','Postgiro','LIQUIDE MITTEL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1800'),array('accountcode','accountname','group_'),array('1800','Bank','LIQUIDE MITTEL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1810'),array('accountcode','accountname','group_'),array('1810','Bank USD','LIQUIDE MITTEL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1820'),array('accountcode','accountname','group_'),array('1820','Kreditkarten','LIQUIDE MITTEL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1890'),array('accountcode','accountname','group_'),array('1890','Geldtransit','LIQUIDE MITTEL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1900'),array('accountcode','accountname','group_'),array('1900','Aktive Rechnungsabgrenzung','LIQUIDE MITTEL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2001'),array('accountcode','accountname','group_'),array('2001','Eigenkapital','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2100'),array('accountcode','accountname','group_'),array('2100','Privatentnahmen','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2150'),array('accountcode','accountname','group_'),array('2150','Privatsteuern','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2180'),array('accountcode','accountname','group_'),array('2180','Privateinlagen','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2200'),array('accountcode','accountname','group_'),array('2200','Sonderausgaben beschr.abzugsf.','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2900'),array('accountcode','accountname','group_'),array('2900','Gezeichnetes Kapital','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2910'),array('accountcode','accountname','group_'),array('2910','Ausstehende Einlagen','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2970'),array('accountcode','accountname','group_'),array('2970','Gewinnvortrag vor Verwendung','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2978'),array('accountcode','accountname','group_'),array('2978','Verlustvortrag vor Verwendung','EIGENKAPITAL'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3030'),array('accountcode','accountname','group_'),array('3030','Gewerbesteuerr','R'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3070'),array('accountcode','accountname','group_'),array('3070','Sonstige R','R'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3095'),array('accountcode','accountname','group_'),array('3095','R','R'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3160'),array('accountcode','accountname','group_'),array('3160','Bankdarlehen','FREMDKAPITAL LANGFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3280'),array('accountcode','accountname','group_'),array('3280','Erhaltene Anzahlungen','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3310'),array('accountcode','accountname','group_'),array('3310','Kreditoren ohne Kontokorrent','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3500'),array('accountcode','accountname','group_'),array('3500','Sonstige Verbindlichkeiten','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3560'),array('accountcode','accountname','group_'),array('3560','Darlehen','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3700'),array('accountcode','accountname','group_'),array('3700','Verbindl. Betr.steuern u.Abgaben','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3720'),array('accountcode','accountname','group_'),array('3720','Verbindlichkeiten L','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3730'),array('accountcode','accountname','group_'),array('3730','Verbindlichkeiten Lohnsteuer','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3740'),array('accountcode','accountname','group_'),array('3740','Verbindlichkeiten Sozialversicherung','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3800'),array('accountcode','accountname','group_'),array('3800','Umsatzsteuer','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3801'),array('accountcode','accountname','group_'),array('3801','Umsatzsteuer 7%','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3802'),array('accountcode','accountname','group_'),array('3802','Umsatzsteuer ig. Erwerb','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3803'),array('accountcode','accountname','group_'),array('3803','Umsatzsteuer ig. Erwerb 16%','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3805'),array('accountcode','accountname','group_'),array('3805','Umsatzsteuer 16%','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3806'),array('accountcode','accountname','group_'),array('3806','Umsatzsteuer 15%','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3815'),array('accountcode','accountname','group_'),array('3815','Umsatzsteuer nicht f','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3816'),array('accountcode','accountname','group_'),array('3816','Umsatzsteuer nicht f','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3820'),array('accountcode','accountname','group_'),array('3820','Umsatzsteuer-Vorauszahlungen','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3841'),array('accountcode','accountname','group_'),array('3841','Umsatzsteuer Vorjahr','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3900'),array('accountcode','accountname','group_'),array('3900','Aktive Rechnungsabgrenzung','FREMDKAPITAL KURZFRISTIG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5200'),array('accountcode','accountname','group_'),array('5200','Wareneingang ohne Vorsteuer','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5300'),array('accountcode','accountname','group_'),array('5300','Wareneingang 7%','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5400'),array('accountcode','accountname','group_'),array('5400','Wareneingang 15%','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5420'),array('accountcode','accountname','group_'),array('5420','ig.Erwerb 7% VoSt. und 7% USt.','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5425'),array('accountcode','accountname','group_'),array('5425','ig.Erwerb 15% VoSt. und 15% USt.','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5731'),array('accountcode','accountname','group_'),array('5731','Erhaltene Skonti 7% Vorsteuer','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5736'),array('accountcode','accountname','group_'),array('5736','Erhaltene Skonti 15% Vorsteuer','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5800'),array('accountcode','accountname','group_'),array('5800','Anschaffungsnebenkosten','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5900'),array('accountcode','accountname','group_'),array('5900','Fremdarbeiten','WARENEINGANG'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6010'),array('accountcode','accountname','group_'),array('6010','L','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6020'),array('accountcode','accountname','group_'),array('6020','Geh','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6030'),array('accountcode','accountname','group_'),array('6030','Aushilfsl','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6040'),array('accountcode','accountname','group_'),array('6040','Lohnsteuer Aushilfen','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6080'),array('accountcode','accountname','group_'),array('6080','Verm','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6090'),array('accountcode','accountname','group_'),array('6090','Fahrtkostenerst.Whg./Arbeitsst','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6110'),array('accountcode','accountname','group_'),array('6110','Sozialversicherung','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6120'),array('accountcode','accountname','group_'),array('6120','Berufsgenossenschaft','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6130'),array('accountcode','accountname','group_'),array('6130','Freiw. Soz. Aufw. LSt- u. Soz.Vers.frei','PERSONALKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6310'),array('accountcode','accountname','group_'),array('6310','Miete','RAUMKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6315'),array('accountcode','accountname','group_'),array('6315','Pacht','RAUMKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6320'),array('accountcode','accountname','group_'),array('6320','Heizung','RAUMKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6325'),array('accountcode','accountname','group_'),array('6325','Gas Strom Wasser','RAUMKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6330'),array('accountcode','accountname','group_'),array('6330','Reinigung','RAUMKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6335'),array('accountcode','accountname','group_'),array('6335','Instandhaltung betriebliche R','RAUMKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6345'),array('accountcode','accountname','group_'),array('6345','Sonstige Raumkosten','RAUMKOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6402'),array('accountcode','accountname','group_'),array('6402','Abschreibungen','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6403'),array('accountcode','accountname','group_'),array('6403','Kaufleasing','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6404'),array('accountcode','accountname','group_'),array('6404','Sofortabschreibung GWG','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6405'),array('accountcode','accountname','group_'),array('6405','Sonstige Kosten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6410'),array('accountcode','accountname','group_'),array('6410','Versicherung','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6420'),array('accountcode','accountname','group_'),array('6420','Beitr','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6430'),array('accountcode','accountname','group_'),array('6430','Sonstige Abgaben','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6470'),array('accountcode','accountname','group_'),array('6470','Rep. und Instandhaltung BGA','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6520'),array('accountcode','accountname','group_'),array('6520','Kfz-Versicherung','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6530'),array('accountcode','accountname','group_'),array('6530','Lfd. Kfz-Kosten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6540'),array('accountcode','accountname','group_'),array('6540','Kfz-Reparaturen','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6560'),array('accountcode','accountname','group_'),array('6560','Fremdfahrzeuge','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6570'),array('accountcode','accountname','group_'),array('6570','Sonstige Kfz-Kosten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6600'),array('accountcode','accountname','group_'),array('6600','Werbung','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6610'),array('accountcode','accountname','group_'),array('6610','Kundengeschenke bis DM 75.','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6620'),array('accountcode','accountname','group_'),array('6620','Kundengeschenke','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6630'),array('accountcode','accountname','group_'),array('6630','Repr','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6640'),array('accountcode','accountname','group_'),array('6640','Bewirtungskosten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6644'),array('accountcode','accountname','group_'),array('6644','Nicht abzugsf.Bewirtungskosten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6650'),array('accountcode','accountname','group_'),array('6650','Reisekosten Arbeitnehmer','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6660'),array('accountcode','accountname','group_'),array('6660','Reisekosten Arbeitnehmer 12.3%','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6665'),array('accountcode','accountname','group_'),array('6665','Reisekosten Arbeitnehmer 9.8%','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6670'),array('accountcode','accountname','group_'),array('6670','Reisekosten Unternehmer','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6680'),array('accountcode','accountname','group_'),array('6680','Reisekosten Unternehmer 12.3%','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6685'),array('accountcode','accountname','group_'),array('6685','Reisekosten Unternehmer 9.8%','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6688'),array('accountcode','accountname','group_'),array('6688','Reisekosten Unternehmer 5.7%','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6690'),array('accountcode','accountname','group_'),array('6690','Km-Geld-Erstattung 8.2%','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6710'),array('accountcode','accountname','group_'),array('6710','Verpackungsmaterial','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6740'),array('accountcode','accountname','group_'),array('6740','Ausgangsfrachten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6780'),array('accountcode','accountname','group_'),array('6780','Fremdarbeiten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6800'),array('accountcode','accountname','group_'),array('6800','Porto','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6805'),array('accountcode','accountname','group_'),array('6805','Telefon','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6815'),array('accountcode','accountname','group_'),array('6815','B','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6820'),array('accountcode','accountname','group_'),array('6820','Zeitschriften & B','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6825'),array('accountcode','accountname','group_'),array('6825','Rechts- und Beratungskosten','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6835'),array('accountcode','accountname','group_'),array('6835','Mieten f','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6840'),array('accountcode','accountname','group_'),array('6840','Mietleasing','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6845'),array('accountcode','accountname','group_'),array('6845','Werkzeuge und Kleinger','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6850'),array('accountcode','accountname','group_'),array('6850','Betriebsbedarf','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6852'),array('accountcode','accountname','group_'),array('6852','Gast','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6855'),array('accountcode','accountname','group_'),array('6855','Nebenkosten des Geldverkehrs','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6880'),array('accountcode','accountname','group_'),array('6880','Aufwendungen aus Kursdifferenzen','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6885'),array('accountcode','accountname','group_'),array('6885','Erl','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7610'),array('accountcode','accountname','group_'),array('7610','Gewerbesteuer','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7685'),array('accountcode','accountname','group_'),array('7685','Kfz-Steuer','SONSTIGE KOSTEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8120'),array('accountcode','accountname','group_'),array('8120','Steuerfreie Ums','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8125'),array('accountcode','accountname','group_'),array('8125','Steuerfreie ig. Lieferungen 1b UStG.','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8200'),array('accountcode','accountname','group_'),array('8200','Erl','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8300'),array('accountcode','accountname','group_'),array('8300','Erl','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8400'),array('accountcode','accountname','group_'),array('8400','Erl','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8500'),array('accountcode','accountname','group_'),array('8500','Provisionserl','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8630'),array('accountcode','accountname','group_'),array('8630','Entnahme sonstg. Leistungen 7% USt.','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8640'),array('accountcode','accountname','group_'),array('8640','Entnahme sonstg. Leistungen 15% USt.','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8731'),array('accountcode','accountname','group_'),array('8731','Gew. Skonti 7% USt.','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8736'),array('accountcode','accountname','group_'),array('8736','Gew. Skonti 15% USt.','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8840'),array('accountcode','accountname','group_'),array('8840','Ertr','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8845'),array('accountcode','accountname','group_'),array('8845','Erl','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8900'),array('accountcode','accountname','group_'),array('8900','Ertr','ERTR'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9310'),array('accountcode','accountname','group_'),array('9310','Zinsen kurzfr. Verbindlichkeiten','NEUTRALE AUFWENDUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9320'),array('accountcode','accountname','group_'),array('9320','Zinsen langfr. Verbindlichkeiten','NEUTRALE AUFWENDUNGEN'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('9500'),array('accountcode','accountname','group_'),array('9500','Ausserordentl.Aufwendungen','NEUTRALE AUFWENDUNGEN'), $db);
?>