<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Assets'), $db);
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Liabilities'), $db);
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Income'), $db);
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Costs'), $db);
InsertRecord('accountsection',array('sectionid'),array(50),array('sectionid','sectionname'),array(50,'Gross'), $db);
InsertRecord('accountgroups',array('groupname'),array('Accounts Payable'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Accounts Payable','20','0','30000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Accounts Receivable'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Accounts Receivable','10','0','20000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Cash/Bank'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Cash/Bank','10','0','10000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Cost of Sales'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Cost of Sales','40','1','2000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Depreciations'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Depreciations','40','1','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Equity'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Equity','20','0','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Expenses'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Expenses','40','1','5000',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Financials'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Financials','40','1','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Fixed Assets'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Fixed Assets','10','0','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Inventory'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Inventory','10','0','32767',''), $db);
InsertRecord('accountgroups',array('groupname'),array('Sales'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Sales','30','1','1000',''), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1400'),array('accountcode','accountname','group_'),array('1400','Stocks of Raw Materials','Inventory'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1410'),array('accountcode','accountname','group_'),array('1410','Stocks of Work In Progress','Inventory'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1420'),array('accountcode','accountname','group_'),array('1420','Stocks of Finsihed Goods','Inventory'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1430'),array('accountcode','accountname','group_'),array('1430','Goods Received Clearing account','Accounts Payable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1500'),array('accountcode','accountname','group_'),array('1500','Accounts Receivable','Accounts Receivable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1700'),array('accountcode','accountname','group_'),array('1700','Bank account','Cash/Bank'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1705'),array('accountcode','accountname','group_'),array('1705','Petty Cash','Cash/Bank'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('1710'),array('accountcode','accountname','group_'),array('1710','Foreign currency account','Cash/Bank'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2000'),array('accountcode','accountname','group_'),array('2000','Share Capital','Equity'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2050'),array('accountcode','accountname','group_'),array('2050','Retained Earnings','Equity'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2630'),array('accountcode','accountname','group_'),array('2630','Accounts Payable','Accounts Payable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2660'),array('accountcode','accountname','group_'),array('2660','VAT out 5','Accounts Payable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2662'),array('accountcode','accountname','group_'),array('2662','VAT out 1','Accounts Payable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2664'),array('accountcode','accountname','group_'),array('2664','VAT out 25','Accounts Payable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2680'),array('accountcode','accountname','group_'),array('2680','VAT In 5','Accounts Payable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('2682'),array('accountcode','accountname','group_'),array('2682','VAT In 25','Accounts Payable'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3000'),array('accountcode','accountname','group_'),array('3000','Sales','Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3010'),array('accountcode','accountname','group_'),array('3010','Sales  - Wholesale','Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3020'),array('accountcode','accountname','group_'),array('3020','Sales of Other items','Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3200'),array('accountcode','accountname','group_'),array('3200','Prompt Payment Discounts','Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3400'),array('accountcode','accountname','group_'),array('3400','Difference On Exchange','Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('3800'),array('accountcode','accountname','group_'),array('3800','Freight Outwards','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4000'),array('accountcode','accountname','group_'),array('4000','Purchases of materials','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4010'),array('accountcode','accountname','group_'),array('4010','Cost of Goods Sold - Retail','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4200'),array('accountcode','accountname','group_'),array('4200','Material Usage Varaiance','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4210'),array('accountcode','accountname','group_'),array('4210','Consumable Materials','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4220'),array('accountcode','accountname','group_'),array('4220','Purchase price Variance','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4250'),array('accountcode','accountname','group_'),array('4250','Discounts Received','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4260'),array('accountcode','accountname','group_'),array('4260','Exchange Variation','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4300'),array('accountcode','accountname','group_'),array('4300','Freight Inwards','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('4500'),array('accountcode','accountname','group_'),array('4500','Packaging','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5000'),array('accountcode','accountname','group_'),array('5000','Direct Labour','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5050'),array('accountcode','accountname','group_'),array('5050','Direct Labour Recovery','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5200'),array('accountcode','accountname','group_'),array('5200','Indirect Labour','Cost of Sales'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('5210'),array('accountcode','accountname','group_'),array('5210','Overhead Recovery','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6400'),array('accountcode','accountname','group_'),array('6400','Commissions','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6600'),array('accountcode','accountname','group_'),array('6600','Repairs and Maintenance Office','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6700'),array('accountcode','accountname','group_'),array('6700','General Expenses','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6730'),array('accountcode','accountname','group_'),array('6730','phone','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6790'),array('accountcode','accountname','group_'),array('6790','Bank Charges','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6800'),array('accountcode','accountname','group_'),array('6800','Entertainments','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6810'),array('accountcode','accountname','group_'),array('6810','Legal Expenses','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('6840'),array('accountcode','accountname','group_'),array('6840','Credit Control','Expenses'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('7040'),array('accountcode','accountname','group_'),array('7040','Depreciation Office Equipment','Depreciations'), $db);
InsertRecord('chartmaster',array('accountcaode'),array('8200'),array('accountcode','accountname','group_'),array('8200','Bank Interest','Financials'), $db);
?>