<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Assets'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Liabilities'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Income'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Costs'));
InsertRecord('accountgroups',array('groupname'),array('ACTIF COURANT'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('10','ACTIF COURANT','10','0','1000','',''));
InsertRecord('accountgroups',array('groupname'),array('AUTRES IMMOBILISATIONS'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('20','AUTRES IMMOBILISATIONS','10','0','3000','',''));
InsertRecord('accountgroups',array('groupname'),array('AUTRES REVENUS'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('30','AUTRES REVENUS','30','1','9000','',''));
InsertRecord('accountgroups',array('groupname'),array('CAPITAL SOCIAL'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('40','CAPITAL SOCIAL','20','0','7000','',''));
InsertRecord('accountgroups',array('groupname'),array('CO'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('50','CO','40','1','10000','',''));
InsertRecord('accountgroups',array('groupname'),array('D'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('60','D','40','1','12000','',''));
InsertRecord('accountgroups',array('groupname'),array('FRAIS DE PERSONNEL'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('70','FRAIS DE PERSONNEL','40','1','11000','',''));
InsertRecord('accountgroups',array('groupname'),array('PASSIF'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('80','PASSIF','20','0','6000','',''));
InsertRecord('accountgroups',array('groupname'),array('PASSIF COURANT'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('90','PASSIF COURANT','20','0','4000','',''));
InsertRecord('accountgroups',array('groupname'),array('RETENUES SUR SALAIRE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('100','RETENUES SUR SALAIRE','20','0','5000','',''));
InsertRecord('accountgroups',array('groupname'),array('REVENUS DE VENTE'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('110','REVENUS DE VENTE','30','1','8000','',''));
InsertRecord('accountgroups',array('groupname'),array('STOCKS'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('120','STOCKS','10','0','2000','',''));
InsertRecord('chartmaster',array('accountcode'),array('1060'),array('accountcode','accountname','group_'),array('1060','Compte ch','ACTIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('1065'),array('accountcode','accountname','group_'),array('1065','Petite caisse','ACTIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('1200'),array('accountcode','accountname','group_'),array('1200','Comptes clients','ACTIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('1205'),array('accountcode','accountname','group_'),array('1205','Provisions pour cr','ACTIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('1520'),array('accountcode','accountname','group_'),array('1520','Stocks / G','STOCKS'));
InsertRecord('chartmaster',array('accountcode'),array('1530'),array('accountcode','accountname','group_'),array('1530','Stocks / Pi','STOCKS'));
InsertRecord('chartmaster',array('accountcode'),array('1540'),array('accountcode','accountname','group_'),array('1540','Stocks / Mati','STOCKS'));
InsertRecord('chartmaster',array('accountcode'),array('1820'),array('accountcode','accountname','group_'),array('1820','Meubles et accessoires','AUTRES IMMOBILISATIONS'));
InsertRecord('chartmaster',array('accountcode'),array('1825'),array('accountcode','accountname','group_'),array('1825','Amortissement cumul','AUTRES IMMOBILISATIONS'));
InsertRecord('chartmaster',array('accountcode'),array('1840'),array('accountcode','accountname','group_'),array('1840','V','AUTRES IMMOBILISATIONS'));
InsertRecord('chartmaster',array('accountcode'),array('1845'),array('accountcode','accountname','group_'),array('1845','Amortissement cumul','AUTRES IMMOBILISATIONS'));
InsertRecord('chartmaster',array('accountcode'),array('2100'),array('accountcode','accountname','group_'),array('2100','Comptes fournisseurs','PASSIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('2160'),array('accountcode','accountname','group_'),array('2160','Taxes f','PASSIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('2170'),array('accountcode','accountname','group_'),array('2170','Taxes provinciales','PASSIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('2310'),array('accountcode','accountname','group_'),array('2310','TPS','PASSIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('2320'),array('accountcode','accountname','group_'),array('2320','TVQ','PASSIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('2380'),array('accountcode','accountname','group_'),array('2380','Indemnit','PASSIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('2390'),array('accountcode','accountname','group_'),array('2390','CSST','PASSIF COURANT'));
InsertRecord('chartmaster',array('accountcode'),array('2410'),array('accountcode','accountname','group_'),array('2410','Assurance-emploi','RETENUES SUR SALAIRE'));
InsertRecord('chartmaster',array('accountcode'),array('2420'),array('accountcode','accountname','group_'),array('2420','RRQ','RETENUES SUR SALAIRE'));
InsertRecord('chartmaster',array('accountcode'),array('2450'),array('accountcode','accountname','group_'),array('2450','Imp','RETENUES SUR SALAIRE'));
InsertRecord('chartmaster',array('accountcode'),array('2620'),array('accountcode','accountname','group_'),array('2620','Emprunts bancaires','PASSIF'));
InsertRecord('chartmaster',array('accountcode'),array('2680'),array('accountcode','accountname','group_'),array('2680','Emprunt aupr','PASSIF'));
InsertRecord('chartmaster',array('accountcode'),array('3350'),array('accountcode','accountname','group_'),array('3350','Actions ordinaires','CAPITAL SOCIAL'));
InsertRecord('chartmaster',array('accountcode'),array('4020'),array('accountcode','accountname','group_'),array('4020','Ventes g','REVENUS DE VENTE'));
InsertRecord('chartmaster',array('accountcode'),array('4030'),array('accountcode','accountname','group_'),array('4030','Pi','REVENUS DE VENTE'));
InsertRecord('chartmaster',array('accountcode'),array('4430'),array('accountcode','accountname','group_'),array('4430','Transport et manutention','AUTRES REVENUS'));
InsertRecord('chartmaster',array('accountcode'),array('4440'),array('accountcode','accountname','group_'),array('4440','Int','AUTRES REVENUS'));
InsertRecord('chartmaster',array('accountcode'),array('4450'),array('accountcode','accountname','group_'),array('4450','Gain sur change','AUTRES REVENUS'));
InsertRecord('chartmaster',array('accountcode'),array('5010'),array('accountcode','accountname','group_'),array('5010','Achats','CO'));
InsertRecord('chartmaster',array('accountcode'),array('5050'),array('accountcode','accountname','group_'),array('5050','Pi','CO'));
InsertRecord('chartmaster',array('accountcode'),array('5100'),array('accountcode','accountname','group_'),array('5100','Frais de transport','CO'));
InsertRecord('chartmaster',array('accountcode'),array('5410'),array('accountcode','accountname','group_'),array('5410','Salaires','FRAIS DE PERSONNEL'));
InsertRecord('chartmaster',array('accountcode'),array('5420'),array('accountcode','accountname','group_'),array('5420','D','FRAIS DE PERSONNEL'));
InsertRecord('chartmaster',array('accountcode'),array('5430'),array('accountcode','accountname','group_'),array('5430','D','FRAIS DE PERSONNEL'));
InsertRecord('chartmaster',array('accountcode'),array('5440'),array('accountcode','accountname','group_'),array('5440','D','FRAIS DE PERSONNEL'));
InsertRecord('chartmaster',array('accountcode'),array('5610'),array('accountcode','accountname','group_'),array('5610','Frais comptables et juridiques','D'));
InsertRecord('chartmaster',array('accountcode'),array('5615'),array('accountcode','accountname','group_'),array('5615','Publicit','D'));
InsertRecord('chartmaster',array('accountcode'),array('5620'),array('accountcode','accountname','group_'),array('5620','Cr','D'));
InsertRecord('chartmaster',array('accountcode'),array('5660'),array('accountcode','accountname','group_'),array('5660','Amortissement de l\'exercice','D'));
InsertRecord('chartmaster',array('accountcode'),array('5680'),array('accountcode','accountname','group_'),array('5680','Imp','D'));
InsertRecord('chartmaster',array('accountcode'),array('5685'),array('accountcode','accountname','group_'),array('5685','Assurances','D'));
InsertRecord('chartmaster',array('accountcode'),array('5690'),array('accountcode','accountname','group_'),array('5690','Int','D'));
InsertRecord('chartmaster',array('accountcode'),array('5700'),array('accountcode','accountname','group_'),array('5700','Fournitures de bureau','D'));
InsertRecord('chartmaster',array('accountcode'),array('5760'),array('accountcode','accountname','group_'),array('5760','Loyer','D'));
InsertRecord('chartmaster',array('accountcode'),array('5765'),array('accountcode','accountname','group_'),array('5765','R','D'));
InsertRecord('chartmaster',array('accountcode'),array('5780'),array('accountcode','accountname','group_'),array('5780','T','D'));
InsertRecord('chartmaster',array('accountcode'),array('5785'),array('accountcode','accountname','group_'),array('5785','Voyages et loisirs','D'));
InsertRecord('chartmaster',array('accountcode'),array('5790'),array('accountcode','accountname','group_'),array('5790','Services publics','D'));
InsertRecord('chartmaster',array('accountcode'),array('5800'),array('accountcode','accountname','group_'),array('5800','Taxes d\'affaires, droits d\'adh','D'));
InsertRecord('chartmaster',array('accountcode'),array('5810'),array('accountcode','accountname','group_'),array('5810','Perte sur change','D'));
?>