<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Assets'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Liabilities'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Income'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Costs'));
InsertRecord('accountgroups',array('groupname'),array('AANDELEN KAPITAAL'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('AANDELEN KAPITAAL','20','0','6000',''));
InsertRecord('accountgroups',array('groupname'),array('ANDERE INKOMSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('ANDERE INKOMSTEN','30','1','10000',''));
InsertRecord('accountgroups',array('groupname'),array('CONSULTANCY INKOMSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('CONSULTANCY INKOMSTEN','30','1','9000',''));
InsertRecord('accountgroups',array('groupname'),array('GENERAL & ADMINISTRATIVE EXPEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('GENERAL & ADMINISTRATIVE EXPEN','40','1','13000',''));
InsertRecord('accountgroups',array('groupname'),array('HUIDIGE ACTIVA'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('HUIDIGE ACTIVA','10','0','1000',''));
InsertRecord('accountgroups',array('groupname'),array('HUIDIGE PASSIVA'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('HUIDIGE PASSIVA','20','0','4000',''));
InsertRecord('accountgroups',array('groupname'),array('INKOOPPRIJS VERKOPEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('INKOOPPRIJS VERKOPEN','40','1','11000',''));
InsertRecord('accountgroups',array('groupname'),array('LANGE TERMIJN ACTIVA'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('LANGE TERMIJN ACTIVA','10','0','3000',''));
InsertRecord('accountgroups',array('groupname'),array('LANGE TERMIJN PASSIVA'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('LANGE TERMIJN PASSIVA','20','0','5000',''));
InsertRecord('accountgroups',array('groupname'),array('PERSONEELS KOSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('PERSONEELS KOSTEN','40','1','12000',''));
InsertRecord('accountgroups',array('groupname'),array('VERKOOP INKOMSTEN'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('VERKOOP INKOMSTEN','30','1','8000',''));
InsertRecord('accountgroups',array('groupname'),array('VOORRAAD ACTIVA'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('VOORRAAD ACTIVA','10','0','2000',''));
InsertRecord('accountgroups',array('groupname'),array('WINSTRESERVE'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('WINSTRESERVE','20','0','7000',''));
InsertRecord('chartmaster',array('accountcaode'),array('1061'),array('accountcode','accountname','group_'),array('1061','Bank','HUIDIGE ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1065'),array('accountcode','accountname','group_'),array('1065','Kas','HUIDIGE ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1200'),array('accountcode','accountname','group_'),array('1200','Debiteuren','HUIDIGE ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1205'),array('accountcode','accountname','group_'),array('1205','Toelage voor precaire rekeningen','HUIDIGE ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1520'),array('accountcode','accountname','group_'),array('1520','Voorraad / Hardware','VOORRAAD ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1530'),array('accountcode','accountname','group_'),array('1530','Voorraad / Software','VOORRAAD ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1540'),array('accountcode','accountname','group_'),array('1540','Voorraad / Aftermarket Parts','VOORRAAD ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1820'),array('accountcode','accountname','group_'),array('1820','Inventaris','LANGE TERMIJN ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1825'),array('accountcode','accountname','group_'),array('1825','Afschrijving inventaris','LANGE TERMIJN ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1840'),array('accountcode','accountname','group_'),array('1840','Auto','LANGE TERMIJN ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('1845'),array('accountcode','accountname','group_'),array('1845','Afschrijving auto','LANGE TERMIJN ACTIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2100'),array('accountcode','accountname','group_'),array('2100','Crediteuren','HUIDIGE PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2160'),array('accountcode','accountname','group_'),array('2160','Niet-rijks Belastingen','HUIDIGE PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2170'),array('accountcode','accountname','group_'),array('2170','Omzetbelasting','HUIDIGE PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2190'),array('accountcode','accountname','group_'),array('2190','Vennootschapsbelasting','HUIDIGE PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2310'),array('accountcode','accountname','group_'),array('2310','BTW hoog','HUIDIGE PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2311'),array('accountcode','accountname','group_'),array('2311','BTW laag','HUIDIGE PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2620'),array('accountcode','accountname','group_'),array('2620','Bank Leningen','LANGE TERMIJN PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('2680'),array('accountcode','accountname','group_'),array('2680','Aandelenvermogen','LANGE TERMIJN PASSIVA'));
InsertRecord('chartmaster',array('accountcaode'),array('3350'),array('accountcode','accountname','group_'),array('3350','Aandelen in portefeuille','AANDELEN KAPITAAL'));
InsertRecord('chartmaster',array('accountcaode'),array('3590'),array('accountcode','accountname','group_'),array('3590','Winstreserve voorgaande jaren','WINSTRESERVE'));
InsertRecord('chartmaster',array('accountcaode'),array('3600'),array('accountcode','accountname','group_'),array('3600','Huidige winstreserve','WINSTRESERVE'));
InsertRecord('chartmaster',array('accountcaode'),array('4020'),array('accountcode','accountname','group_'),array('4020','Verkoop / Hardware','VERKOOP INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('4030'),array('accountcode','accountname','group_'),array('4030','Verkoop / Software','VERKOOP INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('4040'),array('accountcode','accountname','group_'),array('4040','Verkoop / Aftermarket Parts','VERKOOP INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('4320'),array('accountcode','accountname','group_'),array('4320','Consultancy','CONSULTANCY INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('4330'),array('accountcode','accountname','group_'),array('4330','Programmeren','CONSULTANCY INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('4430'),array('accountcode','accountname','group_'),array('4430','Verzend & Administratie','ANDERE INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('4440'),array('accountcode','accountname','group_'),array('4440','Rente','ANDERE INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('4450'),array('accountcode','accountname','group_'),array('4450','Foreign Exchange Gain','ANDERE INKOMSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5010'),array('accountcode','accountname','group_'),array('5010','Inkoopkosten algemeen','INKOOPPRIJS VERKOPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5020'),array('accountcode','accountname','group_'),array('5020','Inkoopkosten / Hardware','INKOOPPRIJS VERKOPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5030'),array('accountcode','accountname','group_'),array('5030','Inkoopkosten / Software','INKOOPPRIJS VERKOPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5040'),array('accountcode','accountname','group_'),array('5040','Inkoopkosten / Aftermarket Parts','INKOOPPRIJS VERKOPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5100'),array('accountcode','accountname','group_'),array('5100','Vrachtkosten','INKOOPPRIJS VERKOPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5410'),array('accountcode','accountname','group_'),array('5410','Salarissen','PERSONEELS KOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5420'),array('accountcode','accountname','group_'),array('5420','EI Expense','PERSONEELS KOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5430'),array('accountcode','accountname','group_'),array('5430','CPP Expense','PERSONEELS KOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5440'),array('accountcode','accountname','group_'),array('5440','WCB Expense','PERSONEELS KOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5470'),array('accountcode','accountname','group_'),array('5470','Employee Benefits','PERSONEELS KOSTEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5610'),array('accountcode','accountname','group_'),array('5610','Boekhouding- & Rechtkosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5615'),array('accountcode','accountname','group_'),array('5615','Reclame- & Promotiekosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5620'),array('accountcode','accountname','group_'),array('5620','Slechte Schulden','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5660'),array('accountcode','accountname','group_'),array('5660','Afschrijvingskosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5680'),array('accountcode','accountname','group_'),array('5680','Inkomsten Belastingen','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5685'),array('accountcode','accountname','group_'),array('5685','Verzekeringen','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5690'),array('accountcode','accountname','group_'),array('5690','Rente & Bankkosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5700'),array('accountcode','accountname','group_'),array('5700','Kantoorvoorzieningen','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5760'),array('accountcode','accountname','group_'),array('5760','Huurkosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5765'),array('accountcode','accountname','group_'),array('5765','Reparatie- & Onderhoudskosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5780'),array('accountcode','accountname','group_'),array('5780','Telefoonkosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5781'),array('accountcode','accountname','group_'),array('5781','Internetkosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5785'),array('accountcode','accountname','group_'),array('5785','Reis- & Vermaakkosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5790'),array('accountcode','accountname','group_'),array('5790','NUTS Kosten','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5795'),array('accountcode','accountname','group_'),array('5795','Registratie's','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5800'),array('accountcode','accountname','group_'),array('5800','Licenties','GENERAL & ADMINISTRATIVE EXPEN'));
InsertRecord('chartmaster',array('accountcaode'),array('5810'),array('accountcode','accountname','group_'),array('5810','Foreign Exchange Loss','GENERAL & ADMINISTRATIVE EXPEN'));
?>