<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Assets'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Liabilities'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Income'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Costs'));
InsertRecord('accountgroups',array('groupname'),array('Andre driftskostnader, av- og'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Andre driftskostnader, av- og','30','1','18000',''));
InsertRecord('accountgroups',array('groupname'),array('Andre fordringer'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Andre fordringer','10','0','7000',''));
InsertRecord('accountgroups',array('groupname'),array('Annen egenkapital'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Annen egenkapital','40','1','26000',''));
InsertRecord('accountgroups',array('groupname'),array('Annen langsiktig gjeld'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Annen langsiktig gjeld','20','0','12000',''));
InsertRecord('accountgroups',array('groupname'),array('Avsetninger for forpliktelser'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Avsetninger for forpliktelser','20','0','11000',''));
InsertRecord('accountgroups',array('groupname'),array('Bankinnskudd, kontanter o.l.'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Bankinnskudd, kontanter o.l.','10','0','9000',''));
InsertRecord('accountgroups',array('groupname'),array('Egenkapital'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Egenkapital','20','0','10000',''));
InsertRecord('accountgroups',array('groupname'),array('Energi, brensel o.l. vedr. pro'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Energi, brensel o.l. vedr. pro','30','1','19000',''));
InsertRecord('accountgroups',array('groupname'),array('Finansielle anleggsmidler'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Finansielle anleggsmidler','10','0','4000',''));
InsertRecord('accountgroups',array('groupname'),array('Finansinntekter og -kostnader,'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Finansinntekter og -kostnader,','30','1','22000',''));
InsertRecord('accountgroups',array('groupname'),array('Fond for vurderingsforskjeller'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Fond for vurderingsforskjeller','40','1','23000',''));
InsertRecord('accountgroups',array('groupname'),array('Fordringer'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Fordringer','10','0','6000',''));
InsertRecord('accountgroups',array('groupname'),array('Immaterielle eiendeler'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Immaterielle eiendeler','10','0','1000',''));
InsertRecord('accountgroups',array('groupname'),array('Investeringer'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Investeringer','10','0','8000',''));
InsertRecord('accountgroups',array('groupname'),array('Konsernbidrag'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Konsernbidrag','40','1','25000',''));
InsertRecord('accountgroups',array('groupname'),array('Kortsiktig gjeld'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kortsiktig gjeld','20','0','13000',''));
InsertRecord('accountgroups',array('groupname'),array('Kostnader. vedr. lokaler'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Kostnader. vedr. lokaler','30','1','20000',''));
InsertRecord('accountgroups',array('groupname'),array('L'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('L','30','1','17000',''));
InsertRecord('accountgroups',array('groupname'),array('Leie av maskiner, inventar o.l'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Leie av maskiner, inventar o.l','30','1','21000',''));
InsertRecord('accountgroups',array('groupname'),array('Salgs- og driftsinntekter'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Salgs- og driftsinntekter','30','1','14000',''));
InsertRecord('accountgroups',array('groupname'),array('Transportmidler, inventar, mas'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Transportmidler, inventar, mas','10','0','3000',''));
InsertRecord('accountgroups',array('groupname'),array('Utbytte'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Utbytte','40','1','24000',''));
InsertRecord('accountgroups',array('groupname'),array('Varekostnad'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Varekostnad','30','1','15000',''));
InsertRecord('accountgroups',array('groupname'),array('Varer'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Varer','10','0','5000',''));
InsertRecord('accountgroups',array('groupname'),array('Varer for videresalg'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Varer for videresalg','30','1','16000',''));
InsertRecord('accountgroups',array('groupname'),array('Varige driftsmidler'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('Varige driftsmidler','10','0','2000',''));
InsertRecord('chartmaster',array('accountcaode'),array('1000'),array('accountcode','accountname','group_'),array('1000','Forskning og utvikling','Immaterielle eiendeler'));
InsertRecord('chartmaster',array('accountcaode'),array('1030'),array('accountcode','accountname','group_'),array('1030','Patenter','Immaterielle eiendeler'));
InsertRecord('chartmaster',array('accountcaode'),array('1040'),array('accountcode','accountname','group_'),array('1040','Lisenser','Immaterielle eiendeler'));
InsertRecord('chartmaster',array('accountcaode'),array('1050'),array('accountcode','accountname','group_'),array('1050','Varemerker','Immaterielle eiendeler'));
InsertRecord('chartmaster',array('accountcaode'),array('1060'),array('accountcode','accountname','group_'),array('1060','Andre rettigheter','Immaterielle eiendeler'));
InsertRecord('chartmaster',array('accountcaode'),array('1070'),array('accountcode','accountname','group_'),array('1070','Utsatt skattefordel','Immaterielle eiendeler'));
InsertRecord('chartmaster',array('accountcaode'),array('1080'),array('accountcode','accountname','group_'),array('1080','Goodwill','Immaterielle eiendeler'));
InsertRecord('chartmaster',array('accountcaode'),array('1100'),array('accountcode','accountname','group_'),array('1100','Bygninger','Varige driftsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1120'),array('accountcode','accountname','group_'),array('1120','Bygningsmessige anlegg','Varige driftsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1140'),array('accountcode','accountname','group_'),array('1140','Jord- og skogbrukseiendommer','Varige driftsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1150'),array('accountcode','accountname','group_'),array('1150','Tomter og andre grunnarealer','Varige driftsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1200'),array('accountcode','accountname','group_'),array('1200','Maskiner og anlegg','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1210'),array('accountcode','accountname','group_'),array('1210','Maskiner og anlegg under utf','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1230'),array('accountcode','accountname','group_'),array('1230','Biler','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1240'),array('accountcode','accountname','group_'),array('1240','Andre transportmidler','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1250'),array('accountcode','accountname','group_'),array('1250','Inventar','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1260'),array('accountcode','accountname','group_'),array('1260','Fast bygningsinventar med annen avskrivning','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1270'),array('accountcode','accountname','group_'),array('1270','Verkt','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1280'),array('accountcode','accountname','group_'),array('1280','Kontormaskiner','Transportmidler, inventar, mas'));
InsertRecord('chartmaster',array('accountcaode'),array('1300'),array('accountcode','accountname','group_'),array('1300','Investeringer i datterselskaper','Finansielle anleggsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1350'),array('accountcode','accountname','group_'),array('1350','Investeringer i aksjer og andeler','Finansielle anleggsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1360'),array('accountcode','accountname','group_'),array('1360','Obligasjoner','Finansielle anleggsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1370'),array('accountcode','accountname','group_'),array('1370','Fordringer p','Finansielle anleggsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1380'),array('accountcode','accountname','group_'),array('1380','Fordringer p','Finansielle anleggsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1390'),array('accountcode','accountname','group_'),array('1390','Andre langsiktige fordringer','Finansielle anleggsmidler'));
InsertRecord('chartmaster',array('accountcaode'),array('1400'),array('accountcode','accountname','group_'),array('1400','R','Varer'));
InsertRecord('chartmaster',array('accountcaode'),array('1420'),array('accountcode','accountname','group_'),array('1420','Varer under tilvirkning','Varer'));
InsertRecord('chartmaster',array('accountcaode'),array('1440'),array('accountcode','accountname','group_'),array('1440','Ferdige egentilvirkede varer','Varer'));
InsertRecord('chartmaster',array('accountcaode'),array('1460'),array('accountcode','accountname','group_'),array('1460','Innkj','Varer'));
InsertRecord('chartmaster',array('accountcaode'),array('1480'),array('accountcode','accountname','group_'),array('1480','Forskuddsbetaling til leverand','Varer'));
InsertRecord('chartmaster',array('accountcaode'),array('1500'),array('accountcode','accountname','group_'),array('1500','Kundefordringer','Fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1520'),array('accountcode','accountname','group_'),array('1520','Andre kortsiktige fordringer','Fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1530'),array('accountcode','accountname','group_'),array('1530','Opptjente, ikke fakturerte driftsinntekter','Fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1570'),array('accountcode','accountname','group_'),array('1570','Andre kortsiktige fordringer','Fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1580'),array('accountcode','accountname','group_'),array('1580','Avsetning tap p','Fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1700'),array('accountcode','accountname','group_'),array('1700','Forskuddsbetalt leie','Andre fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1710'),array('accountcode','accountname','group_'),array('1710','Forskuddsbetalt rente','Andre fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1720'),array('accountcode','accountname','group_'),array('1720','Forskuddsbetalt l','Andre fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1750'),array('accountcode','accountname','group_'),array('1750','P','Andre fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1760'),array('accountcode','accountname','group_'),array('1760','P','Andre fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1780'),array('accountcode','accountname','group_'),array('1780','Krav p','Andre fordringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1800'),array('accountcode','accountname','group_'),array('1800','Aksjer & andeler i foretak i samme kons.','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1810'),array('accountcode','accountname','group_'),array('1810','Markesdbaserte aksjer','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1820'),array('accountcode','accountname','group_'),array('1820','Andre aksjer','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1830'),array('accountcode','accountname','group_'),array('1830','Markedsbaserte obligasjoner','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1840'),array('accountcode','accountname','group_'),array('1840','Andre obligasjoner','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1850'),array('accountcode','accountname','group_'),array('1850','Markedsbaserte sertifikater','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1860'),array('accountcode','accountname','group_'),array('1860','Andre sertifikater','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1880'),array('accountcode','accountname','group_'),array('1880','Andre finansielle instrumenter','Investeringer'));
InsertRecord('chartmaster',array('accountcaode'),array('1900'),array('accountcode','accountname','group_'),array('1900','Kontanter','Bankinnskudd, kontanter o.l.'));
InsertRecord('chartmaster',array('accountcaode'),array('1910'),array('accountcode','accountname','group_'),array('1910','Kasse','Bankinnskudd, kontanter o.l.'));
InsertRecord('chartmaster',array('accountcaode'),array('1920'),array('accountcode','accountname','group_'),array('1920','Bankinnskudd','Bankinnskudd, kontanter o.l.'));
InsertRecord('chartmaster',array('accountcaode'),array('1950'),array('accountcode','accountname','group_'),array('1950','Bankinnskudd for skattetrekk','Bankinnskudd, kontanter o.l.'));
InsertRecord('chartmaster',array('accountcaode'),array('2000'),array('accountcode','accountname','group_'),array('2000','Aksjekapital','Egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2010'),array('accountcode','accountname','group_'),array('2010','Egne aksjer','Egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2020'),array('accountcode','accountname','group_'),array('2020','Overkursfond','Egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2040'),array('accountcode','accountname','group_'),array('2040','Fond for vurderingsforskjeller','Egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2050'),array('accountcode','accountname','group_'),array('2050','Annen egenkapital','Egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2080'),array('accountcode','accountname','group_'),array('2080','Udisponert overskudd','Egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2090'),array('accountcode','accountname','group_'),array('2090','Udekket tap','Egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('2100'),array('accountcode','accountname','group_'),array('2100','Pensjonsforpliktelser','Avsetninger for forpliktelser'));
InsertRecord('chartmaster',array('accountcaode'),array('2120'),array('accountcode','accountname','group_'),array('2120','Utsatt skatt','Avsetninger for forpliktelser'));
InsertRecord('chartmaster',array('accountcaode'),array('2140'),array('accountcode','accountname','group_'),array('2140','Avsetn. for garanti- & serviceforpl.','Avsetninger for forpliktelser'));
InsertRecord('chartmaster',array('accountcaode'),array('2180'),array('accountcode','accountname','group_'),array('2180','Andre avsetninger for forpiktelser','Avsetninger for forpliktelser'));
InsertRecord('chartmaster',array('accountcaode'),array('2200'),array('accountcode','accountname','group_'),array('2200','Konvertible l','Annen langsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2210'),array('accountcode','accountname','group_'),array('2210','Obligsjonsl','Annen langsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2220'),array('accountcode','accountname','group_'),array('2220','Gjeld til kredittinstitusjoner','Annen langsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2240'),array('accountcode','accountname','group_'),array('2240','Pantel','Annen langsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2260'),array('accountcode','accountname','group_'),array('2260','Gjeld til selskap i samme konsern','Annen langsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2270'),array('accountcode','accountname','group_'),array('2270','Andre valutal','Annen langsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2300'),array('accountcode','accountname','group_'),array('2300','Konvertible l','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2320'),array('accountcode','accountname','group_'),array('2320','Sertifikatl','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2340'),array('accountcode','accountname','group_'),array('2340','Andre valutal','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2360'),array('accountcode','accountname','group_'),array('2360','Byggel','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2380'),array('accountcode','accountname','group_'),array('2380','Kassakreditt','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2400'),array('accountcode','accountname','group_'),array('2400','Leverand','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2500'),array('accountcode','accountname','group_'),array('2500','Avsatt betalbar skatt','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2510'),array('accountcode','accountname','group_'),array('2510','Skattebetaling','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2600'),array('accountcode','accountname','group_'),array('2600','Skattetrekk','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2620'),array('accountcode','accountname','group_'),array('2620','P','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2630'),array('accountcode','accountname','group_'),array('2630','Bidragstrekk','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2640'),array('accountcode','accountname','group_'),array('2640','Trygdetrekk','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2650'),array('accountcode','accountname','group_'),array('2650','Forsikringstrekk','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2660'),array('accountcode','accountname','group_'),array('2660','Fagforeningstrekk','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2690'),array('accountcode','accountname','group_'),array('2690','Andre trekk','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2710'),array('accountcode','accountname','group_'),array('2710','Utg','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2715'),array('accountcode','accountname','group_'),array('2715','Utg','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2717'),array('accountcode','accountname','group_'),array('2717','Beregnet avgift utlandet','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2720'),array('accountcode','accountname','group_'),array('2720','Inng','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2725'),array('accountcode','accountname','group_'),array('2725','Inng','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2745'),array('accountcode','accountname','group_'),array('2745','Grunnlag 1 tjenester utlandet','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2746'),array('accountcode','accountname','group_'),array('2746','Grunnlag 2 tjenester utlandet','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2750'),array('accountcode','accountname','group_'),array('2750','Oppgj','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2770'),array('accountcode','accountname','group_'),array('2770','P','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2780'),array('accountcode','accountname','group_'),array('2780','Skyldig arbeidsgiveravgift','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2781'),array('accountcode','accountname','group_'),array('2781','Arb.giv.avg. p','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2800'),array('accountcode','accountname','group_'),array('2800','Avsatt utbytte','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2900'),array('accountcode','accountname','group_'),array('2900','Forskudd fra kunder','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2910'),array('accountcode','accountname','group_'),array('2910','Skyldig l','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2920'),array('accountcode','accountname','group_'),array('2920','Skyldig feriepenger','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2930'),array('accountcode','accountname','group_'),array('2930','Gjeld til ansatte og aksjon','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2950'),array('accountcode','accountname','group_'),array('2950','P','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('2960'),array('accountcode','accountname','group_'),array('2960','P','Kortsiktig gjeld'));
InsertRecord('chartmaster',array('accountcaode'),array('3010'),array('accountcode','accountname','group_'),array('3010','Salgsinntekter, 24% mva','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3019'),array('accountcode','accountname','group_'),array('3019','Frakt','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3020'),array('accountcode','accountname','group_'),array('3020','Salgsinntekter, 12% mva','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3060'),array('accountcode','accountname','group_'),array('3060','Uttak av varer','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3080'),array('accountcode','accountname','group_'),array('3080','Rabatter og andre salgsinntektsreduksjon','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3099'),array('accountcode','accountname','group_'),array('3099','Milj','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3110'),array('accountcode','accountname','group_'),array('3110','Salgsinntekter, avgiftsfrie','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3160'),array('accountcode','accountname','group_'),array('3160','Uttak av varer','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3180'),array('accountcode','accountname','group_'),array('3180','Rabatter og andre salgsinntektsreduksjon','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3300'),array('accountcode','accountname','group_'),array('3300','Spes. offent. avg. tilvirk./solgte varer','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3400'),array('accountcode','accountname','group_'),array('3400','Spes. offent. avg. tilvirk./solgte varer','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3440'),array('accountcode','accountname','group_'),array('3440','Spes. offentlige tilskudd for tjenester','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3500'),array('accountcode','accountname','group_'),array('3500','Uopptjente inntekter garanti','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3510'),array('accountcode','accountname','group_'),array('3510','Uopptjente inntekter service','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3600'),array('accountcode','accountname','group_'),array('3600','Leieinntekter fast eiendom','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3610'),array('accountcode','accountname','group_'),array('3610','Leieinntekter andre varige driftsmidler','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3620'),array('accountcode','accountname','group_'),array('3620','Andre leieinntekter','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3700'),array('accountcode','accountname','group_'),array('3700','Provisjonsinntekter','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3800'),array('accountcode','accountname','group_'),array('3800','Gevinst ved avgang av anleggsmidler','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('3900'),array('accountcode','accountname','group_'),array('3900','Andre driftsrelaterte inntekter','Salgs- og driftsinntekter'));
InsertRecord('chartmaster',array('accountcaode'),array('4010'),array('accountcode','accountname','group_'),array('4010','Innkj','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4020'),array('accountcode','accountname','group_'),array('4020','Innkj','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4060'),array('accountcode','accountname','group_'),array('4060','Innkj','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4070'),array('accountcode','accountname','group_'),array('4070','Frakt, toll og spedisjon','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4090'),array('accountcode','accountname','group_'),array('4090','Beholdningsendring','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4110'),array('accountcode','accountname','group_'),array('4110','Innkj','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4160'),array('accountcode','accountname','group_'),array('4160','Frakt, toll og spedisjon','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4170'),array('accountcode','accountname','group_'),array('4170','Frakt, toll og spedisjon, avgiftsfritt','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4180'),array('accountcode','accountname','group_'),array('4180','Innkj','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4190'),array('accountcode','accountname','group_'),array('4190','Beholdningsendring','Varekostnad'));
InsertRecord('chartmaster',array('accountcaode'),array('4310'),array('accountcode','accountname','group_'),array('4310','Innkj','Varer for videresalg'));
InsertRecord('chartmaster',array('accountcaode'),array('4320'),array('accountcode','accountname','group_'),array('4320','Innkj','Varer for videresalg'));
InsertRecord('chartmaster',array('accountcaode'),array('4360'),array('accountcode','accountname','group_'),array('4360','Frakt, toll m.m. vedr. innkj','Varer for videresalg'));
InsertRecord('chartmaster',array('accountcaode'),array('4370'),array('accountcode','accountname','group_'),array('4370','Rabatter m.m. vedr. innkj','Varer for videresalg'));
InsertRecord('chartmaster',array('accountcaode'),array('4380'),array('accountcode','accountname','group_'),array('4380','Varekostnad','Varer for videresalg'));
InsertRecord('chartmaster',array('accountcaode'),array('4390'),array('accountcode','accountname','group_'),array('4390','Beholdningsendring varer for videresalg','Varer for videresalg'));
InsertRecord('chartmaster',array('accountcaode'),array('5010'),array('accountcode','accountname','group_'),array('5010','Faste l','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5090'),array('accountcode','accountname','group_'),array('5090','Periodiseringskonto l','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5190'),array('accountcode','accountname','group_'),array('5190','P','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5210'),array('accountcode','accountname','group_'),array('5210','Fri bil','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5220'),array('accountcode','accountname','group_'),array('5220','Fri telefon','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5230'),array('accountcode','accountname','group_'),array('5230','Fri avis','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5240'),array('accountcode','accountname','group_'),array('5240','Fri losji og bolig','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5250'),array('accountcode','accountname','group_'),array('5250','Rentefordel','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5260'),array('accountcode','accountname','group_'),array('5260','Smusstillegg','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5280'),array('accountcode','accountname','group_'),array('5280','Andre fordeler i arbeidsforhold','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5291'),array('accountcode','accountname','group_'),array('5291','Motkonto for gruppe 52','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5330'),array('accountcode','accountname','group_'),array('5330','Godtgj. til styre- og bedriftsforsamling','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5410'),array('accountcode','accountname','group_'),array('5410','Arbeidsgiveravgift','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5411'),array('accountcode','accountname','group_'),array('5411','Arb.giv.avg. p','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5420'),array('accountcode','accountname','group_'),array('5420','Innberetningspliktige pensjonskostnader','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5430'),array('accountcode','accountname','group_'),array('5430','Premie pensjonsordning','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5500'),array('accountcode','accountname','group_'),array('5500','Andre kostnadsgodtgj','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5510'),array('accountcode','accountname','group_'),array('5510','Overtidsmat etter regning','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5520'),array('accountcode','accountname','group_'),array('5520','Kantinekostnader','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5800'),array('accountcode','accountname','group_'),array('5800','Refusjon av sykepenger','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5820'),array('accountcode','accountname','group_'),array('5820','Refusjon av arbeidsgiveravgift','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5920'),array('accountcode','accountname','group_'),array('5920','Yrkesskadeforsikring','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5930'),array('accountcode','accountname','group_'),array('5930','Andre ikke arb.giv.avg.pliktige forsikr.','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5950'),array('accountcode','accountname','group_'),array('5950','Personalforsikring','L'));
InsertRecord('chartmaster',array('accountcaode'),array('5960'),array('accountcode','accountname','group_'),array('5960','Gaver til ansatte','L'));
InsertRecord('chartmaster',array('accountcaode'),array('6000'),array('accountcode','accountname','group_'),array('6000','Avskrivning p','Andre driftskostnader, av- og'));
InsertRecord('chartmaster',array('accountcaode'),array('6010'),array('accountcode','accountname','group_'),array('6010','Avskrivning p','Andre driftskostnader, av- og'));
InsertRecord('chartmaster',array('accountcaode'),array('6020'),array('accountcode','accountname','group_'),array('6020','Avskrivning p','Andre driftskostnader, av- og'));
InsertRecord('chartmaster',array('accountcaode'),array('6050'),array('accountcode','accountname','group_'),array('6050','Nedskr. varige driftsmidl. & imat. eiend','Andre driftskostnader, av- og'));
InsertRecord('chartmaster',array('accountcaode'),array('6100'),array('accountcode','accountname','group_'),array('6100','Frakter, transportkostnader og forsikring','Andre driftskostnader, av- og'));
InsertRecord('chartmaster',array('accountcaode'),array('6110'),array('accountcode','accountname','group_'),array('6110','Toll og spedisjonskostnader ved forsend','Andre driftskostnader, av- og'));
InsertRecord('chartmaster',array('accountcaode'),array('6200'),array('accountcode','accountname','group_'),array('6200','Elektrisitet','Energi, brensel o.l. vedr. pro'));
InsertRecord('chartmaster',array('accountcaode'),array('6260'),array('accountcode','accountname','group_'),array('6260','Vann','Energi, brensel o.l. vedr. pro'));
InsertRecord('chartmaster',array('accountcaode'),array('6300'),array('accountcode','accountname','group_'),array('6300','Leie lokaler','Kostnader. vedr. lokaler'));
InsertRecord('chartmaster',array('accountcaode'),array('6320'),array('accountcode','accountname','group_'),array('6320','Renovasjon, vann, avl','Kostnader. vedr. lokaler'));
InsertRecord('chartmaster',array('accountcaode'),array('6340'),array('accountcode','accountname','group_'),array('6340','Lys, varme','Kostnader. vedr. lokaler'));
InsertRecord('chartmaster',array('accountcaode'),array('6360'),array('accountcode','accountname','group_'),array('6360','Renhold','Kostnader. vedr. lokaler'));
InsertRecord('chartmaster',array('accountcaode'),array('6400'),array('accountcode','accountname','group_'),array('6400','Leie av driftsmidler','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6430'),array('accountcode','accountname','group_'),array('6430','Leie andre kontormaskiner','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6540'),array('accountcode','accountname','group_'),array('6540','Inventar','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6550'),array('accountcode','accountname','group_'),array('6550','Driftsmaterialer','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6560'),array('accountcode','accountname','group_'),array('6560','Rekvisita','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6570'),array('accountcode','accountname','group_'),array('6570','Arbeidskl','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6600'),array('accountcode','accountname','group_'),array('6600','Reparasjoner og vedlikehold bygninger','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6620'),array('accountcode','accountname','group_'),array('6620','Reparasjoner og vedlikehold utstyr','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6700'),array('accountcode','accountname','group_'),array('6700','Revisjonshonorar','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6720'),array('accountcode','accountname','group_'),array('6720','Honorar for','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6750'),array('accountcode','accountname','group_'),array('6750','Honorar regnskapsf','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6800'),array('accountcode','accountname','group_'),array('6800','Kontorrekvisita','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6820'),array('accountcode','accountname','group_'),array('6820','Trykksaker','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6840'),array('accountcode','accountname','group_'),array('6840','Aviser, tidsskrifter, b','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6860'),array('accountcode','accountname','group_'),array('6860','M','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6900'),array('accountcode','accountname','group_'),array('6900','Telefon','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('6940'),array('accountcode','accountname','group_'),array('6940','Porto','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7000'),array('accountcode','accountname','group_'),array('7000','Drivstoff','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7020'),array('accountcode','accountname','group_'),array('7020','Vedlikehold','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7040'),array('accountcode','accountname','group_'),array('7040','Forsikringer','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7100'),array('accountcode','accountname','group_'),array('7100','Bilgodtgj','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7105'),array('accountcode','accountname','group_'),array('7105','','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7130'),array('accountcode','accountname','group_'),array('7130','Reisekostnader, oppgavepliktige','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7140'),array('accountcode','accountname','group_'),array('7140','Reisekostnader, ikke oppgavepliktig','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7150'),array('accountcode','accountname','group_'),array('7150','Diettkostnader, oppgaveplikig','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7160'),array('accountcode','accountname','group_'),array('7160','Diettkostnader, ikke oppgavepliktig','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7200'),array('accountcode','accountname','group_'),array('7200','Provisjonskostnader, oppgavepliktige','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7210'),array('accountcode','accountname','group_'),array('7210','Provisjonskostnader, ikke oppgavepliktig','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7300'),array('accountcode','accountname','group_'),array('7300','Salgskostnader','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7320'),array('accountcode','accountname','group_'),array('7320','Reklamekostnader','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7350'),array('accountcode','accountname','group_'),array('7350','Representasjon, fradragsberettiget','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7360'),array('accountcode','accountname','group_'),array('7360','Representasjon, ikke fradragsberettiget','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7400'),array('accountcode','accountname','group_'),array('7400','Kontingenter og gaver','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7500'),array('accountcode','accountname','group_'),array('7500','Forsikringspremier','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7550'),array('accountcode','accountname','group_'),array('7550','Garanti- og servicekostnader','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7600'),array('accountcode','accountname','group_'),array('7600','Lisenesavgifter og royalties','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7700'),array('accountcode','accountname','group_'),array('7700','Styre- og bedriftsforsamlingsm','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7710'),array('accountcode','accountname','group_'),array('7710','Generalforsamling','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7730'),array('accountcode','accountname','group_'),array('7730','Kostnader ved egne aksjer','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7750'),array('accountcode','accountname','group_'),array('7750','Eiendoms- og festeavgift','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7770'),array('accountcode','accountname','group_'),array('7770','Bank og kortgebyrer','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7800'),array('accountcode','accountname','group_'),array('7800','Tap ved avgang anleggsmidler','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7820'),array('accountcode','accountname','group_'),array('7820','Innkommet p','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7830'),array('accountcode','accountname','group_'),array('7830','Tap p','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7850'),array('accountcode','accountname','group_'),array('7850','Tap pga. brannskade','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7860'),array('accountcode','accountname','group_'),array('7860','Tap p','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7900'),array('accountcode','accountname','group_'),array('7900','Beholdningsendring anlegg under utf','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('7990'),array('accountcode','accountname','group_'),array('7990','Andre driftskostnader','Leie av maskiner, inventar o.l'));
InsertRecord('chartmaster',array('accountcaode'),array('8000'),array('accountcode','accountname','group_'),array('8000','Inntekter p','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8040'),array('accountcode','accountname','group_'),array('8040','Renteinntekter, skattefrie','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8050'),array('accountcode','accountname','group_'),array('8050','Annen renteinntekt','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8060'),array('accountcode','accountname','group_'),array('8060','Purregebyr, kunder','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8070'),array('accountcode','accountname','group_'),array('8070','Renteinntekter, kunder','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8080'),array('accountcode','accountname','group_'),array('8080','Agio gevinst','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8090'),array('accountcode','accountname','group_'),array('8090','Andre finansinntekter','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8100'),array('accountcode','accountname','group_'),array('8100','Verdired. av markedsbas.finans. oml','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8110'),array('accountcode','accountname','group_'),array('8110','Nedskrivn. av andre finansielle oml','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8120'),array('accountcode','accountname','group_'),array('8120','Nedskrivning av finansielle anleggsmidl.','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8140'),array('accountcode','accountname','group_'),array('8140','Rentekostnader, ikke fradragsberettigede','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8150'),array('accountcode','accountname','group_'),array('8150','Annen rentekostnad','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8160'),array('accountcode','accountname','group_'),array('8160','Purregebyr. leverand','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8180'),array('accountcode','accountname','group_'),array('8180','Agio tap','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8300'),array('accountcode','accountname','group_'),array('8300','Betalbar skatt','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8320'),array('accountcode','accountname','group_'),array('8320','Utsatt skatt','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8350'),array('accountcode','accountname','group_'),array('8350','Skattekostnad','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8600'),array('accountcode','accountname','group_'),array('8600','Betalbar skatt','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8620'),array('accountcode','accountname','group_'),array('8620','Utsatt skatt','Finansinntekter og -kostnader,'));
InsertRecord('chartmaster',array('accountcaode'),array('8800'),array('accountcode','accountname','group_'),array('8800','','Fond for vurderingsforskjeller'));
InsertRecord('chartmaster',array('accountcaode'),array('8900'),array('accountcode','accountname','group_'),array('8900','Overf','Fond for vurderingsforskjeller'));
InsertRecord('chartmaster',array('accountcaode'),array('8910'),array('accountcode','accountname','group_'),array('8910','Overf','Annen egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('8920'),array('accountcode','accountname','group_'),array('8920','Avsatt utbytte/renter p','Utbytte'));
InsertRecord('chartmaster',array('accountcaode'),array('8930'),array('accountcode','accountname','group_'),array('8930','Konsernbidrag','Konsernbidrag'));
InsertRecord('chartmaster',array('accountcaode'),array('8940'),array('accountcode','accountname','group_'),array('8940','Aksjon','Annen egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('8950'),array('accountcode','accountname','group_'),array('8950','Fondsemisjon','Annen egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('8960'),array('accountcode','accountname','group_'),array('8960','Overf','Annen egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('8980'),array('accountcode','accountname','group_'),array('8980','Avsatt til fri egenkapital','Annen egenkapital'));
InsertRecord('chartmaster',array('accountcaode'),array('8990'),array('accountcode','accountname','group_'),array('8990','Udekket tap','Annen egenkapital'));
?>