<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Tillg'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Skulder'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Inkomst'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Kostnad'));
InsertRecord('accountgroups',array('groupname'),array('Avs'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('10','Avs','20','0','18000','',''));
InsertRecord('accountgroups',array('groupname'),array('Byggnader och mark'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('20','Byggnader och mark','10','0','2000','',''));
InsertRecord('accountgroups',array('groupname'),array('Eget kapital'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('30','Eget kapital','10','0','11000','',''));
InsertRecord('accountgroups',array('groupname'),array('F'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('40','F','10','0','8000','',''));
InsertRecord('accountgroups',array('groupname'),array('Finansiella anl'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('50','Finansiella anl','10','0','4000','',''));
InsertRecord('accountgroups',array('groupname'),array('Immateriella anl'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('60','Immateriella anl','20','0','1000','',''));
InsertRecord('accountgroups',array('groupname'),array('Kassa och Bank'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('70','Kassa och Bank','10','0','10000','',''));
InsertRecord('accountgroups',array('groupname'),array('Kortfristiga placeringar'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('80','Kortfristiga placeringar','10','0','9000','',''));
InsertRecord('accountgroups',array('groupname'),array('Kortfristiga skulder till kred'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('90','Kortfristiga skulder till kred','20','0','20000','',''));
InsertRecord('accountgroups',array('groupname'),array('Kundfordringar'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('100','Kundfordringar','10','0','6000','',''));
InsertRecord('accountgroups',array('groupname'),array('L'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('110','L','20','0','19000','',''));
InsertRecord('accountgroups',array('groupname'),array('Lager och p'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('120','Lager och p','10','0','5000','',''));
InsertRecord('accountgroups',array('groupname'),array('Maskiner och inventarier'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('130','Maskiner och inventarier','10','0','3000','',''));
InsertRecord('accountgroups',array('groupname'),array('Moms och s'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('140','Moms och s','20','0','22000','',''));
InsertRecord('accountgroups',array('groupname'),array('Obeskattade reserver'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('150','Obeskattade reserver','20','0','12000','',''));
InsertRecord('accountgroups',array('groupname'),array('Periodiseringsfond vid 1995'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('160','Periodiseringsfond vid 1995','20','0','13000','',''));
InsertRecord('accountgroups',array('groupname'),array('Periodiseringsfond vid 1996'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('170','Periodiseringsfond vid 1996','20','0','14000','',''));
InsertRecord('accountgroups',array('groupname'),array('Periodiseringsfond vid 1997'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('180','Periodiseringsfond vid 1997','20','0','15000','',''));
InsertRecord('accountgroups',array('groupname'),array('Periodiseringsfond vid 1998'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('190','Periodiseringsfond vid 1998','20','0','16000','',''));
InsertRecord('accountgroups',array('groupname'),array('Periodiseringsfond vid 1999'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('200','Periodiseringsfond vid 1999','20','0','17000','',''));
InsertRecord('accountgroups',array('groupname'),array('Personalens skatter, avgifter'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('210','Personalens skatter, avgifter','20','0','23000','',''));
InsertRecord('accountgroups',array('groupname'),array('Skatteskulder'),array('groupcode','groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname','parentgroupcode'),array('220','Skatteskulder','20','0','21000','',''));
InsertRecord('chartmaster',array('accountcode'),array('1010'),array('accountcode','accountname','group_'),array('1010','Balanserade utgifter','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1011'),array('accountcode','accountname','group_'),array('1011','Balanserade utgifter f','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1012'),array('accountcode','accountname','group_'),array('1012','Balanserade utgifter f','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1019'),array('accountcode','accountname','group_'),array('1019','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1020'),array('accountcode','accountname','group_'),array('1020','Koncessioner m m','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1029'),array('accountcode','accountname','group_'),array('1029','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1030'),array('accountcode','accountname','group_'),array('1030','Patent','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1039'),array('accountcode','accountname','group_'),array('1039','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1040'),array('accountcode','accountname','group_'),array('1040','Licenser','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1049'),array('accountcode','accountname','group_'),array('1049','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1050'),array('accountcode','accountname','group_'),array('1050','Varum','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1059'),array('accountcode','accountname','group_'),array('1059','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1060'),array('accountcode','accountname','group_'),array('1060','Hyresr','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1069'),array('accountcode','accountname','group_'),array('1069','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1070'),array('accountcode','accountname','group_'),array('1070','Goodwill','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1079'),array('accountcode','accountname','group_'),array('1079','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1080'),array('accountcode','accountname','group_'),array('1080','P','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1081'),array('accountcode','accountname','group_'),array('1081','P','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1088'),array('accountcode','accountname','group_'),array('1088','F','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1090'),array('accountcode','accountname','group_'),array('1090','','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1099'),array('accountcode','accountname','group_'),array('1099','Ackumulerade avskrivningar p','Immateriella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1110'),array('accountcode','accountname','group_'),array('1110','Byggnader','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1111'),array('accountcode','accountname','group_'),array('1111','Byggnader p','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1112'),array('accountcode','accountname','group_'),array('1112','Byggnader p','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1119'),array('accountcode','accountname','group_'),array('1119','Ackumulerade avskrivningar p','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1130'),array('accountcode','accountname','group_'),array('1130','Mark','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1140'),array('accountcode','accountname','group_'),array('1140','Tomter och obebyggda markomr','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1150'),array('accountcode','accountname','group_'),array('1150','Markanl','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1159'),array('accountcode','accountname','group_'),array('1159','Ackumulerade avskrivningar p','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1180'),array('accountcode','accountname','group_'),array('1180','P','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1181'),array('accountcode','accountname','group_'),array('1181','P','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1182'),array('accountcode','accountname','group_'),array('1182','P','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1183'),array('accountcode','accountname','group_'),array('1183','P','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1188'),array('accountcode','accountname','group_'),array('1188','F','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1190'),array('accountcode','accountname','group_'),array('1190','','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1199'),array('accountcode','accountname','group_'),array('1199','Ackumulerade avskrivningar p','Byggnader och mark'));
InsertRecord('chartmaster',array('accountcode'),array('1200'),array('accountcode','accountname','group_'),array('1200','Maskiner och inventarier (gruppkonto)','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1209'),array('accountcode','accountname','group_'),array('1209','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1210'),array('accountcode','accountname','group_'),array('1210','Maskiner och andra tekniska anl','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1211'),array('accountcode','accountname','group_'),array('1211','Maskiner','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1212'),array('accountcode','accountname','group_'),array('1212','Byggnadsinventarier','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1213'),array('accountcode','accountname','group_'),array('1213','Andra tekniska anl','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1219'),array('accountcode','accountname','group_'),array('1219','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1220'),array('accountcode','accountname','group_'),array('1220','Inventarier och verktyg','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1229'),array('accountcode','accountname','group_'),array('1229','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1230'),array('accountcode','accountname','group_'),array('1230','Installationer','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1231'),array('accountcode','accountname','group_'),array('1231','Installationer p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1232'),array('accountcode','accountname','group_'),array('1232','Installationer p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1233'),array('accountcode','accountname','group_'),array('1233','F','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1239'),array('accountcode','accountname','group_'),array('1239','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1240'),array('accountcode','accountname','group_'),array('1240','Bilar och andra transportmedel','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1249'),array('accountcode','accountname','group_'),array('1249','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1250'),array('accountcode','accountname','group_'),array('1250','Datorer','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1251'),array('accountcode','accountname','group_'),array('1251','Datorer - f','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1257'),array('accountcode','accountname','group_'),array('1257','Datorer - personal','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1259'),array('accountcode','accountname','group_'),array('1259','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1260'),array('accountcode','accountname','group_'),array('1260','Leasingavtal','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1269'),array('accountcode','accountname','group_'),array('1269','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1280'),array('accountcode','accountname','group_'),array('1280','P','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1281'),array('accountcode','accountname','group_'),array('1281','P','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1288'),array('accountcode','accountname','group_'),array('1288','F','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1290'),array('accountcode','accountname','group_'),array('1290','','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1291'),array('accountcode','accountname','group_'),array('1291','Konst och liknande tillg','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1292'),array('accountcode','accountname','group_'),array('1292','Inventarier i annans fastighet','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1299'),array('accountcode','accountname','group_'),array('1299','Ackumulerade avskrivningar p','Maskiner och inventarier'));
InsertRecord('chartmaster',array('accountcode'),array('1310'),array('accountcode','accountname','group_'),array('1310','Aktier och andelar i koncernf','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1311'),array('accountcode','accountname','group_'),array('1311','Aktier och andelar i svenska dotterf','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1312'),array('accountcode','accountname','group_'),array('1312','Aktier och andelar i utl','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1313'),array('accountcode','accountname','group_'),array('1313','Aktier och andelar i andra svenska koncernf','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1314'),array('accountcode','accountname','group_'),array('1314','Aktier och andelar i andra utl','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1319'),array('accountcode','accountname','group_'),array('1319','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1320'),array('accountcode','accountname','group_'),array('1320','L','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1321'),array('accountcode','accountname','group_'),array('1321','Fordringar hos moderf','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1322'),array('accountcode','accountname','group_'),array('1322','Fordringar hos dotterf','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1323'),array('accountcode','accountname','group_'),array('1323','Fordringar hos andra koncernf','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1329'),array('accountcode','accountname','group_'),array('1329','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1330'),array('accountcode','accountname','group_'),array('1330','Aktier och andelar i intressef','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1339'),array('accountcode','accountname','group_'),array('1339','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1340'),array('accountcode','accountname','group_'),array('1340','L','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1349'),array('accountcode','accountname','group_'),array('1349','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1350'),array('accountcode','accountname','group_'),array('1350','Aktier, andelar och v','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1351'),array('accountcode','accountname','group_'),array('1351','Aktier i b','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1352'),array('accountcode','accountname','group_'),array('1352','Andra aktier och andelar','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1353'),array('accountcode','accountname','group_'),array('1353','Andelar i bostadsr','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1354'),array('accountcode','accountname','group_'),array('1354','Obligationer','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1359'),array('accountcode','accountname','group_'),array('1359','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1380'),array('accountcode','accountname','group_'),array('1380','Andra l','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1381'),array('accountcode','accountname','group_'),array('1381','Reversfordringar','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1382'),array('accountcode','accountname','group_'),array('1382','Fordringar hos anst','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1383'),array('accountcode','accountname','group_'),array('1383','L','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1384'),array('accountcode','accountname','group_'),array('1384','L','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1385'),array('accountcode','accountname','group_'),array('1385','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1386'),array('accountcode','accountname','group_'),array('1386','F','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1387'),array('accountcode','accountname','group_'),array('1387','L','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1388'),array('accountcode','accountname','group_'),array('1388','Olika l','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1389'),array('accountcode','accountname','group_'),array('1389','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1390'),array('accountcode','accountname','group_'),array('1390','V','Finansiella anl'));
InsertRecord('chartmaster',array('accountcode'),array('1400'),array('accountcode','accountname','group_'),array('1400','Lager (gruppkonto)','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1401'),array('accountcode','accountname','group_'),array('1401','Inneliggande lager','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1402'),array('accountcode','accountname','group_'),array('1402','Varor p','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1403'),array('accountcode','accountname','group_'),array('1403','Konsignationslager','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1404'),array('accountcode','accountname','group_'),array('1404','Lager av v','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1409'),array('accountcode','accountname','group_'),array('1409','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1410'),array('accountcode','accountname','group_'),array('1410','Lager av r','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1419'),array('accountcode','accountname','group_'),array('1419','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1420'),array('accountcode','accountname','group_'),array('1420','Lager av tillsatsmaterial och f','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1429'),array('accountcode','accountname','group_'),array('1429','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1430'),array('accountcode','accountname','group_'),array('1430','Lager av halvfabrikat','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1431'),array('accountcode','accountname','group_'),array('1431','Lager av k','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1432'),array('accountcode','accountname','group_'),array('1432','Lager av egentillverkde halvfabrikat','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1439'),array('accountcode','accountname','group_'),array('1439','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1440'),array('accountcode','accountname','group_'),array('1440','Produkter i arbete - (PIA)','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1449'),array('accountcode','accountname','group_'),array('1449','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1450'),array('accountcode','accountname','group_'),array('1450','Lager av f','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1459'),array('accountcode','accountname','group_'),array('1459','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1460'),array('accountcode','accountname','group_'),array('1460','Lager av handelsvaror - Varulager','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1469'),array('accountcode','accountname','group_'),array('1469','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1470'),array('accountcode','accountname','group_'),array('1470','P','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1471'),array('accountcode','accountname','group_'),array('1471','P','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1472'),array('accountcode','accountname','group_'),array('1472','Oms','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1478'),array('accountcode','accountname','group_'),array('1478','P','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1479'),array('accountcode','accountname','group_'),array('1479','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1480'),array('accountcode','accountname','group_'),array('1480','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1481'),array('accountcode','accountname','group_'),array('1481','Remburs','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1489'),array('accountcode','accountname','group_'),array('1489','','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1490'),array('accountcode','accountname','group_'),array('1490','F','Lager och p'));
InsertRecord('chartmaster',array('accountcode'),array('1500'),array('accountcode','accountname','group_'),array('1500','Kundfordringar (gruppkonto)','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1510'),array('accountcode','accountname','group_'),array('1510','Kundfordringar','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1512'),array('accountcode','accountname','group_'),array('1512','Bel','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1515'),array('accountcode','accountname','group_'),array('1515','Os','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1516'),array('accountcode','accountname','group_'),array('1516','Tvistiga kundfordringar','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1518'),array('accountcode','accountname','group_'),array('1518','Ej reskontraf','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1519'),array('accountcode','accountname','group_'),array('1519','V','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1520'),array('accountcode','accountname','group_'),array('1520','V','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1525'),array('accountcode','accountname','group_'),array('1525','Os','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1529'),array('accountcode','accountname','group_'),array('1529','V','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1530'),array('accountcode','accountname','group_'),array('1530','Kontraktsfordringar','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1540'),array('accountcode','accountname','group_'),array('1540','Bel','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1541'),array('accountcode','accountname','group_'),array('1541','Bel','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1545'),array('accountcode','accountname','group_'),array('1545','Os','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1550'),array('accountcode','accountname','group_'),array('1550','Konsignationsfordringar','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1560'),array('accountcode','accountname','group_'),array('1560','Kundfordringar hos koncernf','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1561'),array('accountcode','accountname','group_'),array('1561','Kundfordringar hos moderf','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1562'),array('accountcode','accountname','group_'),array('1562','Kundfordringar hos dotternf','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1563'),array('accountcode','accountname','group_'),array('1563','Kundfordringar hos andra koncernf','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1569'),array('accountcode','accountname','group_'),array('1569','V','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1570'),array('accountcode','accountname','group_'),array('1570','Kundfordringar hos intressef','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1575'),array('accountcode','accountname','group_'),array('1575','Os','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1579'),array('accountcode','accountname','group_'),array('1579','V','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1580'),array('accountcode','accountname','group_'),array('1580','Kontokort och kuponger','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1590'),array('accountcode','accountname','group_'),array('1590','V','Kundfordringar'));
InsertRecord('chartmaster',array('accountcode'),array('1600'),array('accountcode','accountname','group_'),array('1600','',''));
InsertRecord('chartmaster',array('accountcode'),array('1610'),array('accountcode','accountname','group_'),array('1610','Fordringar hos anst',''));
InsertRecord('chartmaster',array('accountcode'),array('1611'),array('accountcode','accountname','group_'),array('1611','Resef',''));
InsertRecord('chartmaster',array('accountcode'),array('1612'),array('accountcode','accountname','group_'),array('1612','Kassaf',''));
InsertRecord('chartmaster',array('accountcode'),array('1613'),array('accountcode','accountname','group_'),array('1613','',''));
InsertRecord('chartmaster',array('accountcode'),array('1614'),array('accountcode','accountname','group_'),array('1614','Tillf',''));
InsertRecord('chartmaster',array('accountcode'),array('1619'),array('accountcode','accountname','group_'),array('1619','',''));
InsertRecord('chartmaster',array('accountcode'),array('1630'),array('accountcode','accountname','group_'),array('1630','Avr',''));
InsertRecord('chartmaster',array('accountcode'),array('1640'),array('accountcode','accountname','group_'),array('1640','Skattefordringar',''));
InsertRecord('chartmaster',array('accountcode'),array('1650'),array('accountcode','accountname','group_'),array('1650','Momsfordringar',''));
InsertRecord('chartmaster',array('accountcode'),array('1660'),array('accountcode','accountname','group_'),array('1660','Fordringar hos koncernf',''));
InsertRecord('chartmaster',array('accountcode'),array('1661'),array('accountcode','accountname','group_'),array('1661','Fordringar hos moderf',''));
InsertRecord('chartmaster',array('accountcode'),array('1662'),array('accountcode','accountname','group_'),array('1662','Fordringar hos dotterf',''));
InsertRecord('chartmaster',array('accountcode'),array('1663'),array('accountcode','accountname','group_'),array('1663','Fordringar hos andra koncernf',''));
InsertRecord('chartmaster',array('accountcode'),array('1670'),array('accountcode','accountname','group_'),array('1670','Fordringar hos intressef',''));
InsertRecord('chartmaster',array('accountcode'),array('1680'),array('accountcode','accountname','group_'),array('1680','Andra kortfristiga fordringar',''));
InsertRecord('chartmaster',array('accountcode'),array('1681'),array('accountcode','accountname','group_'),array('1681','Utl',''));
InsertRecord('chartmaster',array('accountcode'),array('1682'),array('accountcode','accountname','group_'),array('1682','Kortfristiga l',''));
InsertRecord('chartmaster',array('accountcode'),array('1683'),array('accountcode','accountname','group_'),array('1683','Fordringar f',''));
InsertRecord('chartmaster',array('accountcode'),array('1684'),array('accountcode','accountname','group_'),array('1684','Fordringar hos leverant',''));
InsertRecord('chartmaster',array('accountcode'),array('1685'),array('accountcode','accountname','group_'),array('1685','Fordringar hos n',''));
InsertRecord('chartmaster',array('accountcode'),array('1686'),array('accountcode','accountname','group_'),array('1686','Upparbetad men ej fakturerad int',''));
InsertRecord('chartmaster',array('accountcode'),array('1687'),array('accountcode','accountname','group_'),array('1687','Kortfristig del av l',''));
InsertRecord('chartmaster',array('accountcode'),array('1689'),array('accountcode','accountname','group_'),array('1689','',''));
InsertRecord('chartmaster',array('accountcode'),array('1690'),array('accountcode','accountname','group_'),array('1690','V',''));
InsertRecord('chartmaster',array('accountcode'),array('1700'),array('accountcode','accountname','group_'),array('1700','F','F'));
InsertRecord('chartmaster',array('accountcode'),array('1710'),array('accountcode','accountname','group_'),array('1710','F','F'));
InsertRecord('chartmaster',array('accountcode'),array('1711'),array('accountcode','accountname','group_'),array('1711','F','F'));
InsertRecord('chartmaster',array('accountcode'),array('1720'),array('accountcode','accountname','group_'),array('1720','F','F'));
InsertRecord('chartmaster',array('accountcode'),array('1730'),array('accountcode','accountname','group_'),array('1730','F','F'));
InsertRecord('chartmaster',array('accountcode'),array('1740'),array('accountcode','accountname','group_'),array('1740','F','F'));
InsertRecord('chartmaster',array('accountcode'),array('1750'),array('accountcode','accountname','group_'),array('1750','Upplupna hyresinkomster','F'));
InsertRecord('chartmaster',array('accountcode'),array('1760'),array('accountcode','accountname','group_'),array('1760','Upplupna inkomstr','F'));
InsertRecord('chartmaster',array('accountcode'),array('1770'),array('accountcode','accountname','group_'),array('1770','Tillg','F'));
InsertRecord('chartmaster',array('accountcode'),array('1780'),array('accountcode','accountname','group_'),array('1780','Upplupna avtalsinkomster','F'));
InsertRecord('chartmaster',array('accountcode'),array('1790'),array('accountcode','accountname','group_'),array('1790','','F'));
InsertRecord('chartmaster',array('accountcode'),array('1800'),array('accountcode','accountname','group_'),array('1800','Kortfristiga placeringar (gruppkonto)','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1810'),array('accountcode','accountname','group_'),array('1810','Aktier i b','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1820'),array('accountcode','accountname','group_'),array('1820','Obligationer','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1830'),array('accountcode','accountname','group_'),array('1830','Konvertibla skuldebrev','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1880'),array('accountcode','accountname','group_'),array('1880','Andra kortfristiga placeringar','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1882'),array('accountcode','accountname','group_'),array('1882','Egna aktier','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1886'),array('accountcode','accountname','group_'),array('1886','Aktier och andelar i koncernf','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1889'),array('accountcode','accountname','group_'),array('1889','Aktier och andelar i','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1890'),array('accountcode','accountname','group_'),array('1890','V','Kortfristiga placeringar'));
InsertRecord('chartmaster',array('accountcode'),array('1900'),array('accountcode','accountname','group_'),array('1900','Obsevationskonto','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1910'),array('accountcode','accountname','group_'),array('1910','Kassa','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1911'),array('accountcode','accountname','group_'),array('1911','Huvudkassa','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1912'),array('accountcode','accountname','group_'),array('1912','Kassa 2','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1913'),array('accountcode','accountname','group_'),array('1913','Kassa 3','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1920'),array('accountcode','accountname','group_'),array('1920','Postgiro','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1921'),array('accountcode','accountname','group_'),array('1921','Postgiro 1','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1922'),array('accountcode','accountname','group_'),array('1922','Postgiro 2','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1930'),array('accountcode','accountname','group_'),array('1930','Checkr','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1931'),array('accountcode','accountname','group_'),array('1931','Checkr','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1932'),array('accountcode','accountname','group_'),array('1932','Checkr','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1940'),array('accountcode','accountname','group_'),array('1940','Bank och','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1941'),array('accountcode','accountname','group_'),array('1941','Bankkonto 1','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1942'),array('accountcode','accountname','group_'),array('1942','Bankkonto 2','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1950'),array('accountcode','accountname','group_'),array('1950','Bankcertifikat','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1960'),array('accountcode','accountname','group_'),array('1960','Koncernkonto moderbolag','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1970'),array('accountcode','accountname','group_'),array('1970','S','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1971'),array('accountcode','accountname','group_'),array('1971','Allm','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1972'),array('accountcode','accountname','group_'),array('1972','Upphovsmannakonto','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1973'),array('accountcode','accountname','group_'),array('1973','Skogskonto','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1974'),array('accountcode','accountname','group_'),array('1974','Sp','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('1979'),array('accountcode','accountname','group_'),array('1979','','Kassa och Bank'));
InsertRecord('chartmaster',array('accountcode'),array('2010'),array('accountcode','accountname','group_'),array('2010','Eget kapital - f','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2011'),array('accountcode','accountname','group_'),array('2011','Egna varuuttag','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2012'),array('accountcode','accountname','group_'),array('2012','Avr','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2013'),array('accountcode','accountname','group_'),array('2013','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2014'),array('accountcode','accountname','group_'),array('2014','Upplupna egenavgifer och s','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2017'),array('accountcode','accountname','group_'),array('2017','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2018'),array('accountcode','accountname','group_'),array('2018','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2019'),array('accountcode','accountname','group_'),array('2019','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2020'),array('accountcode','accountname','group_'),array('2020','Eget kapital - del','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2021'),array('accountcode','accountname','group_'),array('2021','Egna varuuttag','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2022'),array('accountcode','accountname','group_'),array('2022','Avr','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2023'),array('accountcode','accountname','group_'),array('2023','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2024'),array('accountcode','accountname','group_'),array('2024','Upplupna egenavgifter och s','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2027'),array('accountcode','accountname','group_'),array('2027','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2028'),array('accountcode','accountname','group_'),array('2028','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2029'),array('accountcode','accountname','group_'),array('2029','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2030'),array('accountcode','accountname','group_'),array('2030','Eget kapital - del','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2031'),array('accountcode','accountname','group_'),array('2031','Egna varuuttag','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2032'),array('accountcode','accountname','group_'),array('2032','Avr','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2033'),array('accountcode','accountname','group_'),array('2033','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2034'),array('accountcode','accountname','group_'),array('2034','Upplupna egenavgifer och s','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2037'),array('accountcode','accountname','group_'),array('2037','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2038'),array('accountcode','accountname','group_'),array('2038','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2039'),array('accountcode','accountname','group_'),array('2039','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2050'),array('accountcode','accountname','group_'),array('2050','Avs','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2080'),array('accountcode','accountname','group_'),array('2080','Bundet eget kapital - aktiebolag, ek,f','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2081'),array('accountcode','accountname','group_'),array('2081','Aktiekapital','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2082'),array('accountcode','accountname','group_'),array('2082','Ej registrerat aktiekapital','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2083'),array('accountcode','accountname','group_'),array('2083','Inbetalda insatser - stiftelsekapital i stiftelse','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2084'),array('accountcode','accountname','group_'),array('2084','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2085'),array('accountcode','accountname','group_'),array('2085','Uppskrivningsfond','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2086'),array('accountcode','accountname','group_'),array('2086','Reservfond - v','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2090'),array('accountcode','accountname','group_'),array('2090','Fritt eget kapital','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2091'),array('accountcode','accountname','group_'),array('2091','Balanserad vinst eller f','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2092'),array('accountcode','accountname','group_'),array('2092','Erh','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2093'),array('accountcode','accountname','group_'),array('2093','Erh','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2098'),array('accountcode','accountname','group_'),array('2098','Vinst eller f','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2099'),array('accountcode','accountname','group_'),array('2099','','Eget kapital'));
InsertRecord('chartmaster',array('accountcode'),array('2150'),array('accountcode','accountname','group_'),array('2150','Ackumulerade','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2151'),array('accountcode','accountname','group_'),array('2151','Ackumulerade','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2152'),array('accountcode','accountname','group_'),array('2152','Ackumulerade','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2153'),array('accountcode','accountname','group_'),array('2153','Ackumulerade','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2160'),array('accountcode','accountname','group_'),array('2160','Ers','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2161'),array('accountcode','accountname','group_'),array('2161','Ers','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2162'),array('accountcode','accountname','group_'),array('2162','Ers','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2163'),array('accountcode','accountname','group_'),array('2163','Ers','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2164'),array('accountcode','accountname','group_'),array('2164','Ers','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2170'),array('accountcode','accountname','group_'),array('2170','Avs','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2171'),array('accountcode','accountname','group_'),array('2171','Allm','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2180'),array('accountcode','accountname','group_'),array('2180','Obeskattade int','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2181'),array('accountcode','accountname','group_'),array('2181','Obeskattade upphovsmannaint','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2185'),array('accountcode','accountname','group_'),array('2185','Obeskattade skogsint','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2190'),array('accountcode','accountname','group_'),array('2190','','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2191'),array('accountcode','accountname','group_'),array('2191','Skillnad mellan bokf','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2195'),array('accountcode','accountname','group_'),array('2195','Valutakursreserv','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2196'),array('accountcode','accountname','group_'),array('2196','Lagerreserv','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2197'),array('accountcode','accountname','group_'),array('2197','Skatteutj','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2199'),array('accountcode','accountname','group_'),array('2199','','Periodiseringsfond vid 1999'));
InsertRecord('chartmaster',array('accountcode'),array('2210'),array('accountcode','accountname','group_'),array('2210','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2211'),array('accountcode','accountname','group_'),array('2211','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2219'),array('accountcode','accountname','group_'),array('2219','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2220'),array('accountcode','accountname','group_'),array('2220','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2250'),array('accountcode','accountname','group_'),array('2250','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2251'),array('accountcode','accountname','group_'),array('2251','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2252'),array('accountcode','accountname','group_'),array('2252','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2259'),array('accountcode','accountname','group_'),array('2259','Avs','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2290'),array('accountcode','accountname','group_'),array('2290','','Avs'));
InsertRecord('chartmaster',array('accountcode'),array('2310'),array('accountcode','accountname','group_'),array('2310','Obligations- och f','L'));
InsertRecord('chartmaster',array('accountcode'),array('2320'),array('accountcode','accountname','group_'),array('2320','Konvertibla l','L'));
InsertRecord('chartmaster',array('accountcode'),array('2330'),array('accountcode','accountname','group_'),array('2330','Checkr','L'));
InsertRecord('chartmaster',array('accountcode'),array('2331'),array('accountcode','accountname','group_'),array('2331','Checkr','L'));
InsertRecord('chartmaster',array('accountcode'),array('2332'),array('accountcode','accountname','group_'),array('2332','Checkr','L'));
InsertRecord('chartmaster',array('accountcode'),array('2333'),array('accountcode','accountname','group_'),array('2333','Utnyttjad checkr','L'));
InsertRecord('chartmaster',array('accountcode'),array('2334'),array('accountcode','accountname','group_'),array('2334','Utnyttjad checkr','L'));
InsertRecord('chartmaster',array('accountcode'),array('2335'),array('accountcode','accountname','group_'),array('2335','Beviljad checkr','L'));
InsertRecord('chartmaster',array('accountcode'),array('2336'),array('accountcode','accountname','group_'),array('2336','Beviljad checkr','L'));
InsertRecord('chartmaster',array('accountcode'),array('2340'),array('accountcode','accountname','group_'),array('2340','Byggnadskreditiv','L'));
InsertRecord('chartmaster',array('accountcode'),array('2350'),array('accountcode','accountname','group_'),array('2350','Andra skulder till kreditinstitut','L'));
InsertRecord('chartmaster',array('accountcode'),array('2351'),array('accountcode','accountname','group_'),array('2351','Fastighetsl','L'));
InsertRecord('chartmaster',array('accountcode'),array('2355'),array('accountcode','accountname','group_'),array('2355','L','L'));
InsertRecord('chartmaster',array('accountcode'),array('2359'),array('accountcode','accountname','group_'),array('2359','','L'));
InsertRecord('chartmaster',array('accountcode'),array('2360'),array('accountcode','accountname','group_'),array('2360','Skulder till koncernf','L'));
InsertRecord('chartmaster',array('accountcode'),array('2361'),array('accountcode','accountname','group_'),array('2361','Skulder till Moderf','L'));
InsertRecord('chartmaster',array('accountcode'),array('2362'),array('accountcode','accountname','group_'),array('2362','Skulder till dotterf','L'));
InsertRecord('chartmaster',array('accountcode'),array('2363'),array('accountcode','accountname','group_'),array('2363','Skulder till andra koncernf','L'));
InsertRecord('chartmaster',array('accountcode'),array('2370'),array('accountcode','accountname','group_'),array('2370','Skulder till intressef','L'));
InsertRecord('chartmaster',array('accountcode'),array('2390'),array('accountcode','accountname','group_'),array('2390','','L'));
InsertRecord('chartmaster',array('accountcode'),array('2391'),array('accountcode','accountname','group_'),array('2391','Avbetalningskontrakt','L'));
InsertRecord('chartmaster',array('accountcode'),array('2392'),array('accountcode','accountname','group_'),array('2392','Villkorliga skulder','L'));
InsertRecord('chartmaster',array('accountcode'),array('2393'),array('accountcode','accountname','group_'),array('2393','L','L'));
InsertRecord('chartmaster',array('accountcode'),array('2394'),array('accountcode','accountname','group_'),array('2394','L','L'));
InsertRecord('chartmaster',array('accountcode'),array('2395'),array('accountcode','accountname','group_'),array('2395','Andra l','L'));
InsertRecord('chartmaster',array('accountcode'),array('2397'),array('accountcode','accountname','group_'),array('2397','Mottagna depositioner','L'));
InsertRecord('chartmaster',array('accountcode'),array('2399'),array('accountcode','accountname','group_'),array('2399','','L'));
InsertRecord('chartmaster',array('accountcode'),array('2410'),array('accountcode','accountname','group_'),array('2410','Kortfristiga skulder till kreditinstitut','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2411'),array('accountcode','accountname','group_'),array('2411','Kortfristiga l','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2417'),array('accountcode','accountname','group_'),array('2417','Kortfristig del av l','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2418'),array('accountcode','accountname','group_'),array('2418','Kortfristig del av checkr','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2419'),array('accountcode','accountname','group_'),array('2419','','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2420'),array('accountcode','accountname','group_'),array('2420','F','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2421'),array('accountcode','accountname','group_'),array('2421','Ej inl','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2429'),array('accountcode','accountname','group_'),array('2429','','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2430'),array('accountcode','accountname','group_'),array('2430','P','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2431'),array('accountcode','accountname','group_'),array('2431','P','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2435'),array('accountcode','accountname','group_'),array('2435','Fakturerad men ej upparbetad int','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2438'),array('accountcode','accountname','group_'),array('2438','P','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2440'),array('accountcode','accountname','group_'),array('2440','Leverant','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2443'),array('accountcode','accountname','group_'),array('2443','Konsignationsskulder','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2445'),array('accountcode','accountname','group_'),array('2445','Tvistiga leverant','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2448'),array('accountcode','accountname','group_'),array('2448','Ej reskontraf','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2460'),array('accountcode','accountname','group_'),array('2460','Leverant','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2461'),array('accountcode','accountname','group_'),array('2461','Leverant','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2462'),array('accountcode','accountname','group_'),array('2462','Leverant','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2463'),array('accountcode','accountname','group_'),array('2463','Leverant','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2470'),array('accountcode','accountname','group_'),array('2470','Leverant','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2490'),array('accountcode','accountname','group_'),array('2490','','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2491'),array('accountcode','accountname','group_'),array('2491','V','Kortfristiga skulder till kred'));
InsertRecord('chartmaster',array('accountcode'),array('2510'),array('accountcode','accountname','group_'),array('2510','Skatteskulder','Skatteskulder'));
InsertRecord('chartmaster',array('accountcode'),array('2511'),array('accountcode','accountname','group_'),array('2511','Debiterad kvarst','Skatteskulder'));
InsertRecord('chartmaster',array('accountcode'),array('2512'),array('accountcode','accountname','group_'),array('2512','Ber','Skatteskulder'));
InsertRecord('chartmaster',array('accountcode'),array('2513'),array('accountcode','accountname','group_'),array('2513','Ber','Skatteskulder'));
InsertRecord('chartmaster',array('accountcode'),array('2514'),array('accountcode','accountname','group_'),array('2514','Ber','Skatteskulder'));
InsertRecord('chartmaster',array('accountcode'),array('2515'),array('accountcode','accountname','group_'),array('2515','Ber','Skatteskulder'));
InsertRecord('chartmaster',array('accountcode'),array('2518'),array('accountcode','accountname','group_'),array('2518','Betald prelimin','Skatteskulder'));
InsertRecord('chartmaster',array('accountcode'),array('2610'),array('accountcode','accountname','group_'),array('2610','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2611'),array('accountcode','accountname','group_'),array('2611','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2612'),array('accountcode','accountname','group_'),array('2612','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2613'),array('accountcode','accountname','group_'),array('2613','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2614'),array('accountcode','accountname','group_'),array('2614','Ber','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2615'),array('accountcode','accountname','group_'),array('2615','Ber','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2618'),array('accountcode','accountname','group_'),array('2618','Vilande utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2620'),array('accountcode','accountname','group_'),array('2620','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2621'),array('accountcode','accountname','group_'),array('2621','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2622'),array('accountcode','accountname','group_'),array('2622','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2628'),array('accountcode','accountname','group_'),array('2628','Vilande utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2630'),array('accountcode','accountname','group_'),array('2630','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2631'),array('accountcode','accountname','group_'),array('2631','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2632'),array('accountcode','accountname','group_'),array('2632','Utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2638'),array('accountcode','accountname','group_'),array('2638','Vilande utg','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2640'),array('accountcode','accountname','group_'),array('2640','Ing','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2641'),array('accountcode','accountname','group_'),array('2641','Debiterad ing','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2642'),array('accountcode','accountname','group_'),array('2642','Debiterad ing','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2645'),array('accountcode','accountname','group_'),array('2645','Ber','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2648'),array('accountcode','accountname','group_'),array('2648','Vilande ing','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2649'),array('accountcode','accountname','group_'),array('2649','Ing','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2650'),array('accountcode','accountname','group_'),array('2650','Redovisningskonto f','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2660'),array('accountcode','accountname','group_'),array('2660','S','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2661'),array('accountcode','accountname','group_'),array('2661','Reklamskatt','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2669'),array('accountcode','accountname','group_'),array('2669','','Moms och s'));
InsertRecord('chartmaster',array('accountcode'),array('2710'),array('accountcode','accountname','group_'),array('2710','Personalens k','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2711'),array('accountcode','accountname','group_'),array('2711','Inneh','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2718'),array('accountcode','accountname','group_'),array('2718','Betald k','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2730'),array('accountcode','accountname','group_'),array('2730','Lagstadgade sociala avgifter och s','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2731'),array('accountcode','accountname','group_'),array('2731','Avr','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2732'),array('accountcode','accountname','group_'),array('2732','Avr','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2738'),array('accountcode','accountname','group_'),array('2738','Betalda lagstadgade sociala avgifter och s','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2740'),array('accountcode','accountname','group_'),array('2740','Avtalade sociala avgifter','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2741'),array('accountcode','accountname','group_'),array('2741','Avr','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2748'),array('accountcode','accountname','group_'),array('2748','Betalade avtalade sociala avgifter','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2750'),array('accountcode','accountname','group_'),array('2750','Utm','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2760'),array('accountcode','accountname','group_'),array('2760','Semesterkassa','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2790'),array('accountcode','accountname','group_'),array('2790','','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2791'),array('accountcode','accountname','group_'),array('2791','Personalens intressekonto','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2792'),array('accountcode','accountname','group_'),array('2792','L','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2793'),array('accountcode','accountname','group_'),array('2793','Gruppf','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2794'),array('accountcode','accountname','group_'),array('2794','Fackf','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('2795'),array('accountcode','accountname','group_'),array('2795','M','Personalens skatter, avgifter'));
InsertRecord('chartmaster',array('accountcode'),array('3439'),array('accountcode','accountname','group_'),array('3439','F','Kortfristiga skulder till kred'));
?>