<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Assets'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Liabilities'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Income'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Costs'));
InsertRecord('accountgroups',array('groupname'),array('保留盈馀'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('保留盈馀','20','0','7000',''));
InsertRecord('accountgroups',array('groupname'),array('其它盈馀'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('其它盈馀','30','1','10000',''));
InsertRecord('accountgroups',array('groupname'),array('存货资产'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('存货资产','10','0','2000',''));
InsertRecord('accountgroups',array('groupname'),array('日常及管理支出'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('日常及管理支出','40','1','13000',''));
InsertRecord('accountgroups',array('groupname'),array('流动负债'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('流动负债','20','0','4000',''));
InsertRecord('accountgroups',array('groupname'),array('流动资产'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('流动资产','10','0','1000',''));
InsertRecord('accountgroups',array('groupname'),array('股份资本'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('股份资本','20','0','6000',''));
InsertRecord('accountgroups',array('groupname'),array('薪资支出'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('薪资支出','40','1','12000',''));
InsertRecord('accountgroups',array('groupname'),array('谘询盈馀'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('谘询盈馀','30','1','9000',''));
InsertRecord('accountgroups',array('groupname'),array('货销成本'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('货销成本','40','1','11000',''));
InsertRecord('accountgroups',array('groupname'),array('资本资产'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('资本资产','10','0','3000',''));
InsertRecord('accountgroups',array('groupname'),array('销售盈馀'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('销售盈馀','30','1','8000',''));
InsertRecord('accountgroups',array('groupname'),array('长期负债'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('长期负债','20','0','5000',''));
InsertRecord('chartmaster',array('accountcaode'),array('1061'),array('accountcode','accountname','group_'),array('1061','支票户头','流动资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1065'),array('accountcode','accountname','group_'),array('1065','零用金','流动资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1200'),array('accountcode','accountname','group_'),array('1200','应收帐款','流动资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1205'),array('accountcode','accountname','group_'),array('1205','呆帐备抵','流动资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1520'),array('accountcode','accountname','group_'),array('1520','库存 / 硬体','存货资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1530'),array('accountcode','accountname','group_'),array('1530','库存 / 软体','存货资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1540'),array('accountcode','accountname','group_'),array('1540','库存 / 二级市场零件','存货资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1820'),array('accountcode','accountname','group_'),array('1820','办公室装璜及设备','资本资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1825'),array('accountcode','accountname','group_'),array('1825','累计分期付款 - 装璜及设备.','资本资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1840'),array('accountcode','accountname','group_'),array('1840','运输工具','资本资产'));
InsertRecord('chartmaster',array('accountcaode'),array('1845'),array('accountcode','accountname','group_'),array('1845','累计分期付款 - 运输工具','资本资产'));
InsertRecord('chartmaster',array('accountcaode'),array('2100'),array('accountcode','accountname','group_'),array('2100','应付帐款','流动负债'));
InsertRecord('chartmaster',array('accountcaode'),array('2160'),array('accountcode','accountname','group_'),array('2160','应付公司税','流动负债'));
InsertRecord('chartmaster',array('accountcaode'),array('2190'),array('accountcode','accountname','group_'),array('2190','应付所得税','流动负债'));
InsertRecord('chartmaster',array('accountcaode'),array('2310'),array('accountcode','accountname','group_'),array('2310','商品服务税','流动负债'));
InsertRecord('chartmaster',array('accountcaode'),array('2311'),array('accountcode','accountname','group_'),array('2311','地方税','流动负债'));
InsertRecord('chartmaster',array('accountcaode'),array('2620'),array('accountcode','accountname','group_'),array('2620','银行借款','长期负债'));
InsertRecord('chartmaster',array('accountcaode'),array('2680'),array('accountcode','accountname','group_'),array('2680','股东贷款','长期负债'));
InsertRecord('chartmaster',array('accountcaode'),array('3350'),array('accountcode','accountname','group_'),array('3350','普通股份','股份资本'));
InsertRecord('chartmaster',array('accountcaode'),array('3590'),array('accountcode','accountname','group_'),array('3590','保留盈馀 - 去年度','保留盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('3600'),array('accountcode','accountname','group_'),array('3600','流动盈馀','保留盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4020'),array('accountcode','accountname','group_'),array('4020','销售 / 硬体','销售盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4030'),array('accountcode','accountname','group_'),array('4030','销售 / 软体','销售盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4040'),array('accountcode','accountname','group_'),array('4040','销售 / 二级市场零件','销售盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4320'),array('accountcode','accountname','group_'),array('4320','谘询','谘询盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4330'),array('accountcode','accountname','group_'),array('4330','程式设计','谘询盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4430'),array('accountcode','accountname','group_'),array('4430','运销费','其它盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4440'),array('accountcode','accountname','group_'),array('4440','利息','其它盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('4450'),array('accountcode','accountname','group_'),array('4450','Foreign Exchange Gain','其它盈馀'));
InsertRecord('chartmaster',array('accountcaode'),array('5010'),array('accountcode','accountname','group_'),array('5010','采购','货销成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5020'),array('accountcode','accountname','group_'),array('5020','货销成本 / 硬体','货销成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5030'),array('accountcode','accountname','group_'),array('5030','货销成本 / 软体','货销成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5040'),array('accountcode','accountname','group_'),array('5040','货销成本 / 二级市场零件','货销成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5100'),array('accountcode','accountname','group_'),array('5100','运费','货销成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5410'),array('accountcode','accountname','group_'),array('5410','薪资','薪资支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5420'),array('accountcode','accountname','group_'),array('5420','保险支出','薪资支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5430'),array('accountcode','accountname','group_'),array('5430','退休金支出','薪资支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5440'),array('accountcode','accountname','group_'),array('5440','补偿金支出','薪资支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5470'),array('accountcode','accountname','group_'),array('5470','员工福利','薪资支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5610'),array('accountcode','accountname','group_'),array('5610','会计法务','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5615'),array('accountcode','accountname','group_'),array('5615','广告行销','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5620'),array('accountcode','accountname','group_'),array('5620','坏帐','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5660'),array('accountcode','accountname','group_'),array('5660','分期支出','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5680'),array('accountcode','accountname','group_'),array('5680','所得税','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5685'),array('accountcode','accountname','group_'),array('5685','保险','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5690'),array('accountcode','accountname','group_'),array('5690','利息及银行手续费','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5700'),array('accountcode','accountname','group_'),array('5700','办公用品','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5760'),array('accountcode','accountname','group_'),array('5760','租金','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5765'),array('accountcode','accountname','group_'),array('5765','维修管理费','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5780'),array('accountcode','accountname','group_'),array('5780','电信费','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5781'),array('accountcode','accountname','group_'),array('5781','网路连线费','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5785'),array('accountcode','accountname','group_'),array('5785','旅费及娱乐','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5790'),array('accountcode','accountname','group_'),array('5790','工具','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5795'),array('accountcode','accountname','group_'),array('5795','注册费','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5800'),array('accountcode','accountname','group_'),array('5800','权利金','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5810'),array('accountcode','accountname','group_'),array('5810','Foreign Exchange Loss','日常及管理支出'));
?>