<?php
InsertRecord('accountsection',array('sectionid'),array(10),array('sectionid','sectionname'),array(10,'Assets'));
InsertRecord('accountsection',array('sectionid'),array(20),array('sectionid','sectionname'),array(20,'Liabilities'));
InsertRecord('accountsection',array('sectionid'),array(30),array('sectionid','sectionname'),array(30,'Income'));
InsertRecord('accountsection',array('sectionid'),array(40),array('sectionid','sectionname'),array(40,'Costs'));
InsertRecord('accountgroups',array('groupname'),array('保留盈餘'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('保留盈餘','20','0','7000',''));
InsertRecord('accountgroups',array('groupname'),array('其它盈餘'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('其它盈餘','30','1','10000',''));
InsertRecord('accountgroups',array('groupname'),array('存貨資產'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('存貨資產','10','0','2000',''));
InsertRecord('accountgroups',array('groupname'),array('日常及管理支出'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('日常及管理支出','40','1','13000',''));
InsertRecord('accountgroups',array('groupname'),array('流動負債'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('流動負債','20','0','4000',''));
InsertRecord('accountgroups',array('groupname'),array('流動資產'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('流動資產','10','0','1000',''));
InsertRecord('accountgroups',array('groupname'),array('股份資本'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('股份資本','20','0','6000',''));
InsertRecord('accountgroups',array('groupname'),array('薪資支出'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('薪資支出','40','1','12000',''));
InsertRecord('accountgroups',array('groupname'),array('諮詢盈餘'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('諮詢盈餘','30','1','9000',''));
InsertRecord('accountgroups',array('groupname'),array('貨銷成本'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('貨銷成本','40','1','11000',''));
InsertRecord('accountgroups',array('groupname'),array('資本資產'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('資本資產','10','0','3000',''));
InsertRecord('accountgroups',array('groupname'),array('銷售盈餘'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('銷售盈餘','30','1','8000',''));
InsertRecord('accountgroups',array('groupname'),array('長期負債'),array('groupname','sectioninaccounts','pandl','sequenceintb','parentgroupname'),array('長期負債','20','0','5000',''));
InsertRecord('chartmaster',array('accountcaode'),array('1061'),array('accountcode','accountname','group_'),array('1061','支票戶頭','流動資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1065'),array('accountcode','accountname','group_'),array('1065','零用金','流動資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1200'),array('accountcode','accountname','group_'),array('1200','應收帳款','流動資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1205'),array('accountcode','accountname','group_'),array('1205','呆帳備抵','流動資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1520'),array('accountcode','accountname','group_'),array('1520','庫存 / 硬體','存貨資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1530'),array('accountcode','accountname','group_'),array('1530','庫存 / 軟體','存貨資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1540'),array('accountcode','accountname','group_'),array('1540','庫存 / 二級市場零件','存貨資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1820'),array('accountcode','accountname','group_'),array('1820','辦公室裝璜及設備','資本資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1825'),array('accountcode','accountname','group_'),array('1825','累計分期付款 - 裝璜及設備.','資本資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1840'),array('accountcode','accountname','group_'),array('1840','運輸工具','資本資產'));
InsertRecord('chartmaster',array('accountcaode'),array('1845'),array('accountcode','accountname','group_'),array('1845','累計分期付款 - 運輸工具','資本資產'));
InsertRecord('chartmaster',array('accountcaode'),array('2100'),array('accountcode','accountname','group_'),array('2100','應付帳款','流動負債'));
InsertRecord('chartmaster',array('accountcaode'),array('2160'),array('accountcode','accountname','group_'),array('2160','應付公司稅','流動負債'));
InsertRecord('chartmaster',array('accountcaode'),array('2190'),array('accountcode','accountname','group_'),array('2190','應付所得稅','流動負債'));
InsertRecord('chartmaster',array('accountcaode'),array('2310'),array('accountcode','accountname','group_'),array('2310','商品服務稅','流動負債'));
InsertRecord('chartmaster',array('accountcaode'),array('2311'),array('accountcode','accountname','group_'),array('2311','地方稅','流動負債'));
InsertRecord('chartmaster',array('accountcaode'),array('2620'),array('accountcode','accountname','group_'),array('2620','銀行借款','長期負債'));
InsertRecord('chartmaster',array('accountcaode'),array('2680'),array('accountcode','accountname','group_'),array('2680','股東貸款','長期負債'));
InsertRecord('chartmaster',array('accountcaode'),array('3350'),array('accountcode','accountname','group_'),array('3350','普通股份','股份資本'));
InsertRecord('chartmaster',array('accountcaode'),array('3590'),array('accountcode','accountname','group_'),array('3590','保留盈餘 - 去年度','保留盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('3600'),array('accountcode','accountname','group_'),array('3600','流動盈餘','保留盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4020'),array('accountcode','accountname','group_'),array('4020','銷售 / 硬體','銷售盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4030'),array('accountcode','accountname','group_'),array('4030','銷售 / 軟體','銷售盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4040'),array('accountcode','accountname','group_'),array('4040','銷售 / 二級市場零件','銷售盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4320'),array('accountcode','accountname','group_'),array('4320','諮詢','諮詢盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4330'),array('accountcode','accountname','group_'),array('4330','程式設計','諮詢盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4430'),array('accountcode','accountname','group_'),array('4430','運銷費','其它盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4440'),array('accountcode','accountname','group_'),array('4440','利息','其它盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('4450'),array('accountcode','accountname','group_'),array('4450','Foreign Exchange Gain','其它盈餘'));
InsertRecord('chartmaster',array('accountcaode'),array('5010'),array('accountcode','accountname','group_'),array('5010','採購','貨銷成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5020'),array('accountcode','accountname','group_'),array('5020','貨銷成本 / 硬體','貨銷成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5030'),array('accountcode','accountname','group_'),array('5030','貨銷成本 / 軟體','貨銷成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5040'),array('accountcode','accountname','group_'),array('5040','貨銷成本 / 二級市場零件','貨銷成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5100'),array('accountcode','accountname','group_'),array('5100','運費','貨銷成本'));
InsertRecord('chartmaster',array('accountcaode'),array('5410'),array('accountcode','accountname','group_'),array('5410','薪資','薪資支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5420'),array('accountcode','accountname','group_'),array('5420','保險支出','薪資支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5430'),array('accountcode','accountname','group_'),array('5430','退休金支出','薪資支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5440'),array('accountcode','accountname','group_'),array('5440','補償金支出','薪資支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5470'),array('accountcode','accountname','group_'),array('5470','員工福利','薪資支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5610'),array('accountcode','accountname','group_'),array('5610','會計法務','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5615'),array('accountcode','accountname','group_'),array('5615','廣告行銷','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5620'),array('accountcode','accountname','group_'),array('5620','壞帳','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5660'),array('accountcode','accountname','group_'),array('5660','分期支出','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5680'),array('accountcode','accountname','group_'),array('5680','所得稅','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5685'),array('accountcode','accountname','group_'),array('5685','保險','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5690'),array('accountcode','accountname','group_'),array('5690','利息及銀行手續費','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5700'),array('accountcode','accountname','group_'),array('5700','辦公用品','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5760'),array('accountcode','accountname','group_'),array('5760','租金','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5765'),array('accountcode','accountname','group_'),array('5765','維修管理費','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5780'),array('accountcode','accountname','group_'),array('5780','電信費','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5781'),array('accountcode','accountname','group_'),array('5781','網路連線費','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5785'),array('accountcode','accountname','group_'),array('5785','旅費及娛樂','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5790'),array('accountcode','accountname','group_'),array('5790','工具','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5795'),array('accountcode','accountname','group_'),array('5795','註冊費','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5800'),array('accountcode','accountname','group_'),array('5800','權利金','日常及管理支出'));
InsertRecord('chartmaster',array('accountcaode'),array('5810'),array('accountcode','accountname','group_'),array('5810','Foreign Exchange Loss','日常及管理支出'));
?>