<?php

CreateTable('config',
"CREATE TABLE `config` (
  `confname` varchar(35) NOT NULL DEFAULT '',
  `confvalue` text NOT NULL,
  PRIMARY KEY (`confname`)
)", $db);

NewConfigValue('AllowOrderLineItemNarrative',1, $db);
NewConfigValue('AllowSalesOfZeroCostItems',0, $db);
NewConfigValue('AutoAuthorisePO',1, $db);
NewConfigValue('AutoCreateWOs',1, $db);
NewConfigValue('AutoDebtorNo',0, $db);
NewConfigValue('AutoIssue',1, $db);
NewConfigValue('CheckCreditLimits',1, $db);
NewConfigValue('Check_Price_Charged_vs_Order_Price',1, $db);
NewConfigValue('Check_Qty_Charged_vs_Del_Qty',1, $db);
NewConfigValue('CountryOfOperation','KE', $db);
NewConfigValue('CreditingControlledItems_MustExist',0, $db);

NewConfigValue('DB_Maintenance',0, $db);
NewConfigValue('DB_Maintenance_LastRun',date('Y-m-d'), $db);
NewConfigValue('DefaultBlindPackNote',1, $db);
NewConfigValue('DefaultCreditLimit',1000, $db);
NewConfigValue('DefaultCustomerType',1, $db);
NewConfigValue('DefaultDateFormat','d/m/Y', $db);
NewConfigValue('DefaultDisplayRecordsMax',50, $db);
NewConfigValue('DefaultFactoryLocation','', $db);
NewConfigValue('DefaultPriceList','', $db);
NewConfigValue('DefaultSupplierType',1, $db);
NewConfigValue('DefaultTaxCategory',1, $db);
NewConfigValue('DefaultTheme','aguapop', $db);
NewConfigValue('Default_Shipper',1, $db);
NewConfigValue('DefineControlledOnWOEntry',1, $db);
NewConfigValue('DispatchCutOffTime',14, $db);
NewConfigValue('DoFreightCalc',0, $db);
NewConfigValue('EDIHeaderMsgId','D:01B:UN:EAN010', $db);
NewConfigValue('EDIReference','KWAMOJA', $db);
NewConfigValue('EDI_Incoming_Orders','EDI_Incoming_Orders', $db);
NewConfigValue('EDI_MsgPending','EDI_MsgPending', $db);
NewConfigValue('EDI_MsgSent','EDI_Sent', $db);
NewConfigValue('ExchangeRateFeed','ECB', $db);
NewConfigValue('Extended_CustomerInfo',0, $db);
NewConfigValue('Extended_SupplierInfo',0, $db);
NewConfigValue('FactoryManagerEmail','manager@company.com', $db);
NewConfigValue('FreightChargeAppliesIfLessThan',1000, $db);
NewConfigValue('FreightTaxCategory',1, $db);
NewConfigValue('FrequentlyOrderedItems',0, $db);
NewConfigValue('geocode_integration',0, $db);
NewConfigValue('HTTPS_Only',0, $db);
NewConfigValue('InventoryManagerEmail','test@company.com', $db);
NewConfigValue('InvoicePortraitFormat',1, $db);
NewConfigValue('ItemDescriptionLanguages','', $db);
NewConfigValue('LogPath','', $db);
NewConfigValue('LogSeverity',0, $db);
NewConfigValue('MaxImageSize',300, $db);
NewConfigValue('MonthsAuditTrail',1, $db);
NewConfigValue('NumberOfMonthMustBeShown',6, $db);
NewConfigValue('NumberOfPeriodsOfStockUsage',12, $db);
NewConfigValue('OverChargeProportion',30, $db);
NewConfigValue('OverReceiveProportion',20, $db);
NewConfigValue('PackNoteFormat',1, $db);
NewConfigValue('PageLength',48, $db);
NewConfigValue('part_pics_dir','part_pics', $db);
NewConfigValue('PastDueDays1',30, $db);
NewConfigValue('PastDueDays2',60, $db);
NewConfigValue('PO_AllowSameItemMultipleTimes',1, $db);
NewConfigValue('ProhibitJournalsToControlAccounts',1, $db);
NewConfigValue('ProhibitNegativeStock',1, $db);
NewConfigValue('ProhibitPostingsBefore','1900-01-01', $db);
NewConfigValue('PurchasingManagerEmail','test@company.com', $db);
NewConfigValue('QuickEntries',10, $db);
NewConfigValue('RadioBeaconFileCounter','/home/RadioBeacon/FileCounter', $db);
NewConfigValue('RadioBeaconFTP_user_name','RadioBeacon ftp server user name', $db);
NewConfigValue('RadioBeaconHomeDir','/home/RadioBeacon', $db);
NewConfigValue('RadioBeaconStockLocation','BL', $db);
NewConfigValue('RadioBraconFTP_server','192.168.2.2', $db);
NewConfigValue('RadioBreaconFilePrefix','ORDXX', $db);
NewConfigValue('RadionBeaconFTP_user_pass','Radio Beacon remote ftp server password', $db);
NewConfigValue('reports_dir','EDI_Sent', $db);
NewConfigValue('RequirePickingNote',0, $db);
NewConfigValue('RomalpaClause','Ownership will not pass to the buyer until the goods have been paid for in full.', $db);
NewConfigValue('ShopAboutUs','', $db);
NewConfigValue('ShopAdditionalStockLocations','', $db);
NewConfigValue('ShopAllowBankTransfer',1, $db);
NewConfigValue('ShopAllowCreditCards',1, $db);
NewConfigValue('ShopAllowPayPal',1, $db);
NewConfigValue('ShopAllowSurcharges',1, $db);
NewConfigValue('ShopBankTransferSurcharge',0, $db);
NewConfigValue('ShopBranchCode','', $db);
NewConfigValue('ShopContactUs','', $db);
NewConfigValue('ShopCreditCardBankAccount',1030, $db);
NewConfigValue('ShopCreditCardGateway','PayFlowPro', $db);
NewConfigValue('ShopCreditCardSurcharge',0.029, $db);
NewConfigValue('ShopDebtorNo','', $db);
NewConfigValue('ShopFreightModule','ShopFreightMethod', $db);
NewConfigValue('ShopFreightPolicy','', $db);
NewConfigValue('ShopManagerEmail','', $db);
NewConfigValue('ShopMode','', $db);
NewConfigValue('ShopName','', $db);
NewConfigValue('ShopPayFlowMerchant','', $db);
NewConfigValue('ShopPayFlowPassword','', $db);
NewConfigValue('ShopPayFlowUser','', $db);
NewConfigValue('ShopPayFlowVendor','', $db);
NewConfigValue('ShopPayPalBankAccount',1030, $db);
NewConfigValue('ShopPaypalCommissionAccount',7220, $db);
NewConfigValue('ShopPayPalPassword','', $db);
NewConfigValue('ShopPayPalProPassword','', $db);
NewConfigValue('ShopPayPalProSignature','', $db);
NewConfigValue('ShopPayPalProUser','', $db);
NewConfigValue('ShopPayPalSignature','', $db);
NewConfigValue('ShopPayPalSurcharge',0.034, $db);
NewConfigValue('ShopPayPalUser','', $db);
NewConfigValue('ShopPrivacyStatement','', $db);
NewConfigValue('ShopShowInfoLinks',1, $db);
NewConfigValue('ShopShowLeftCategoryMenu',1, $db);
NewConfigValue('ShopShowLogoAndShopName',1, $db);
NewConfigValue('ShopShowOnlyAvailableItems',0, $db);
NewConfigValue('ShopShowQOHColumn',1, $db);
NewConfigValue('ShopShowTopCategoryMenu',1, $db);
NewConfigValue('ShopStockLocations',1, $db);
NewConfigValue('ShopSurchargeStockID','', $db);
NewConfigValue('ShopSwipeHQAPIKey','', $db);
NewConfigValue('ShopSwipeHQMerchantID','', $db);
NewConfigValue('ShopTermsConditions','', $db);
NewConfigValue('ShopTitle','Shop Home', $db);
NewConfigValue('ShowStockidOnImages',0, $db);
NewConfigValue('ShowValueOnGRN',1, $db);
NewConfigValue('Show_Settled_LastMonth',1, $db);
NewConfigValue('SmtpSetting',0, $db);
NewConfigValue('SO_AllowSameItemMultipleTimes',1, $db);
NewConfigValue('StandardCostDecimalPlaces',2, $db);
NewConfigValue('TaxAuthorityReferenceName','', $db);
NewConfigValue('UpdateCurrencyRatesDaily',0, $db);
NewConfigValue('VersionNumber','13.10.0', $db);
NewConfigValue('vtiger_integration',0, $db);
NewConfigValue('WeightedAverageCosting',1, $db);
NewConfigValue('WikiApp','Disabled', $db);
NewConfigValue('WikiPath','wiki', $db);
NewConfigValue('WorkingDaysWeek',5, $db);
NewConfigValue('YearEnd',3, $db);

NewConfigValue('DBUpdateNumber',HighestFileName($PathPrefix), $db);

?>