<?php

/* This file contains the code to post GL transactions.

This file can be included on any page that needs GL postings to be posted eg inquiries or GL reports
GL posting thus becomes an invisible/automatic process to the user

The logic of GL posting consists of:


Then looping through all unposted GL transactions in GLTrans table and

1. Debit amounts increase the charge in the period for the account and credit amounts decrease the charge.
2. Chart Details records for all following periods have the b/fwd balance increased for debit amounts and decreased for credits.
3. Once these updates are done the GLTrans record is flagged as posted.


Notes:

ChartDetail records should already exist - they are created (from includes/DateFunctions.in GetPeriod) when a new period is created or when a new GL account is created for all periods in the periods table. However, we may need to create new ones if the user posts back to a period before periods are currently set up - which is not actually possible with the config parameter ProhibitGLPostingsBefore set (However, is a problem when it is not set)
*/


$FirstPeriodResult = DB_query("SELECT MIN(periodno) FROM periods");
$FirstPeriodRow = DB_fetch_row($FirstPeriodResult);
$CreateFrom = $FirstPeriodRow[0];

if (is_null($FirstPeriodRow[0])) {
	//There are no periods defined
	$InsertFirstPeriodResult = DB_query("INSERT INTO periods VALUES (-1,'" . Date('Y-m-d', mktime(0, 0, 0, Date('m') - 1, 0, Date('Y'))) . "')", _('Could not insert first period'));
	$InsertFirstPeriodResult = DB_query("INSERT INTO periods VALUES (0,'" . Date('Y-m-d', mktime(0, 0, 0, Date('m') + 1, 0, Date('Y'))) . "')", _('Could not insert first period'));
	$InsertFirstPeriodResult = DB_query("INSERT INTO periods VALUES (1,'" . Date('Y-m-d', mktime(0, 0, 0, Date('m') + 2, 0, Date('Y'))) . "')", _('Could not insert second period'));
	$CreateFrom = -1;
}

$LastPeriodResult = DB_query("SELECT MAX(periodno) FROM periods");
$LastPeriodRow = DB_fetch_row($LastPeriodResult);


$CreateTo = $LastPeriodRow[0];



/*First off see if there are in fact any chartdetails */

$SQL = "SELECT chartmaster.accountcode, MIN(periods.periodno) AS startperiod
				FROM (chartmaster CROSS JOIN periods)
				LEFT JOIN chartdetails ON chartmaster.accountcode = chartdetails.accountcode
				AND periods.periodno = chartdetails.period
				WHERE (periods.periodno BETWEEN '" . $CreateFrom . "' AND '" . $CreateTo . "')
				AND chartdetails.actual IS NULL
				GROUP BY chartmaster.accountcode";

$ChartDetailsNotSetUpResult = DB_query($SQL, _('Could not test to see that all chart detail records properly initiated'));

if (DB_num_rows($ChartDetailsNotSetUpResult) > 0) {

	/*Now insert the chartdetails records that do not already exist */
	$SQL = "INSERT INTO chartdetails (accountcode, period)
					SELECT chartmaster.accountcode, periods.periodno
					FROM (chartmaster CROSS JOIN periods)
					LEFT JOIN chartdetails ON chartmaster.accountcode = chartdetails.accountcode
					AND periods.periodno = chartdetails.period
					WHERE (periods.periodno BETWEEN '" . $CreateFrom . "' AND '" . $CreateTo . "')
					AND chartdetails.accountcode IS NULL";

	$ErrMsg = _('Inserting new chart details records required failed because');
	$InsChartDetailsRecords = DB_query($SQL, $ErrMsg);
}



/*All the ChartDetail records should have been created now and be available to accept postings */

for ($CurrPeriod = $CreateFrom; $CurrPeriod <= $CreateTo; $CurrPeriod++) {
/*
	$CheckSQL = "SELECT SUM(amount) as checksum
						FROM gltrans
						WHERE posted=0
							AND periodno='" . $CurrPeriod . "'
						ORDER BY account";
	$CheckResult = DB_query($CheckSQL);
	$CheckRow = DB_fetch_array($CheckResult);

	if ($CheckRow['checksum'] != 0) {
		$Title = _('Error with GL balances');
		include('includes/header.inc');
		prnMsg(_('The balances on the general ledger that are about to be posted do not balance.') . '<br />' . _('Please see your system administrator'), 'error');
		include('includes/footer.inc');
		exit;
	}
*/
	$SQL = "SELECT counterindex,
					periodno,
					account,
					amount
				FROM gltrans
				WHERE posted=0
					AND periodno='" . $CurrPeriod . "'
				ORDER BY account";

	$UnpostedTransResult = DB_query($SQL);

	$TransStart = DB_Txn_Begin();
	$CurrentAccount = '0';
	$TotalAmount = 0;
	while ($UnpostedTrans = DB_fetch_array($UnpostedTransResult)) {

		$CheckCurrentPeriodSQL = "SELECT COUNT(actual) as periodexists
										FROM chartdetails
										WHERE  accountcode = '" . $UnpostedTrans['account'] . "'
											AND period= '" . $CurrPeriod . "'";
		$CheckCurrentPeriodResult = DB_query($CheckCurrentPeriodSQL);
		$CheckCurrentPeriodRow = DB_fetch_array($CheckCurrentPeriodResult);

		$CheckNextPeriodSQL = "SELECT COUNT(actual) as periodexists
										FROM chartdetails
										WHERE  accountcode = '" . $UnpostedTrans['account'] . "'
											AND period= '" . ($CurrPeriod + 1) . "'";
		$CheckNextPeriodResult = DB_query($CheckNextPeriodSQL);
		$CheckNextPeriodRow = DB_fetch_array($CheckNextPeriodResult);

		if ($CheckCurrentPeriodRow['periodexists'] == 0 or $CheckNextPeriodRow['periodexists'] == 0) {
			$Title = _('Error with GL periods');
			include('includes/header.inc');
			prnMsg(_('You are trying to post to periods that are not setup in the chartdetails table.') . '<br />' . _('Please see your system administrator'), 'error');
			include('includes/footer.inc');
			exit;
		}

		if ($CurrentAccount != $UnpostedTrans['account']) {
			if ($CurrentAccount != 0) {
				$SQL = "UPDATE chartdetails SET actual = actual + " . $TotalAmount . "
						WHERE accountcode = '" . $CurrentAccount . "'
						AND period= '" . $CurrPeriod . "'";
				$PostPrd = DB_query($SQL);
				/*Update the BFwd for all following ChartDetail records */
				$SQL = "UPDATE chartdetails SET bfwd = bfwd + " . $TotalAmount . "
						WHERE accountcode = '" . $CurrentAccount . "'
						AND period > '" . $CurrPeriod . "'";
				$PostBFwds = DB_query($SQL);
			}
			$TotalAmount = 0;
		}
		$CurrentAccount = $UnpostedTrans['account'];
		$TotalAmount += $UnpostedTrans['amount'];
	}
	// There will be one account still to post after the loop
	if ($CurrentAccount != 0) {
		$SQL = "UPDATE chartdetails SET actual = actual + " . $TotalAmount . "
				WHERE accountcode = '" . $CurrentAccount . "'
				AND period= '" . $CurrPeriod . "'";
		$PostPrd = DB_query($SQL);
		/*Update the BFwd for all following ChartDetail records */
		$SQL = "UPDATE chartdetails SET bfwd = bfwd + " . $TotalAmount . "
				WHERE accountcode = '" . $CurrentAccount . "'
				AND period > '" . $CurrPeriod . "'";
		$PostBFwds = DB_query($SQL);
	}

	$SQL = "UPDATE gltrans SET posted = 1 WHERE periodno = '" . $CurrPeriod . "' AND posted=0";
	$Posted = DB_query($SQL);

	$TransCommit = DB_Txn_Commit();
}

?>